import type { StudyLesson, StudyQuestion } from "./academy-types";

// Casos autorais com restrições concorrentes e alternativas plausíveis.
// Cada caso possui quatro decisões: análise, ação, acompanhamento e transferência.
type Choice = [prompt: string, answer: string, alternatives: [string, string, string], rationale: string];
type Lab = { scenario: string; guidance: string; choices: [Choice, Choice, Choice, Choice] };
export const leadershipLabs: Record<string, Lab> = {
  criterios: {
    scenario: "Você precisa escolher uma ferramenta em cinco dias. A opção A custa menos e é preferida pelo time, mas sua integração obrigatória ainda não foi demonstrada. A opção B integra corretamente, mas exige treinamento. O orçamento comporta ambas; a entrega depende da integração.",
    guidance: "Separe viabilidade de preferência. Uma pontuação alta em conforto ou preço não compensa um requisito obrigatório não atendido. Trate a integração desconhecida como informação pendente, não como aprovação ou reprovação definitiva; estabeleça um prazo curto para verificá-la.",
    choices: [
      ["Qual informação deve receber prioridade antes da comparação final?", "Uma demonstração da integração de A, com critério de aceite e prazo.", ["Uma votação sobre a preferência do time.", "Uma estimativa mais precisa do desconto de A.", "Uma nova apresentação das funções extras de B."], "A integração pode tornar A inviável. Preferência e desconto não resolvem essa incerteza decisiva."],
      ["A integração de A falha no teste; seu preço é 20% menor. Qual escolha respeita o problema?", "Avaliar B e o treinamento necessário dentro do orçamento disponível.", ["Escolher A e redistribuir a integração manualmente sem avaliar o impacto.", "Reduzir o peso da integração na pontuação para aproveitar o desconto.", "Pedir nova votação, agora informando o preço."], "O requisito obrigatório delimita opções viáveis; treinamento é um custo administrável já comportado pelo orçamento."],
      ["B foi escolhida. Qual acompanhamento verifica se a decisão resolveu o problema?", "Confirmar a integração em produção e observar erros e tempo de execução.", ["Contar quantas pessoas gostaram da apresentação.", "Comparar apenas o desconto obtido com o fornecedor.", "Encerrar a análise assim que o contrato for assinado."], "O resultado esperado está na execução e na integração, não apenas na compra."],
      ["Em outra compra, ambas as opções atendem aos requisitos. Como tratar a preferência?", "Compará-la com custo e esforço usando critérios definidos antes da escolha.", ["Transformá-la automaticamente em requisito obrigatório.", "Desconsiderá-la sempre, porque é subjetiva.", "Escolher a opção preferida e ajustar os critérios depois."], "Preferências são legítimas entre opções viáveis, desde que a comparação seja consistente e anterior à escolha."],
    ],
  },
  reversibilidade: {
    scenario: "Um processo novo pode reduzir uma hora de trabalho por dia. Testá-lo com um time é reversível, mas a implantação completa exige um contrato anual. Você tem duas semanas para recomendar uma decisão; erros no atendimento não podem aumentar.",
    guidance: "Avalie separadamente a reversibilidade do piloto e a do compromisso final. O teste precisa produzir evidência sobre benefício e segurança, ter condições de interrupção e preservar uma forma de voltar ao processo anterior. Duas semanas de observação não eliminam todas as incertezas de um contrato anual.",
    choices: [
      ["Qual desenho permite aprender sem assumir já o compromisso anual?", "Um piloto restrito, sem contrato anual, com linha de base, limite de erros e revisão.", ["Um piloto com todos os times para obter mais dados rapidamente.", "Assinar o contrato com a expectativa de desfazer se necessário.", "Testar apenas com quem já domina o processo, sem medir erros."], "Escopo, referência e limite de risco tornam o teste útil sem confundir teste reversível com compromisso duradouro."],
      ["O tempo cai, mas erros ultrapassam o limite combinado. O que fazer?", "Interromper conforme o acordo, entender os erros e decidir sobre novo teste.", ["Estender o piloto automaticamente porque o ganho de tempo é evidente.", "Excluir os primeiros dias da análise para manter o limite.", "Manter o teste e comunicar somente a redução de tempo."], "O limite protege uma restrição indispensável e não pode ser renegociado silenciosamente após a falha."],
      ["O teste melhora tempo e qualidade. O que ainda precisa entrar na recomendação?", "Limitações da amostra, custo de retorno e consequências do contrato anual.", ["Somente a média de economia de tempo nas duas semanas.", "Uma declaração de que os riscos foram eliminados.", "A preferência das pessoas que participaram."], "Um piloto bem sucedido sustenta uma recomendação, mas não prova que uma escala maior ou compromisso anual têm os mesmos riscos."],
      ["Um novo teste envolve perda irreversível de dados. Qual ajuste é necessário?", "Reavaliar o risco e garantir proteção e recuperação antes do teste.", ["Manter o piloto porque seu prazo é curto.", "Aceitar o risco porque poucas pessoas participarão.", "Tratar a perda como custo de aprendizagem sem consultar os responsáveis."], "Escopo pequeno não torna uma consequência irreversível aceitável."],
    ],
  },
  revisao: {
    scenario: "Você mudou a escala para reduzir o prazo de atendimento. O prazo melhorou, mas o retrabalho aumentou e um turno ficou sobrecarregado. A revisão já estava marcada para sexta; a proposta original foi sua.",
    guidance: "Examine o resultado de forma completa e diferencie a justificativa original dos efeitos observados. Uma revisão útil registra o que se mantém, o que muda, quem executará o ajuste e quando a qualidade e a distribuição serão reavaliadas.",
    choices: [
      ["Qual comparação sustenta a revisão da escala?", "Prazo, retrabalho e distribuição de carga antes e depois, considerando mudanças de demanda.", ["Somente o prazo, pois era o objetivo inicialmente divulgado.", "A opinião do turno que mais gostou da mudança.", "A quantidade de pessoas que concordou na reunião inicial."], "O ganho principal precisa ser confrontado com efeitos relevantes e contexto, sem atribuir todo efeito à escala."],
      ["A sobrecarga se concentra no mesmo turno. Qual ajuste é mais bem definido?", "Redistribuir parte da carga, nomear responsável e revisar prazo e qualidade em uma data.", ["Pedir mais colaboração e aguardar reclamações.", "Reverter tudo imediatamente, sem avaliar quais partes funcionaram.", "Manter a escala até que todos se adaptem."], "O ajuste deve atacar a evidência observada sem perder automaticamente o benefício já obtido."],
      ["Como comunicar que sua proposta precisa de ajuste?", "Explicar o ganho, os efeitos não previstos e a decisão de corrigir com critérios.", ["Apresentar o ajuste como se tivesse sido planejado desde o início.", "Atribuir a falha exclusivamente à resistência do time.", "Esperar os indicadores melhorarem antes de informar."], "A revisão transparente torna a decisão explicável e preserva espaço para aprendizagem."],
      ["A demanda dobrou após a mudança. Qual conclusão é justificável?", "É preciso considerar essa mudança antes de atribuir os resultados à escala.", ["A escala causou necessariamente toda a sobrecarga.", "A escala não teve qualquer efeito porque a demanda mudou.", "A comparação deixa de ter utilidade e deve ser abandonada."], "Contexto diferente exige cuidado na comparação; não autoriza afirmar causalidade ou ausência de efeito."],
    ],
  },
  vieses: {
    scenario: "Você investiu três meses em um projeto. Dois clientes elogiam a proposta, seis deixaram de usar o piloto e a necessidade mudou. Continuar exige mais dois meses. A equipe teme que interromper pareça uma admissão de incompetência.",
    guidance: "Tempo gasto é histórico, não benefício futuro. Procure explicar desistências e necessidades atuais antes de escolher continuar. Ouça avaliações independentes, registre evidência contrária e avalie o próximo investimento pelas alternativas disponíveis.",
    choices: [
      ["Qual investigação pode realmente contrariar sua hipótese?", "Ouvir quem abandonou o piloto e confrontar os motivos com a necessidade atual.", ["Pedir depoimentos mais detalhados aos dois clientes satisfeitos.", "Reunir a equipe para reafirmar o valor dos três meses investidos.", "Comparar a proposta apenas com versões anteriores do próprio projeto."], "O conjunto favorável já é conhecido; as desistências e a mudança de necessidade podem alterar a decisão."],
      ["Qual argumento sustenta continuar?", "O benefício futuro estimado supera o custo adicional e as alternativas avaliadas.", ["Interromper faria os três meses parecerem desperdiçados.", "A equipe precisa provar que a escolha inicial estava certa.", "Os clientes satisfeitos representam a maioria das conversas positivas."], "A decisão atual considera valor futuro e alternativas, sem usar custo passado como justificativa suficiente."],
      ["Como reduzir concordância automática na reunião?", "Pedir análises individuais antes de anunciar sua recomendação.", ["Apresentar sua recomendação com mais convicção.", "Convidar primeiro somente quem participou desde o começo.", "Solicitar que cada pessoa escolha entre apoiar o projeto ou não."], "Contribuições antes da posição de autoridade têm mais chance de trazer contrapontos independentes."],
      ["A análise conclui que adaptar é melhor. O que preservar?", "Aprendizados e evidências úteis, explicando por que a próxima escolha mudou.", ["Todo o escopo anterior para justificar o investimento.", "Somente os elogios, para proteger a equipe.", "O compromisso original, mesmo se a necessidade mudou."], "Aprender com o investimento não exige continuá-lo nas mesmas condições."],
    ],
  },
  "decisao-coletiva": {
    scenario: "Você decide a escala dentro de regras da empresa. A equipe prefere, por maioria, um turno que deixa uma janela obrigatória sem cobertura. Duas pessoas alertaram sobre isso, mas a consulta foi apresentada como participação na decisão.",
    guidance: "Consulta não é aprovação automática por maioria. Torne claros autoridade, critérios e restrições antes de pedir contribuições. Explique como as sugestões foram usadas e trate os riscos identificados antes de fechar o acordo.",
    choices: [
      ["Qual informação faltou ao iniciar a consulta?", "Quem decide e quais limites de cobertura a decisão precisa respeitar.", ["O número mínimo de votos para cada proposta.", "A preferência pessoal da liderança.", "O formato de divulgação da escala já escolhida."], "Sem papéis e limites, participação pode ser confundida com promessa de adoção da preferência vencedora."],
      ["Como lidar com a proposta majoritária?", "Explicar a restrição e pedir alternativas que preservem a cobertura.", ["Aprovar por maioria e compensar a lacuna quando surgir.", "Cancelar a consulta e escolher sozinho sem devolutiva.", "Pedir que as duas pessoas retirem a objeção para alcançar consenso."], "O requisito precisa ser atendido; a contribuição pode continuar dentro de opções viáveis."],
      ["Qual devolutiva torna a escolha transparente?", "Mostrar critérios, sugestões incorporadas, limites e razões das sugestões não adotadas.", ["Anunciar apenas que a votação foi consultiva.", "Dizer que a decisão final é responsabilidade exclusiva da liderança.", "Publicar todos os votos com o nome de cada pessoa."], "A devolutiva explica como a participação influenciou a decisão sem expor pessoas desnecessariamente."],
      ["Um próximo tema pode ser decidido pelo time. O que delegar junto?", "Limites, prazo, responsáveis e forma de comunicar o resultado.", ["Liberdade sem esclarecer consequências ou restrições.", "Uma opção já escolhida para que o time a ratifique.", "A votação, mantendo em segredo o veto da liderança."], "Decisão coletiva com autonomia precisa ter fronteiras explícitas e compromisso real com o papel delegado."],
    ],
  },
  escuta: {
    scenario: "Uma pessoa diz que recebe prioridades conflitantes de dois gestores. Você acredita que ela evita responsabilidades, mas ainda não viu os pedidos. A entrega está atrasada e a conversa tem quinze minutos.",
    guidance: "Comece pelo relato e por exemplos concretos. Confirme o entendimento e diferencie ouvir da aceitação de qualquer conclusão. A escuta precisa produzir uma hipótese verificável e um próximo passo sobre a entrega, sem transformar uma impressão em diagnóstico.",
    choices: [
      ["Qual abertura permite entender o conflito de prioridades?", "Que pedidos você recebeu, de quem e em que ordem? Vamos comparar os prazos.", ["Por que você não se organizou antes do prazo?", "Você concorda que o problema foi sua falta de foco?", "Qual gestor você prefere seguir daqui para a frente?"], "Pedidos, origem e prazo tornam verificável a hipótese de conflito sem acusação ou escolha pessoal de autoridade."],
      ["A pessoa relata três pedidos. Qual resposta confirma entendimento?", "Entendi que dois pedidos disputam o mesmo horário; qual parte ainda compreendi errado?", ["Então você não consegue atender demandas simultâneas.", "Concordo que os gestores foram injustos.", "Vou resolver sem precisar dos detalhes restantes."], "O resumo confirma o contexto sem rotular competência ou validar conclusões que ainda não foram verificadas."],
      ["Ainda há dúvida sobre o prazo combinado. Como avançar hoje?", "Verificar o registro do prazo e combinar uma entrega provisória possível.", ["Aceitar a versão apresentada como definitiva.", "Aplicar uma orientação baseada na sua impressão inicial.", "Adiar toda a conversa até reunir todos os gestores."], "É possível tratar a urgência mantendo a informação pendente explícita e verificável."],
      ["Os registros confirmam prioridades conflitantes. Qual ação trata a origem?", "Alinhar um critério de prioridade entre os gestores e comunicar o acordo à pessoa.", ["Orientar a pessoa a escolher sempre o pedido mais recente.", "Recomendar que ela evite aceitar demandas novas.", "Encerrar o tema porque a explicação foi confirmada."], "Escutar permite identificar uma causa organizacional que exige acordo entre quem define prioridades."],
    ],
  },
  feedback: {
    scenario: "Em dois repasses, o relatório chegou sem a checagem acordada. O time seguinte refez a conferência e atrasou a entrega. A pessoa tem bom desempenho em outros temas e diz que o modelo usado era ambíguo.",
    guidance: "Feedback descreve comportamento, contexto e impacto, ouvindo explicações sem apagar o acordo. Verifique se o padrão era claro e combine uma mudança observável. Acompanhe o próximo repasse usando o critério, evitando julgamentos gerais sobre a pessoa.",
    choices: [
      ["Qual formulação mantém o foco no comportamento?", "Nos dois repasses faltou a checagem combinada; a equipe refez a conferência e atrasou.", ["Sua postura está prejudicando a confiança do time.", "Você precisa ser mais responsável com os colegas.", "Apesar de normalmente ir bem, você sempre falha nessa etapa."], "Situação, comportamento e impacto permitem investigar o trabalho sem transformar um episódio em traço pessoal."],
      ["A pessoa aponta ambiguidade no modelo. Como responder?", "Comparar o modelo com o acordo e esclarecer juntos a checagem necessária.", ["Suspender todo o feedback até o modelo ser refeito.", "Reafirmar que profissionais experientes não precisam de orientação.", "Aceitar a ambiguidade como justificativa para retirar o acordo."], "A explicação pode revelar uma melhoria no processo, mantendo a responsabilidade por uma checagem agora clara."],
      ["Qual acordo é observável no próximo repasse?", "Usar a lista de checagem validada e sinalizar exceções antes de enviar.", ["Demonstrar mais comprometimento.", "Manter atenção para não decepcionar novamente.", "Pedir que a equipe seguinte confira com mais cuidado."], "Ação e momento explícitos tornam o comportamento verificável e evitam transferir o retrabalho."],
      ["O repasse seguinte atende ao acordo. Como reconhecer?", "Apontar a checagem completa e a redução do retrabalho nesse repasse.", ["Concluir que a pessoa nunca mais precisará de acompanhamento.", "Compará-la publicamente com quem ainda está errando.", "Elogiar sua personalidade em vez da contribuição observada."], "Reconhecimento específico reforça o comportamento, sem extrapolar uma entrega para um julgamento permanente."],
    ],
  },
  acordos: {
    scenario: "Dois colegas discordam sobre urgência: um espera resposta em minutos; o outro reúne perguntas no fim do dia. Ambos entregam bem, mas demandas realmente urgentes se misturam a assuntos rotineiros.",
    guidance: "Preferências de comunicação precisam ser convertidas em acordos de trabalho por tipo de demanda. Defina urgência, canal, prazo e exceções; confira entendimento por exemplos e revise o acordo após testar na rotina.",
    choices: [
      ["Qual diferença precisa ser esclarecida primeiro?", "O que cada pessoa considera urgente e qual impacto exige resposta imediata.", ["Quem tem o estilo de comunicação mais adequado.", "Qual preferência tem apoio da maioria.", "Quem começou a reclamar primeiro."], "A divergência envolve critérios e impacto; classificar estilos não define como o trabalho será coordenado."],
      ["Qual acordo atende às duas necessidades?", "Separar rotina e urgência, com canais, prazos e critérios comuns.", ["Responder todas as mensagens imediatamente.", "Concentrar qualquer demanda no fim do dia.", "Deixar cada pessoa escolher o canal conforme sua preferência."], "O acordo diferencia necessidades de execução e evita exigir um único estilo para todos os casos."],
      ["Como verificar se o acordo foi entendido?", "Apresentar exemplos de demandas e pedir que ambos indiquem canal e prazo.", ["Perguntar se todos concordam e encerrar.", "Enviar uma mensagem longa com todas as preferências.", "Contar o número de confirmações no aplicativo."], "Aplicar o acordo a exemplos testa entendimento além de concordância formal."],
      ["Após uma semana, assuntos rotineiros continuam marcados urgentes. O que revisar?", "Exemplos do uso e critérios de urgência, ajustando o acordo e sua revisão.", ["A capacidade de comunicação de quem marcou as mensagens.", "A preferência da pessoa com mais tempo de empresa.", "O canal inteiro, proibindo todas as mensagens."], "O problema observado está na classificação; o ajuste precisa tratar essa regra com exemplos."],
    ],
  },
  "conversa-dificil": {
    scenario: "Você e uma pessoa discordam sobre o motivo de uma entrega refeita. Há versões diferentes sobre uma mudança de escopo. A conversa se torna tensa, e você não controla a aprovação solicitada pela pessoa.",
    guidance: "Prepare fato, impacto e objetivo; investigue o que está pendente antes de concluir. Uma pausa com retomada protege o diálogo, sem abandonar o acordo. Prometa somente o encaminhamento que controla e explicite dependências.",
    choices: [
      ["Qual objetivo torna a conversa útil?", "Esclarecer a mudança de escopo e combinar como aprovar novas alterações.", ["Demonstrar qual versão é mais convincente.", "Obter concordância com a posição inicial da liderança.", "Evitar futuras conversas sobre o episódio."], "O objetivo precisa resolver o trabalho e o próximo acordo, mantendo fatos pendentes em investigação."],
      ["A tensão impede escuta. Como pausar?", "Marcar retomada, listar o fato a verificar e manter o tema a concluir.", ["Encerrar para preservar a relação, sem prazo.", "Continuar até que uma versão prevaleça.", "Trocar o assunto por um elogio para aliviar a tensão."], "Pausa responsável mantém o compromisso com o assunto e define o que acontecerá antes da retomada."],
      ["O pedido depende de outro setor. Qual compromisso é responsável?", "Encaminhar o pedido, explicar a dependência e combinar retorno sobre o andamento.", ["Garantir aprovação para destravar a conversa.", "Recusar imediatamente para evitar expectativa.", "Esperar uma resposta externa sem comunicar um prazo de atualização."], "O compromisso deve recair sobre o encaminhamento controlável, não sobre uma decisão de outra autoridade."],
      ["Os registros não confirmam nenhuma versão por completo. O que registrar?", "O que foi verificado, o que segue incerto e o novo acordo de aprovação.", ["A versão da liderança como referência final.", "Uma culpa compartilhada para encerrar.", "Somente que houve consenso, sem mencionar pendências."], "É possível estabelecer um acordo melhor sem fabricar certeza sobre o passado."],
    ],
  },
  reunioes: {
    scenario: "Sua reunião semanal consome uma hora em atualizações. As decisões ficam para o fim, duas vozes dominam e os responsáveis saem com entendimentos diferentes. Parte das informações poderia ser lida antes.",
    guidance: "Defina o resultado de cada pauta e separe informação de discussão. Facilite contribuições independentes e reserve tempo para confirmar decisões, responsáveis e revisão. A utilidade do encontro aparece nos encaminhamentos, não apenas na satisfação.",
    choices: [
      ["Qual mudança libera tempo para decidir?", "Enviar atualizações antes e pautar as decisões com critérios e preparação.", ["Aumentar a reunião para acomodar todas as atualizações.", "Reduzir o tempo de fala de todos por igual, sem alterar a pauta.", "Excluir da reunião pessoas que costumam ficar em silêncio."], "Preparação e separação dos tipos de pauta protegem o tempo das decisões relevantes."],
      ["Como ampliar perspectivas na decisão?", "Solicitar registros individuais e uma rodada curta antes do debate.", ["Pedir que as duas pessoas mais ativas falem por último sem preparar as demais.", "Abrir votação imediata sobre a proposta mais defendida.", "Solicitar participação espontânea novamente."], "Contribuições individuais e uma rodada estruturada permitem ouvir informação que o debate espontâneo não trouxe."],
      ["Qual fechamento reduz interpretações diferentes?", "Confirmar escolha, pendências, responsável, próximo passo e data de acompanhamento.", ["Enviar depois uma ata com todas as falas.", "Perguntar se alguém discorda e terminar.", "Delegar a cada participante a interpretação do que fará."], "Encaminhamentos precisam ser confirmados com quem executará, não apenas registrados em volume."],
      ["Como avaliar se o novo formato funciona?", "Verificar clareza e cumprimento dos encaminhamentos e ajustar o encontro.", ["Contar somente quantas pessoas falaram.", "Medir apenas a duração reduzida.", "Usar satisfação alta como prova de decisões melhores."], "Participação e duração são sinais auxiliares; o propósito é produzir clareza e ação."],
    ],
  },
  resultado: {
    scenario: "Você delegou uma apresentação para um cliente. A pessoa domina o tema, mas não sabe qual decisão a apresentação precisa apoiar. Você espera validar dados, não aprovar cada slide. Existe um limite de confidencialidade.",
    guidance: "Uma delegação clara especifica resultado, critério de aceite, limites, autonomia e acompanhamento. Experiência técnica não substitui contexto. Combine pontos de revisão proporcionais ao risco sem controlar todas as escolhas de execução.",
    choices: [
      ["Qual informação é central antes de iniciar?", "A decisão do cliente a apoiar, dados necessários e limites de confidencialidade.", ["A sequência exata de cada slide.", "A preferência de cores da liderança.", "Uma lista de tarefas sem o propósito da apresentação."], "O resultado e as restrições orientam escolhas autônomas; detalhar a forma não resolve a falta de contexto."],
      ["Qual autonomia pode ser explicitada?", "Escolher estrutura e exemplos dentro dos limites, consultando sobre dados sensíveis.", ["Enviar ao cliente qualquer informação que torne a apresentação convincente.", "Solicitar aprovação de cada alteração de texto.", "Descobrir limites durante o contato com o cliente."], "Autonomia precisa distinguir decisões próprias e pontos que exigem consulta por risco."],
      ["Qual revisão é proporcional ao risco?", "Conferir a consistência dos dados e o respeito à confidencialidade antes do envio.", ["Controlar diariamente o tempo em cada slide.", "Reescrever a apresentação inteira para preservar seu estilo.", "Aguardar o retorno do cliente para verificar os dados."], "O acompanhamento verifica critérios críticos sem assumir a execução ou deixar risco grave para depois."],
      ["A entrega atende ao objetivo com outro formato. Como avaliar?", "Pelos critérios de resultado e limites acordados.", ["Pela semelhança com a apresentação que você faria.", "Pela quantidade de horas dedicadas.", "Pelo uso de todas as sugestões da liderança."], "Delegar resultado admite caminhos diferentes quando os critérios e restrições foram atendidos."],
    ],
  },
  acompanhamento: {
    scenario: "Uma pessoa experiente recebe uma entrega de risco moderado. Você revisa tudo diariamente, e ela espera sua aprovação para agir. Uma dependência externa pode atrasar o trabalho; você precisa saber cedo sem assumir a tarefa.",
    guidance: "Acompanhe resultado, risco e bloqueios na cadência adequada à entrega. Explicite quando agir sem consulta e quando sinalizar. Se o acompanhamento está substituindo a autonomia, ajuste os pontos de contato e observe a qualidade das decisões.",
    choices: [
      ["Qual sinal indica que o acompanhamento está excessivo?", "A pessoa espera sua aprovação mesmo em escolhas já delegadas.", ["A pessoa usa um método diferente do seu.", "A pessoa faz perguntas sobre uma dependência nova.", "A pessoa apresenta uma alternativa ao plano inicial."], "Dependência recorrente de aprovação em decisões delegadas revela perda de autonomia, não os métodos diferentes."],
      ["Qual acordo combina visibilidade e autonomia?", "Revisões por marco, sinalização imediata de bloqueios e limites de decisão claros.", ["Suspender qualquer acompanhamento para demonstrar confiança.", "Exigir aprovação diária somente por mensagem.", "Receber atualizações sem combinar o que exige intervenção."], "Marcos e gatilhos de risco evitam controle contínuo e também abandono."],
      ["A dependência atrasou. Qual intervenção preserva responsabilidade?", "Remover o bloqueio entre áreas e pedir à pessoa uma proposta de replanejamento.", ["Assumir toda a entrega para ganhar tempo.", "Orientar a pessoa a cobrar informalmente sem prazo.", "Manter o plano porque a dependência não é do time."], "A liderança pode tratar a interface enquanto a pessoa mantém a condução da entrega e do ajuste."],
      ["Quando aumentar temporariamente a frequência das revisões?", "Quando surgir um risco novo relevante, explicando motivo e duração do ajuste.", ["Quando a pessoa adotar um método que você não conhece.", "Sempre que houver um atraso externo, mesmo já resolvido.", "Sempre que você sentir necessidade de ter mais controle."], "A cadência deve acompanhar risco e necessidade de apoio, com limites explícitos."],
    ],
  },
  prioridades: {
    scenario: "O time tem capacidade para duas entregas nesta semana e recebeu quatro solicitações urgentes. Uma impede uma multa contratual, outra depende de aprovação externa, duas geram melhorias internas. Todas têm patrocinadores influentes.",
    guidance: "Compare impacto, prazo, dependências e capacidade real. Urgência declarada não é critério suficiente. Negocie escopo e adiamentos, torne a escolha visível e proteja a capacidade contra entradas que silenciosamente substituem o acordo.",
    choices: [
      ["O que precisa entrar na priorização?", "Impacto, prazo obrigatório, dependência e esforço dentro da capacidade disponível.", ["A posição hierárquica de cada solicitante.", "A ordem de chegada, sem verificar restrições.", "Uma distribuição igual de tempo entre as quatro demandas."], "A comparação trata consequências e viabilidade em vez de autoridade ou equilíbrio aparente."],
      ["Qual encaminhamento respeita a capacidade?", "Garantir a restrição contratual e negociar a segunda entrega e o adiamento das demais.", ["Aceitar as quatro e pedir ao time que encontre uma forma.", "Começar todas para demonstrar resposta aos patrocinadores.", "Eliminar o acompanhamento para liberar tempo."], "Escolher implica dizer o que não cabe e renegociar; iniciar tudo não cria capacidade."],
      ["Uma quinta demanda entra no meio da semana. Como tratá-la?", "Comparar com os critérios e explicitar o que sairia para ela entrar.", ["Incluí-la por ser a mais recente.", "Repassá-la à pessoa com mais experiência sem revisar a carga.", "Assumi-la pessoalmente para manter todas as promessas."], "Novas entradas precisam ser confrontadas com escolhas e capacidade já comprometidas."],
      ["Qual sinal pede revisão da prioridade escolhida?", "Uma mudança verificada na consequência, no prazo ou na dependência crítica.", ["Uma nova cobrança sem informação sobre impacto.", "A preferência de quem fala mais na reunião.", "O desconforto de comunicar um adiamento."], "Repriorizar requer informação que altere os critérios, não apenas pressão renovada."],
    ],
  },
  autonomia: {
    scenario: "Uma pessoa pode negociar ajustes operacionais, mas mudanças de preço precisam de aprovação. Um cliente pede alteração de escopo com redução de preço. O prazo é curto, e a pessoa quer atender sem perder autonomia.",
    guidance: "Direitos de decisão dependem do impacto e dos limites, não só do título do cargo. A pessoa deve poder preparar alternativas e encaminhar a exceção, sem prometer uma decisão que ultrapassa sua autoridade.",
    choices: [
      ["Qual parte exige consulta neste caso?", "A alteração de preço, enquanto a pessoa pode preparar opções operacionais.", ["Qualquer contato com o cliente.", "Somente a redução do prazo de resposta.", "Nenhuma parte, porque negociar já foi delegado."], "O limite específico de preço prevalece, sem cancelar toda a autonomia operacional."],
      ["Qual resposta ao cliente preserva confiança?", "Apresentar possibilidades de escopo e explicar que o preço depende de aprovação.", ["Confirmar o desconto para depois pedir autorização.", "Recusar qualquer conversa até a liderança responder.", "Omitir o limite de aprovação para parecer mais ágil."], "É possível avançar na preparação mantendo a dependência transparente."],
      ["Exceções semelhantes chegam toda semana. O que revisar?", "Os limites de decisão, o risco e o fluxo de aprovação com dados das exceções.", ["Pedir que a pessoa pare de encaminhar exceções.", "Autorizar qualquer desconto para eliminar consultas.", "Manter os limites porque já foram explicados uma vez."], "Padrões de exceção são evidência para redesenhar fronteiras e não justificam autonomia ilimitada."],
      ["A pessoa age dentro dos limites com uma alternativa diferente. Qual reação é coerente?", "Avaliar pelo resultado e oferecer feedback sem exigir aprovação retroativa.", ["Retirar a autonomia porque a alternativa não era sua preferida.", "Requerer consulta prévia em todas as decisões seguintes.", "Ignorar o resultado porque houve autonomia."], "Autonomia real admite escolhas diferentes dentro dos limites e mantém responsabilidade pelo resultado."],
    ],
  },
  distribuicao: {
    scenario: "Uma pessoa experiente recebe sempre as entregas complexas e está sobrecarregada. Uma colega quer desenvolver a competência, mas ainda precisa de apoio. A nova entrega tem parte crítica e parte adequada para aprendizagem.",
    guidance: "Distribua trabalho por capacidade, risco e oportunidade de desenvolvimento. Igualdade de quantidade não garante equilíbrio de esforço. Divida a oportunidade com apoio e critérios, sem transformar a pessoa experiente em uma segunda responsável por tudo.",
    choices: [
      ["Qual análise evita repetir a sobrecarga?", "Esforço atual, criticidade das partes e apoio necessário para desenvolver a colega.", ["Número bruto de tarefas de cada pessoa.", "Histórico de quem sempre entregou mais rápido.", "Preferências do cliente sobre a pessoa executora."], "Equilíbrio exige considerar esforço e risco, além de oportunidades e apoio disponível."],
      ["Qual distribuição concilia entrega e desenvolvimento?", "Delegar a parte adequada à colega, com revisão crítica e tempo de apoio reservado.", ["Entregar tudo à pessoa experiente e prometer desenvolvimento futuro.", "Delegar tudo à colega sem acompanhamento para acelerar aprendizagem.", "Distribuir metade das tarefas para cada uma sem avaliar complexidade."], "Uma oportunidade delimitada com apoio protege a entrega e cria prática real."],
      ["Como evitar que o apoio vire sobrecarga invisível?", "Reservar tempo, definir o papel de apoio e revisar a capacidade total da pessoa experiente.", ["Tratar a mentoria como algo feito quando sobrar tempo.", "Manter todas as entregas antigas da pessoa experiente.", "Pedir que a colega revise sozinha qualquer risco."], "Apoio também consome capacidade e precisa ser planejado como trabalho."],
      ["Qual evidência orienta a próxima delegação?", "Critérios atendidos, decisões feitas e nível de apoio ainda necessário.", ["A ausência de perguntas durante a tarefa.", "A satisfação da liderança com o esforço percebido.", "A comparação pública entre as duas pessoas."], "Desenvolvimento aparece em decisões e entregas observáveis, não em silêncio ou rankings pessoais."],
    ],
  },
  individuais: {
    scenario: "Uma conversa individual foi ocupada por status de tarefas. A pessoa sinaliza dificuldade para discordar nas reuniões, mas o tempo acabou. Você não tem evidências suficientes para concluir que o time está sem confiança.",
    guidance: "Conversa individual reserva espaço para prioridades, obstáculos, aprendizagem e perspectiva da pessoa. Investigue exemplos sem generalizar relatos para o time. Faça um encaminhamento possível e marque uma retomada para conferir o efeito.",
    choices: [
      ["Qual pergunta aprofunda o relato sem induzir uma conclusão?", "Em que reunião isso ocorreu e o que dificultou apresentar sua discordância?", ["Você concorda que nosso time não permite críticas?", "Quem precisa mudar de comportamento para você falar?", "Por que você não foi mais assertivo?"], "O exemplo permite entender contexto e barreiras sem impor interpretação ou culpa."],
      ["O tempo acabou. Qual acordo mantém o tema vivo?", "Agendar retomada próxima e separar atualizações rotineiras do próximo encontro.", ["Pedir que a pessoa escreva qualquer novidade quando quiser.", "Prometer resolver o clima do time na semana seguinte.", "Concluir que a pessoa deveria ter trazido o tema antes."], "A retomada explícita demonstra compromisso sem prometer uma conclusão ainda sem evidências."],
      ["A pessoa quer testar uma contribuição escrita antes da reunião. Como apoiar?", "Combinar o teste, criar espaço para a contribuição e revisar a experiência depois.", ["Apresentar você mesmo a opinião dela, sem combinar.", "Anunciar ao time que ela tem dificuldade para discordar.", "Exigir que fale espontaneamente para desenvolver confiança."], "O apoio deve ser consentido, prático e acompanhado, preservando a pessoa."],
      ["O que pode ser concluído a partir desse relato?", "Há uma dificuldade individual a investigar; ainda não há medida do clima do time.", ["Toda a equipe tem receio de discordar.", "A pessoa não possui competência de comunicação.", "A contribuição escrita solucionará definitivamente o problema."], "Um relato abre investigação, mas não sustenta diagnóstico coletivo ou promessa de solução."],
    ],
  },
  aprendizagem: {
    scenario: "Uma pessoa quer melhorar a condução de reuniões. Ela assistiu a vários conteúdos, mas nunca facilitou um encontro. A próxima reunião tem uma pauta simples; a seguinte envolve uma decisão crítica.",
    guidance: "Aprender exige prática delimitada, apoio e evidência de progresso. Escolha uma primeira oportunidade proporcional ao risco e um critério observável. Conteúdo ajuda a preparar, mas consumo de aulas não prova aplicação.",
    choices: [
      ["Qual oportunidade é mais adequada para começar?", "Facilitar a pauta simples, com preparação, observação e feedback combinado.", ["Assumir a reunião crítica para aprender sob pressão.", "Assistir a mais conteúdos até sentir confiança total.", "Observar reuniões indefinidamente sem conduzir nenhuma parte."], "Uma prática com risco delimitado produz evidência e permite feedback sem expor desnecessariamente a entrega."],
      ["Qual critério mostra aplicação da habilidade?", "Encerrar a pauta com decisão, responsável e próximo passo confirmados.", ["Ler todos os conteúdos disponíveis.", "Falar durante a maior parte do encontro.", "Receber elogios gerais pela postura."], "O critério verifica o resultado da facilitação, não consumo ou impressão."],
      ["A pessoa facilita bem, mas não confirma responsáveis. Qual feedback orienta progresso?", "Descrever essa lacuna e combinar um fechamento estruturado na próxima prática.", ["Classificar a pessoa como ainda despreparada.", "Considerar a habilidade concluída porque houve boa participação.", "Recomendar uma nova trilha inteira sem tratar a lacuna."], "Feedback específico conecta evidência, próximo teste e critério."],
      ["Quando ampliar a complexidade da prática?", "Ao observar o critério atendido e ajustar o apoio ao novo risco.", ["Assim que a pessoa concluir mais uma aula.", "Depois de um prazo fixo independente dos resultados.", "Apenas quando não precisar de ajuda em nenhum tema."], "A progressão acompanha evidência e risco, sem exigir perfeição ou usar só presença em aulas."],
    ],
  },
  reconhecimento: {
    scenario: "Uma entrega foi concluída por esforço de várias pessoas. A apresentação destacou quem falou com o cliente, mas a checagem de dados e a remoção de um bloqueio ocorreram nos bastidores. Há preferências diferentes sobre reconhecimento público.",
    guidance: "Reconheça contribuições verificáveis e seu impacto, incluindo trabalho menos visível. Verifique a preferência sobre exposição e não use reconhecimento para compensar sobrecarga ou prometer oportunidades ainda não decididas.",
    choices: [
      ["O que investigar antes de reconhecer a entrega?", "Quais contribuições sustentaram o resultado, incluindo apoio e checagem.", ["Quem teve mais contato com o cliente.", "Quem apresentou melhor o resultado.", "Quem trabalhou o maior número de horas."], "Visibilidade não representa sozinha a contribuição; a apuração precisa incluir trabalho que tornou a entrega possível."],
      ["Qual reconhecimento é específico?", "Sua checagem identificou a divergência antes do envio e evitou retrabalho.", ["Você é a pessoa mais dedicada do time.", "Você sempre salva nossas entregas.", "Seu esforço prova que merece promoção imediata."], "Comportamento e impacto observáveis tornam o reconhecimento útil sem comparação ou promessa."],
      ["Uma pessoa prefere retorno reservado. Como proceder?", "Reconhecer em particular e combinar como citar a contribuição no relato coletivo.", ["Fazer um elogio público porque exposição é sempre positiva.", "Omitir completamente a contribuição dela.", "Pedir que justifique ao time por que não gosta de exposição."], "Preferência por privacidade não exige apagar contribuição nem impor exposição."],
      ["A entrega exigiu sobrecarga recorrente. Qual complemento é necessário?", "Reconhecer a contribuição e tratar capacidade e prioridades para evitar repetição.", ["Usar elogios para manter o esforço adicional.", "Transformar as horas extras em padrão esperado.", "Adiar qualquer ajuste porque o time foi reconhecido."], "Reconhecimento não substitui decisões sobre condições de trabalho e capacidade."],
    ],
  },
  "plano-desenvolvimento": {
    scenario: "O objetivo registrado é melhorar comunicação. A pessoa quer tornar claros os repasses entre áreas. Vocês têm duas semanas, uma oportunidade real de repasse e tempo limitado para acompanhamento.",
    guidance: "Traduza competência ampla em comportamento observável: preparar repasse, confirmar entendimento e acompanhar exceções. Defina prática, apoio, evidência e data de revisão. Um plano é uma hipótese de aprendizagem, não garantia de mudança.",
    choices: [
      ["Qual objetivo é verificável?", "No próximo repasse, confirmar responsável, critério de aceite e dúvidas da outra área.", ["Melhorar a comunicação em duas semanas.", "Demonstrar mais segurança nas conversas.", "Evitar qualquer conflito entre as áreas."], "Comportamento e situação definidos permitem observar o que mudou."],
      ["Qual plano cabe nas condições disponíveis?", "Preparar e conduzir um repasse, com revisão breve antes e retorno depois.", ["Concluir três cursos e aguardar uma oportunidade futura.", "Mudar todos os processos entre áreas em duas semanas.", "Solicitar feedback informal sem combinar o comportamento observado."], "O plano associa estudo e oportunidade real, com apoio proporcional ao tempo disponível."],
      ["Qual evidência deve entrar na revisão?", "Se o destinatário compreendeu os critérios e quais dúvidas ou retrabalhos surgiram.", ["Somente a quantidade de material lido.", "A impressão geral de que a pessoa parece mais confiante.", "A ausência de reclamações, sem consultar a outra área."], "O resultado da aplicação precisa ser observado no trabalho e com quem recebe o repasse."],
      ["A prática não ocorreu porque a oportunidade foi adiada. Como revisar?", "Reagendar uma oportunidade possível e ajustar o plano sem inventar evidência.", ["Registrar a habilidade como concluída pelo esforço de preparação.", "Classificar a pessoa como sem progresso.", "Manter a mesma data e retirar a etapa prática."], "Ausência de oportunidade é diferente de falha na aplicação; o plano deve ser ajustado ao contexto real."],
    ],
  },
  mentoria: {
    scenario: "Uma colega experiente apoia quem aprende a negociar prioridades. A pessoa pede uma solução pronta para uma demanda; há tempo para discutir e a decisão permanece com ela. O apoio não pode sobrecarregar a mentora.",
    guidance: "Mentoria ajuda a elaborar critérios e alternativas, preservando autoria da decisão. Combine objetivo, tempo e fronteiras do apoio. Experiências da mentora são referências a adaptar, não respostas universais.",
    choices: [
      ["Qual pergunta desenvolve a decisão da pessoa?", "Quais critérios, limites de capacidade e alternativas você vê nesta demanda?", ["Você quer que eu responda por você?", "Por que não faz como eu sempre fiz?", "Qual resposta evitaria discordância com o solicitante?"], "Critérios e alternativas permitem elaborar o raciocínio que a pessoa precisará aplicar novamente."],
      ["Como usar um exemplo da mentora?", "Comparar contexto e limites antes de adaptar a experiência à situação atual.", ["Replicar a solução para economizar tempo.", "Adotar o exemplo por vir da pessoa mais experiente.", "Desconsiderar exemplos porque a decisão é individual."], "Experiência é útil quando suas condições e limites são examinados."],
      ["Qual acordo protege a capacidade de quem apoia?", "Definir encontros, objetivo e canal de exceções dentro do tempo reservado.", ["Disponibilizar apoio ilimitado até que a pessoa aprenda.", "Aceitar interrupções permanentes como parte informal do papel.", "Reduzir todas as entregas sem negociar a carga."], "Apoio planejado torna o compromisso sustentável e explícito."],
      ["Qual sinal mostra aprendizagem entre os encontros?", "A pessoa explica critérios, propõe alternativas e revisa sua decisão com evidências.", ["A pessoa consulta a mentora em todas as escolhas.", "A pessoa reproduz exatamente as respostas ouvidas.", "A pessoa deixou de fazer perguntas."], "O progresso está na qualidade do raciocínio e na autonomia, não na imitação ou no silêncio."],
    ],
  },
  "resultado-meta": {
    scenario: "A meta anunciada é realizar dez treinamentos. O problema real é reduzir erros no repasse de pedidos. A realização dos encontros não garante mudança; a equipe precisa de um resultado observável em oito semanas.",
    guidance: "Atividade e resultado são medidas diferentes. Defina qual mudança deve ocorrer, em quem ou no quê, em qual prazo e com qual referência. Capacitação pode ser parte da estratégia, mas o acompanhamento precisa observar a execução e a qualidade.",
    choices: [
      ["Qual objetivo representa o problema?", "Reduzir erros de repasse em relação à referência acordada, sem piorar o prazo.", ["Realizar os dez encontros previstos.", "Aumentar o total de pessoas treinadas.", "Distribuir materiais a todos os participantes."], "Encontros e distribuição são atividades; a mudança esperada está na qualidade do repasse."],
      ["Qual informação é necessária para acompanhar a meta?", "Definição de erro, medida inicial, fonte e frequência de observação.", ["Número de slides preparados.", "Nome de quem concluiu o treinamento primeiro.", "Expectativa de melhoria informada pelo instrutor."], "Sem referência e definição comum, as comparações podem misturar fenômenos diferentes."],
      ["Os encontros ocorreram, mas os erros não caíram. Qual revisão faz sentido?", "Investigar aplicação, obstáculos do processo e apoio necessário antes de ajustar a estratégia.", ["Declarar a meta alcançada pela execução dos encontros.", "Aumentar o número de encontros sem investigar causas.", "Concluir que as pessoas não se esforçaram."], "Entrega de atividades não substitui resultado; a revisão procura os fatores que impediram a mudança."],
      ["Erros caíram, mas o prazo dobrou. Como interpretar?", "Há um ganho de qualidade com efeito adverso que exige revisar o processo.", ["A meta foi integralmente atingida porque um indicador melhorou.", "O treinamento falhou completamente.", "O prazo não importa porque não era a medida principal."], "O resultado deve respeitar limites de qualidade e execução, evitando otimização de uma medida à custa de outra."],
    ],
  },
  indicadores: {
    scenario: "O time aumentou tickets fechados em 30%, mas reaberturas e reclamações subiram. O indicador remunera volume; alguns casos complexos ficam sem resposta. Você precisa avaliar a qualidade sem inventar uma pontuação de engajamento.",
    guidance: "Uma medida isolada pode incentivar escolhas que pioram o resultado. Combine volume com qualidade, examine distribuição e definição e use apenas dados que de fato existem. Não trate correlação ou percepção como prova de causa.",
    choices: [
      ["Qual conjunto é mais útil para investigar?", "Volume, reabertura, prazo e complexidade dos casos com definições consistentes.", ["Somente volume, para preservar comparabilidade.", "Uma nota estimada de motivação do time.", "A opinião dos clientes satisfeitos selecionados."], "Medidas complementares expõem efeito adverso e diferenças de contexto; métricas estimadas não sustentam a análise."],
      ["O que avaliar sobre o incentivo por volume?", "Se ele favorece encerramento precoce ou seleção de casos mais simples.", ["Se a equipe poderia aumentar ainda mais o volume.", "Se os casos complexos podem ser retirados do relatório.", "Se reclamações deveriam ser contadas só após o próximo ciclo."], "O comportamento incentivado pode mudar a medida sem melhorar o resultado."],
      ["Reaberturas subiram após o incentivo. Qual conclusão cabe?", "Há um sinal a investigar; é preciso verificar contexto e decisões de encerramento.", ["O incentivo causou necessariamente cada reabertura.", "O aumento prova queda de engajamento.", "A relação pode ser ignorada porque não há prova definitiva."], "O sinal justifica investigação, mas não permite afirmar causalidade ou inferir engajamento."],
      ["Qual ajuste ajuda a acompanhar melhor?", "Definir qualidade e reabertura junto ao volume, revisando o comportamento incentivado.", ["Trocar o nome do indicador mantendo a regra.", "Criar uma média sem explicar pesos e fontes.", "Retirar resultados ruins para reduzir ruído."], "A medida precisa refletir a entrega desejada e suas consequências, com origem legível."],
    ],
  },
  "cadencia-resultados": {
    scenario: "A meta é revisada somente no fim do mês. Uma dependência já compromete a segunda semana, mas o relatório continua verde porque tarefas começaram. As reuniões gastam tempo em justificativas e não produzem ações.",
    guidance: "Cadência deve permitir agir a tempo. Diferencie início de tarefa de resultado entregue e use sinais precoces ligados ao risco. Encerre cada revisão com decisão, responsável e prazo; acompanhe o acordo antes de pedir novos relatos.",
    choices: [
      ["Qual sinal deveria acionar uma revisão antes do mês fechar?", "Uma dependência crítica sem solução dentro do prazo necessário.", ["A proximidade da data do relatório mensal.", "O número de tarefas marcadas como iniciadas.", "Uma mudança na preferência de formato do relatório."], "O sinal é útil quando permite corrigir um risco antes de ele virar resultado perdido."],
      ["Como representar o andamento com honestidade?", "Mostrar entregas concluídas, risco da dependência e previsão com premissas.", ["Manter verde porque houve esforço e início.", "Apresentar toda tarefa iniciada como percentual de resultado.", "Trocar a meta para o número de reuniões realizadas."], "Status precisa distinguir resultado, atividade e incerteza de previsão."],
      ["Qual saída torna a revisão acionável?", "Uma decisão sobre a dependência com responsável, prazo e próxima checagem.", ["Uma lista maior de justificativas registradas.", "Uma cobrança geral por mais agilidade.", "Uma nova apresentação do planejamento original."], "Revisão gera valor quando orienta uma ação verificável."],
      ["Quando reduzir a frequência das revisões?", "Quando os riscos e a velocidade de mudança permitirem manter capacidade de agir.", ["Sempre que a meta ficar verde.", "Quando as pessoas relatarem cansaço, sem avaliar o risco.", "Somente após o resultado final, mesmo em contexto estável."], "Cadência é proporcional ao risco e à necessidade de decisão, podendo ser ajustada."],
    ],
  },
  dependencias: {
    scenario: "Sua equipe precisa de dados de outra área na terça para entregar na sexta. O responsável externo não confirmou o critério de aceite. Cada área acredita que a outra está atrasando; ambos os times têm outras prioridades.",
    guidance: "Coordene interfaces com entrega, critério, responsável, prazo e canal para bloqueios. Verifique entendimento e capacidade entre áreas; escale conflitos de prioridade com fatos e alternativas, evitando repassar culpa ou prometer o que não controla.",
    choices: [
      ["Qual acordo está faltando na interface?", "O que será entregue, critério de aceite, responsável e prazo necessário.", ["A identificação de quem começou o atraso.", "A preferência de cada equipe sobre comunicação.", "Uma cobrança copiada para todos os gestores."], "A interface precisa ser executável e compreendida pelas duas áreas."],
      ["A outra área não consegue entregar tudo na terça. Qual negociação é útil?", "Comparar um recorte viável de dados e o efeito no escopo ou prazo final.", ["Confirmar sexta ao cliente e insistir por mensagem.", "Aguardar terça para saber se foi possível.", "Solicitar prioridade absoluta sem discutir a carga."], "Alternativas de escopo e consequência permitem negociar dentro da capacidade real."],
      ["O conflito de prioridade persiste. Como escalar?", "Apresentar dependência, impacto, alternativas e a decisão de prioridade necessária.", ["Relatar que a outra área não colabora.", "Copiar o cliente para pressionar.", "Prometer compensar qualquer atraso com trabalho adicional do time."], "Escalar deve ajudar uma autoridade a decidir com fatos, não aumentar confronto."],
      ["Como acompanhar sem assumir o trabalho da outra área?", "Checar os marcos e bloqueios combinados, mantendo claros os responsáveis.", ["Executar a parte externa sem combinar.", "Pedir atualizações a cada hora independentemente do risco.", "Confiar no prazo sem qualquer checagem crítica."], "Coordenação mantém visibilidade e responsabilidade nas interfaces."],
    ],
  },
  retrospectiva: {
    scenario: "Depois de uma entrega, o time registra sempre comunicação ruim. Nenhuma ação é acompanhada. Desta vez houve uma aprovação tardia documentada e um retrabalho evitável; a reunião precisa produzir uma melhoria possível.",
    guidance: "Traga episódios e evidências, explore condições do processo e escolha poucas ações. A retrospectiva não é busca de culpado nem lista infinita. Defina um experimento verificável e retome sua evidência no próximo ciclo.",
    choices: [
      ["Como tornar a análise específica?", "Examinar quando a aprovação atrasou, o que estava pendente e o efeito na entrega.", ["Confirmar novamente que a comunicação foi ruim.", "Votar em quem mais contribuiu para o atraso.", "Comparar o episódio apenas com a melhor entrega do time."], "Episódio e condição verificáveis permitem encontrar um ajuste de processo."],
      ["Qual ação cabe no próximo ciclo?", "Combinar um ponto de aprovação antecipado, com responsável e prazo.", ["Melhorar a comunicação de todas as pessoas.", "Reestruturar todos os processos imediatamente.", "Registrar a sugestão e deixar cada um agir como puder."], "Ação delimitada permite aplicação e avaliação no ciclo seguinte."],
      ["Qual evidência testa a melhoria?", "Se a aprovação ocorreu no marco e quanto retrabalho permaneceu.", ["Se a retrospectiva teve participação alta.", "Se a proposta recebeu aprovação unânime.", "Se o encontro durou menos tempo."], "Evidência de execução e efeito verifica a ação; satisfação com o encontro não faz isso."],
      ["A ação foi aplicada, mas o atraso veio de outra dependência. O que concluir?", "Examinar o efeito no problema original e tratar a nova dependência separadamente.", ["A ação não trouxe valor porque a entrega ainda atrasou.", "A ação resolveu definitivamente a comunicação.", "É necessário abandonar retrospectivas."], "Resultado final depende de múltiplos fatores; o teste precisa avaliar o mecanismo que pretendia melhorar."],
    ],
  },
  confianca: {
    scenario: "Você prometeu responder a um pedido na quarta, mas recebeu uma urgência e não conseguiu. A pessoa precisou agir sem retorno. Você quer preservar confiança sem inventar uma justificativa ou garantir um prazo impossível.",
    guidance: "Confiança se constrói com compromissos claros, cumprimento e renegociação antecipada quando possível. Após uma falha, reconheça o impacto, combine reparação e acompanhe. A explicação de contexto não apaga a responsabilidade pelo acordo.",
    choices: [
      ["Qual resposta assume responsabilidade pelo acordo?", "Reconhecer o prazo perdido e o impacto, explicar o contexto e combinar novo encaminhamento.", ["Explicar a urgência para mostrar que o pedido era menos importante.", "Prometer responder sempre de imediato daqui em diante.", "Aguardar que a pessoa volte a solicitar."], "Responsabilidade inclui reconhecer efeito e reparar, sem promessa exagerada."],
      ["Qual novo compromisso é mais confiável?", "Um retorno em prazo viável, distinguindo informação disponível e decisão pendente.", ["Uma resposta completa ainda hoje sem avaliar dependências.", "Um compromisso genérico de melhorar a atenção.", "Um prazo condicionado apenas a quando sobrar tempo."], "Viabilidade e clareza sobre o que será entregue tornam o compromisso verificável."],
      ["Ao perceber antecipadamente que atrasará de novo, o que fazer?", "Renegociar antes do prazo e discutir o impacto e alternativas.", ["Priorizar silenciosamente e explicar depois.", "Esperar o vencimento para ter certeza do atraso.", "Transferir o pedido a outra pessoa sem avisar."], "Renegociar cedo permite que a pessoa ajuste sua ação com informação."],
      ["Qual evidência de recuperação deve ser observada?", "Cumprimento dos novos acordos e sinalização antecipada de impedimentos.", ["A ausência de novas reclamações.", "A concordância da pessoa com a justificativa.", "Um elogio público à relação entre vocês."], "Confiança não pode ser decretada; comportamentos consistentes são evidências de execução do acordo."],
    ],
  },
  "perguntas-seguras": {
    scenario: "Uma pessoa relata um erro antes do envio. A reunião é tensa e alguém sugere retirar dela a tarefa. O erro é corrigível, mas você ainda não sabe se veio de falta de clareza, atenção ou condição do processo.",
    guidance: "Receba o alerta sem punir a iniciativa de informar; mantenha a investigação e a responsabilidade. Trate primeiro a contenção proporcional ao risco e depois as condições da falha. Espaço para perguntas não significa ausência de critérios.",
    choices: [
      ["Qual resposta permite conter e entender o problema?", "Agradecer o aviso, avaliar o risco e definir correção antes de investigar as condições.", ["Retirar a tarefa imediatamente para dar exemplo.", "Garantir que o erro não terá qualquer consequência antes de entendê-lo.", "Pedir que a pessoa resolva sem envolver o grupo."], "Receber o alerta favorece informação precoce; a resposta continua proporcional ao risco e responsável."],
      ["Qual pergunta investiga as condições?", "Em qual etapa surgiu o erro e quais critérios ou informações estavam disponíveis?", ["Por que você não foi mais cuidadoso?", "Quem deveria ser responsabilizado primeiro?", "Você concorda que não estava preparado?"], "Etapa e condições produzem informação verificável em vez de julgamento antecipado."],
      ["Como acompanhar a prevenção?", "Definir um ajuste de checagem e observar sua execução no próximo envio.", ["Pedir que ninguém volte a errar.", "Exigir aprovação da liderança em toda tarefa sem prazo de revisão.", "Presumir que agradecer o alerta resolveu o processo."], "Prevenção precisa de ação e critério; acolhimento sozinho não elimina o risco."],
      ["Um erro envolve risco grave. O que muda?", "A contenção e análise exigem maior rigor, preservando abertura para alertas.", ["A necessidade de ouvir deixa de existir.", "Qualquer erro deve ser tratado como punição automática.", "A gravidade deve ser minimizada para manter confiança."], "Segurança para relatar e exigência na resposta podem coexistir."],
    ],
  },
  "conflito-fatos": {
    scenario: "Uma pessoa diz que um colega nunca ajuda. O colega apresenta três apoios recentes e relata pedidos fora do combinado. Há uma entrega pendente; você precisa separar fatos, interpretações e necessidades.",
    guidance: "Evite aceitar palavras absolutas como descrição factual. Peça episódios, registros e impacto, reconhecendo necessidades sem validar toda interpretação. Defina o acordo necessário para a entrega atual e o que precisa ser verificado sobre o histórico.",
    choices: [
      ["Qual investigação torna a divergência verificável?", "Comparar pedidos específicos, combinados e respostas nas situações citadas.", ["Perguntar quem considera o colega mais colaborativo.", "Aceitar o relato da pessoa que procurou você primeiro.", "Medir qual versão foi apresentada com mais calma."], "Fatos do trabalho ajudam a distinguir interpretação e evidência."],
      ["Como reconhecer a necessidade sem endossar o rótulo?", "Entendo que você precisa de apoio previsível; vamos verificar pedidos e acordos.", ["Concordo que ele nunca ajuda.", "Você está exagerando e deve aceitar o colega.", "Ambos têm a mesma culpa pelo conflito."], "Reconhecer a necessidade mantém espaço para investigação sem validar generalização."],
      ["Qual acordo trata a entrega atual?", "Definir apoio, limite de capacidade, prazo e forma de sinalizar impedimentos.", ["Pedir aos dois que tenham uma relação melhor.", "Exigir que qualquer pedido seja atendido.", "Evitar novos pedidos entre eles."], "O acordo concreto trata a dependência e não tenta resolver a relação por uma ordem genérica."],
      ["Os pedidos estavam fora do acordo anterior. Como revisar?", "Explicitar a diferença e renegociar necessidades e capacidade para os próximos pedidos.", ["Encerrar dizendo que uma das pessoas estava errada em tudo.", "Ignorar a necessidade porque o pedido foi fora do combinado.", "Ampliar o acordo para toda demanda sem avaliar capacidade."], "Um pedido fora do limite pede clareza e negociação, não invalidação total do relato ou aceitação ilimitada."],
    ],
  },
  "facilitar-acordo": {
    scenario: "Dois colegas disputam um recurso necessário à entrega. Ambos têm motivos válidos, mas o recurso comporta uma frente por vez. Você facilita a conversa; a prioridade estratégica final é sua responsabilidade.",
    guidance: "Diferencie interesses, propostas e restrições. Facilitar não exige consenso a qualquer custo: se a decisão é da liderança, deixe isso explícito e use critérios. O acordo precisa descrever sequência, responsáveis, exceções e revisão.",
    choices: [
      ["Qual abertura organiza a conversa?", "Esclarecer necessidades, limite do recurso e quem decide a prioridade.", ["Pedir que alguém ceda para acabar com o conflito.", "Prometer que ambos terão o recurso ao mesmo tempo.", "Anunciar uma votação sem explicar autoridade."], "Papéis e restrições impedem promessas incompatíveis e permitem comparar as necessidades."],
      ["Uma divisão simultânea prejudicaria ambas as entregas. Qual alternativa analisar?", "Sequência por critério de impacto e prazo, com ajuste de escopo se necessário.", ["Divisão igual para parecer imparcial.", "Escolha de quem defendeu a proposta com mais firmeza.", "Cancelamento das duas frentes para evitar preferência."], "Equidade não é sempre divisão idêntica; a solução deve atender às condições da entrega."],
      ["Qual fechamento torna o acordo executável?", "Registrar sequência, responsáveis, prazo e gatilho para rever a prioridade.", ["Confirmar que todos entenderam a importância de cooperar.", "Pedir que resolvam os detalhes posteriormente.", "Manter o acordo verbal para preservar flexibilidade."], "Clareza sobre execução e revisão permite agir sem reabrir toda a disputa."],
      ["Uma pessoa continua discordando. Como proceder?", "Registrar o argumento, explicar os critérios e confirmar a execução e o canal de revisão.", ["Exigir concordância pessoal para executar.", "Reabrir a decisão até alcançar unanimidade.", "Tratar a discordância como falta de compromisso."], "Execução responsável pode coexistir com discordância tratada e decisão explicada."],
    ],
  },
  inclusao: {
    scenario: "As oportunidades de apresentar projetos vão sempre às mesmas pessoas. Parte do time contribui melhor por escrito; um colega novo ainda não conhece o processo. A próxima apresentação é de risco moderado.",
    guidance: "Observe critérios de acesso a oportunidades e formas de contribuição, sem presumir necessidades pela identidade de alguém. Explicite critérios, convide perspectivas e ofereça preparação e apoio proporcionais, verificando se a oportunidade foi acessível.",
    choices: [
      ["Qual análise identifica uma barreira possível?", "Verificar critérios usados para escolher apresentadores e quem ficou sem oportunidades.", ["Contar apenas quem se voluntaria espontaneamente.", "Concluir que quem não fala não tem interesse.", "Escolher uma pessoa diferente sem explicar o critério."], "Padrões de oportunidade e critérios revelam barreiras que espontaneidade pode ocultar."],
      ["Como ampliar participação na preparação?", "Aceitar contribuições prévias por escrito e facilitar uma rodada no encontro.", ["Exigir que todos contribuam oralmente da mesma forma.", "Designar alguém para representar opiniões sem consultar.", "Reduzir a participação a uma votação final."], "Múltiplas formas de contribuição permitem elaborar ideias sem presumir que um único formato serve a todos."],
      ["Qual escolha desenvolve uma nova pessoa com responsabilidade?", "Usar critérios explícitos e oferecer preparação e apoio compatíveis com o risco.", ["Entregar a apresentação sem contexto para demonstrar igualdade.", "Manter sempre a pessoa mais experiente.", "Selecionar por popularidade na equipe."], "Acesso a oportunidades precisa de critérios e condições de execução, não apenas mudança de nome."],
      ["Qual verificação ajuda a revisar a prática?", "Ouvir quem participou sobre barreiras e observar distribuição das oportunidades.", ["Considerar resolvido porque houve um novo apresentador.", "Medir somente aplausos na apresentação.", "Presumir que a preferência declarada nunca muda."], "Uma oportunidade isolada não prova acessibilidade permanente; experiência e padrões precisam ser acompanhados."],
    ],
  },
  "proposito-mudanca": {
    scenario: "A empresa mudará um processo de repasse para reduzir erros. A equipe ouviu apenas que é preciso inovar. O novo processo ainda tem pontos abertos, mas prazo e requisito de segurança já estão definidos.",
    guidance: "Explique problema, resultado desejado e o que está decidido ou ainda pode mudar. Propósito não substitui orientação de execução. Comunique incertezas e abra contribuição nos pontos em que ela realmente pode influenciar.",
    choices: [
      ["Qual mensagem torna o propósito concreto?", "A mudança busca reduzir erros de repasse; segurança e prazo são fixos, detalhes serão testados.", ["Precisamos mudar porque inovação é sempre positiva.", "Todos devem apoiar antes de conhecer os detalhes.", "A mudança eliminará qualquer erro do processo."], "Problema, resultado, limites e incertezas explicam a mudança sem promessa absoluta."],
      ["Onde pedir contribuições?", "Nos detalhes de execução que ainda podem ser ajustados dentro dos requisitos.", ["Em uma votação sobre o requisito já obrigatório.", "Somente depois de concluir a implantação.", "Em qualquer ponto, prometendo incorporar toda sugestão."], "Participação real exige declarar o espaço de influência disponível."],
      ["Como verificar entendimento do propósito?", "Pedir exemplos de como o novo processo deve tratar um repasse e seus limites.", ["Contar confirmações de leitura da mensagem.", "Medir a animação após a apresentação.", "Perguntar apenas se todos concordam."], "Aplicação em exemplos mostra entendimento operacional, além de exposição à mensagem."],
      ["O resultado não aparece no prazo previsto. Como comunicar?", "Apresentar evidências, limites do teste e ajustes, mantendo claro o problema a resolver.", ["Mudar a justificativa para um benefício não medido.", "Adiar a divulgação até surgir um resultado favorável.", "Dizer que a resistência é a única causa."], "Transparência mantém propósito e revisão ligados ao que foi observado."],
    ],
  },
  "impactos-mudanca": {
    scenario: "Uma mudança economiza tempo em um setor, mas transfere preenchimento para outro. Quem executa à noite não participou da consulta. O anúncio diz que todos terão menos trabalho, embora o impacto não tenha sido medido.",
    guidance: "Mapeie quem ganha, quem absorve esforço e quais dependências mudam. Ouça pessoas e turnos afetados antes de fechar detalhes. Diferencie evidência de promessa e negocie capacidade quando houver transferência de trabalho.",
    choices: [
      ["Qual lacuna precisa ser tratada primeiro?", "Ouvir o turno não consultado e medir o esforço transferido para o outro setor.", ["Confirmar a satisfação do setor beneficiado.", "Repetir o anúncio com mais clareza visual.", "Coletar sugestões somente da liderança de cada setor."], "A avaliação está incompleta sem grupos afetados e sem o custo deslocado."],
      ["Como corrigir a promessa de menos trabalho para todos?", "Explicitar que há impactos diferentes e que carga e execução serão verificadas.", ["Manter a promessa para não prejudicar a adesão.", "Retirar do anúncio qualquer referência a esforço.", "Reclassificar preenchimento como benefício para evitar medir."], "Comunicação deve reconhecer incerteza e distribuição real dos impactos."],
      ["O esforço transferido é significativo. O que negociar?", "Escopo, capacidade e responsabilidades entre áreas antes de ampliar.", ["Uma campanha de engajamento para quem recebeu mais trabalho.", "Um agradecimento público sem ajuste.", "Um prazo informal para que as pessoas se adaptem."], "Problema de capacidade exige decisão de trabalho, não apenas comunicação."],
      ["Qual retorno demonstra uso da consulta?", "Explicar mudanças feitas, sugestões não adotadas e razões ligadas aos limites.", ["Agradecer sem comentar as preocupações recebidas.", "Publicar apenas comentários favoráveis.", "Declarar que a consulta garantiu concordância de todos."], "Devolutiva deve mostrar influência real e limites, sem transformar consulta em prova de consenso."],
    ],
  },
  "piloto-mudanca": {
    scenario: "Um fluxo novo será testado por dez dias. Você precisa saber se reduz retrabalho sem atrasar atendimento. O teste inclui somente casos simples; a equipe pretende ampliar logo após o prazo, mesmo sem critério de retorno.",
    guidance: "Desenhe hipótese, escopo, referência, responsável, sinais e decisão ao final. Escolha casos que informem a hipótese e explicite limites da amostra. Ampliação depende de evidência; prazo encerrado não equivale a validação.",
    choices: [
      ["Qual hipótese pode ser testada?", "O fluxo reduz retrabalho em casos do escopo sem ultrapassar o prazo de atendimento.", ["O novo fluxo é mais moderno e será bem recebido.", "Dez dias são suficientes para validar toda a operação.", "A adesão ao teste provará a eficiência."], "Hipótese liga mudança a resultado e limite observável."],
      ["Qual problema existe na amostra apenas simples?", "Ela limita a conclusão sobre casos complexos e deve ser explicitada ou ampliada com controle.", ["Ela invalida qualquer dado do teste.", "Ela prova que os casos complexos também melhorarão.", "Ela não importa se o número de casos for grande."], "Quantidade não elimina uma diferença importante de contexto na amostra."],
      ["O prazo terminou e os dados são inconclusivos. O que decidir?", "Revisar desenho e duração ou manter escopo restrito antes de ampliar.", ["Ampliar porque o teste cumpriu os dez dias.", "Declarar sucesso pela participação do time.", "Selecionar somente casos que mostram melhora."], "A decisão deve seguir evidência e seus limites, sem confundir execução do teste com comprovação."],
      ["Qual condição de interrupção precisa ser acordada antes?", "Uma deterioração relevante de prazo ou qualidade, com caminho de retorno.", ["Qualquer comentário crítico sobre o novo fluxo.", "A falta de entusiasmo na reunião inicial.", "O simples término do período, independentemente de dados."], "A interrupção protege uma restrição relevante e permite retorno operacional."],
    ],
  },
  adocao: {
    scenario: "Todas as pessoas concluíram um treinamento, mas metade ainda usa o processo antigo. O novo formulário falha em alguns turnos, e o time não sabe onde pedir ajuda. Você precisa separar entendimento de condições de uso.",
    guidance: "Participação em treinamento não prova adoção. Observe uso, barreiras, qualidade e suporte; investigue antes de atribuir resistência. Ajuste processo e condições, comunique como obter ajuda e acompanhe a aplicação real.",
    choices: [
      ["Qual investigação orienta o primeiro ajuste?", "Verificar falhas por turno, entendimento e disponibilidade de suporte no uso real.", ["Reaplicar o treinamento inteiro a quem usa o processo antigo.", "Classificar quem não usa como resistente.", "Contar certificados emitidos como evidência de adoção."], "Condições e compreensão podem explicar a dificuldade; presença em aula não mede aplicação."],
      ["Qual ação responde à falha do formulário?", "Corrigir a barreira e combinar um procedimento temporário e um canal de apoio.", ["Exigir uso imediato mesmo quando o formulário falha.", "Manter ambos os processos indefinidamente sem critérios.", "Criar uma campanha de motivação para compensar a falha."], "A barreira operacional precisa de solução e orientação de contingência."],
      ["Qual sinal mede adoção com mais utilidade?", "Uso adequado nas situações previstas, erros e pedidos de ajuda ao longo do tempo.", ["Total de pessoas treinadas.", "Quantidade de mensagens sobre a mudança.", "Número de comentários positivos no lançamento."], "Adoção ocorre no trabalho e exige avaliar qualidade e condições de aplicação."],
      ["Após corrigir a barreira, parte do time ainda não usa. Como seguir?", "Investigar os casos restantes e adaptar apoio ou acordos conforme a causa.", ["Concluir que todas as dificuldades anteriores eram desculpas.", "Refazer o lançamento para toda a empresa.", "Retirar qualquer acompanhamento para evitar pressão."], "O acompanhamento precisa diferenciar causas, inclusive depois de um ajuste comum."],
    ],
  },
  "aprendizado-mudanca": {
    scenario: "Um processo está em uso há um mês. O prazo melhorou, mas a checagem se tornou mais difícil e exceções não foram documentadas. A equipe quer declarar a mudança concluída e retirar todo apoio.",
    guidance: "Consolidar exige verificar efeitos, exceções e sustentabilidade. Documente o que foi aprendido, mantenha responsáveis e ajuste o apoio. Uma melhoria inicial não prova estabilidade ou ausência de efeitos adversos.",
    choices: [
      ["O que verificar antes de considerar a mudança consolidada?", "Prazo, qualidade da checagem, exceções e capacidade de manter o processo.", ["Somente a melhora no indicador de prazo.", "A satisfação na apresentação de encerramento.", "O cumprimento da data do projeto."], "Consolidação observa efeitos e condições para continuidade, não apenas um ganho inicial."],
      ["Qual registro facilita o uso futuro?", "Procedimento ajustado, exceções conhecidas, responsáveis e canal de revisão.", ["A apresentação original do lançamento.", "Uma lista de pessoas que aderiram primeiro.", "Uma declaração de que o processo não deve mais mudar."], "O conhecimento operacional precisa incluir limites e meios de corrigir situações novas."],
      ["Como reduzir apoio com responsabilidade?", "Fazer redução gradual, observando execução e mantendo canal para impedimentos.", ["Retirar todo apoio na data anunciada.", "Manter acompanhamento intenso para sempre.", "Deixar o time escolher sozinho a continuidade do suporte."], "A redução acompanha evidências de aplicação e mantém acesso a ajuda quando necessário."],
      ["Uma nova exceção reduz a qualidade. O que fazer?", "Reabrir o ponto afetado, analisar a evidência e ajustar o procedimento.", ["Recusar a revisão porque o projeto foi encerrado.", "Retornar ao processo antigo em todas as áreas.", "Excluir a exceção do indicador para preservar o resultado."], "Consolidar não impede revisão; um efeito localizado pode pedir ajuste localizado."],
    ],
  },
  "agenda-lider": {
    scenario: "Sua agenda está tomada por aprovação operacional. Conversas individuais são canceladas e decisões relevantes ficam para a noite. Parte das aprovações já poderia ser delegada; uma reunião recorrente não produz encaminhamentos.",
    guidance: "A agenda expressa escolhas de responsabilidade e capacidade. Examine trabalho necessário, delegável e sem propósito claro. Proteja tempo para pessoas e decisões; modificar a agenda exige acordos de autonomia e contato, não apenas novos blocos.",
    choices: [
      ["Qual diagnóstico orienta a reorganização?", "Mapear tempo, interrupções e responsabilidades que realmente exigem sua decisão.", ["Preencher horários vazios com mais reuniões.", "Reservar tempo de estudo à noite sem mudar o trabalho atual.", "Cancelar todas as solicitações operacionais de uma vez."], "A reorganização começa por entender o trabalho e os direitos de decisão."],
      ["Qual mudança ataca a aprovação excessiva?", "Delegar decisões com limites e pontos de revisão, comunicando o novo fluxo.", ["Responder mais rapidamente a cada aprovação.", "Concentrar todas as aprovações no fim do dia.", "Delegar sem esclarecer quando consultar."], "Remover a dependência exige direitos e fronteiras explícitos, não apenas velocidade."],
      ["Qual ação protege conversas com o time?", "Reservar tempo viável e renegociar demandas concorrentes e critérios de interrupção.", ["Criar blocos que podem ser cancelados por qualquer pedido.", "Pedir que o time marque conversas fora do expediente.", "Substituir todas as conversas por atualizações escritas."], "O tempo protegido depende de acordos e prioridades compatíveis com a capacidade."],
      ["Como revisar se a agenda melhorou?", "Observar decisões destravadas, conversas realizadas e interrupções recorrentes.", ["Contar somente a quantidade de blocos na agenda.", "Verificar se todos os horários ficaram ocupados.", "Medir apenas o total de reuniões removidas."], "A utilidade aparece no trabalho que a agenda permite realizar, não na forma do calendário."],
    ],
  },
  "limites-rotina": {
    scenario: "Mensagens rotineiras chegam à noite com marcação urgente. Pessoas respondem por receio, mas uma ocorrência real pode exigir contato fora do horário. Você quer um acordo que preserve resposta necessária e limites.",
    guidance: "Distinga emergência e rotina por impacto e prazo. Defina canal, responsável e alternativa se a pessoa não estiver disponível. O acordo deve ser executável e conhecido, com revisão do uso; limites dependem também do comportamento da liderança.",
    choices: [
      ["Qual critério distingue urgência real?", "Consequência de esperar e prazo necessário para contenção, com exemplos acordados.", ["A palavra urgente escrita pelo solicitante.", "O cargo de quem enviou a mensagem.", "A ansiedade gerada pelo assunto."], "O critério precisa refletir consequência e tempo, não apenas marcação ou autoridade."],
      ["Qual acordo permite contato excepcional?", "Canal e responsável definidos, com alternativa e expectativa explícita de resposta.", ["Disponibilidade de todas as pessoas em qualquer horário.", "Proibição de qualquer contato fora do horário, inclusive ocorrência crítica.", "Uso do mesmo grupo para rotina e emergência."], "O acordo delimita exceções necessárias sem transformar disponibilidade em obrigação ilimitada."],
      ["Você envia uma ideia à noite sem urgência. Como agir?", "Programar para o horário combinado ou deixar explícito que não há resposta esperada agora.", ["Marcar como urgente para não esquecer.", "Esperar resposta e elogiar quem estiver online.", "Encaminhar a toda a equipe para obter retorno mais rápido."], "O comportamento da liderança influencia a expectativa real por trás do acordo."],
      ["O canal emergencial é usado para rotina. O que revisar?", "Exemplos, critérios e responsáveis pelo encaminhamento, com dados do uso.", ["A disposição das pessoas para responder.", "O acordo inteiro, exigindo resposta a tudo.", "Apenas a aparência das mensagens."], "O desvio de classificação pede ajuste do processo e dos critérios."],
    ],
  },
  "pressao-lider": {
    scenario: "Duas entregas estão atrasadas e uma falha afeta um cliente. Há informações incompletas, um risco relevante e pressão por resposta imediata. A equipe recebe orientações diferentes enquanto tenta conter o problema.",
    guidance: "Sob pressão, diferencie contenção, investigação e decisão definitiva. Torne claras prioridades, papéis e informações pendentes. Ajuste escopo à capacidade, comunique o que é conhecido e revise quando novas evidências alterarem o risco.",
    choices: [
      ["Qual primeiro encaminhamento reduz o risco?", "Definir contenção, responsável e informação crítica a verificar antes da decisão definitiva.", ["Escolher a solução mais rápida e tratá-la como final.", "Pedir investigação completa antes de qualquer contenção.", "Dar tarefas a todos sem explicar a prioridade."], "Conter e investigar podem ocorrer de forma coordenada sem fabricar certeza ou esperar tudo para agir."],
      ["Como comunicar ao cliente com informação incompleta?", "Informar efeito conhecido, ação em curso, incerteza e próximo horário de atualização.", ["Garantir uma causa e solução antes de verificar.", "Esperar a resolução para evitar mensagens incompletas.", "Prometer um prazo sem consultar quem executa."], "Comunicação responsável distingue fato, ação e previsão."],
      ["As orientações se contradizem. O que organizar?", "Uma prioridade comum, autoridade de decisão e canal de atualização para a equipe.", ["Deixar cada pessoa seguir a orientação mais recente.", "Adicionar reuniões sem definir quem decide.", "Exigir execução simultânea de todas as orientações."], "Coordenação de papéis e prioridades reduz retrabalho em um contexto já limitado."],
      ["Uma informação nova altera o risco. Qual resposta é coerente?", "Revisar a escolha e comunicar o ajuste e seus critérios.", ["Manter a primeira escolha para transmitir firmeza.", "Mudar silenciosamente para preservar a imagem.", "Transferir a decisão a quem trouxe a nova informação."], "Consistência está nos critérios e responsabilidade, não em defender uma escolha diante de evidência nova."],
    ],
  },
  "feedback-lider": {
    scenario: "Você pede feedback e recebe está tudo bem. Uma pessoa comenta que suas intervenções nas reuniões dificultam terminar ideias, mas pede discrição. Você quer melhorar sem pressionar por elogios ou expor o relato.",
    guidance: "Peça exemplos de um comportamento específico e agradeça sem se defender de imediato. Combine uso do relato e experimente uma ação observável. Um feedback isolado orienta investigação e teste, sem representar automaticamente todo o time.",
    choices: [
      ["Qual pergunta favorece um retorno útil?", "Em que momento interrompi a elaboração de uma ideia e como isso afetou a conversa?", ["Você acha que sou um bom líder?", "Por que ninguém me falou antes?", "Quem mais concorda com você?"], "Comportamento, situação e efeito tornam o feedback acionável sem pedir validação pessoal."],
      ["Como tratar o pedido de discrição?", "Combinar como usar o exemplo sem identificar a pessoa ou atribuir sua opinião ao grupo.", ["Citar o relato na reunião para demonstrar transparência.", "Prometer anonimato absoluto sem discutir o contexto identificável.", "Ignorar o feedback porque não pode mencionar sua origem."], "É necessário acordar uso e limites do relato e evitar identificação desnecessária."],
      ["Qual experimento verifica uma mudança sua?", "Aguardar o término das falas e pedir retorno sobre esse comportamento após algumas reuniões.", ["Falar menos sem definir em qual situação.", "Pedir elogios sobre a mudança ao final de cada reunião.", "Evitar participar de qualquer decisão."], "A ação específica pode ser observada e revisada sem abandonar a responsabilidade de liderar."],
      ["O que o relato permite concluir?", "Existe um comportamento a examinar e testar; não é uma medida de opinião de todo o time.", ["Todo o time está insatisfeito com sua liderança.", "A pessoa é excessivamente sensível a interrupções.", "Uma nova postura resolverá todas as reuniões."], "O retorno é evidência situada, não diagnóstico coletivo ou garantia de resultado."],
    ],
  },
  "plano-lider": {
    scenario: "Você quer evoluir em delegação e escolhe uma entrega para praticar. A agenda não comporta várias mudanças ao mesmo tempo. Seu plano deve gerar uma oportunidade concreta, uma evidência e um ajuste possível.",
    guidance: "Construa um ciclo curto de preparação, prática, observação e revisão. Defina comportamento e situação, planeje apoio e use evidências de execução e resultado. Não confunda esforço ou leitura com aplicação nem transforme uma tentativa em julgamento da liderança inteira.",
    choices: [
      ["Qual foco cabe no ciclo atual?", "Delegar uma entrega com resultado e limites claros, acompanhando um marco definido.", ["Melhorar todas as competências de liderança em duas semanas.", "Ler materiais sobre delegação sem escolher uma entrega.", "Deixar de acompanhar qualquer trabalho para ser mais autônomo."], "Um comportamento em oportunidade delimitada torna a prática viável e observável."],
      ["Qual evidência deve ser planejada?", "Decisões tomadas pela pessoa, critérios da entrega e apoio necessário durante o ciclo.", ["Quantidade de horas dedicadas ao estudo.", "Sensação geral de ter liderado melhor.", "Ausência de dúvidas ou pedidos de ajuda."], "Evidência da aplicação mostra autonomia e resultado sem tratar silêncio como competência."],
      ["O marco revela limite pouco claro. Qual ajuste mantém o aprendizado?", "Esclarecer o direito de decisão e testar esse acordo no próximo marco.", ["Assumir de novo a entrega inteira.", "Concluir que delegar não funciona com essa pessoa.", "Manter o acordo inicial para não invalidar o plano."], "A revisão corrige o mecanismo observado em vez de tirar conclusão geral de uma tentativa."],
      ["Como decidir o próximo ciclo?", "Usar o que foi observado para manter, ajustar ou ampliar uma prática possível.", ["Escolher sempre uma competência nova para aumentar variedade.", "Repetir o plano exatamente, independente da evidência.", "Encerrar o desenvolvimento após uma boa entrega."], "Evolução exige revisão com evidência e escolha consciente de continuidade."],
    ],
  },
};

function makeQuestion(id: string, lessonId: string, choice: Choice, scenario: string): StudyQuestion {
  const [prompt, answer, alternatives, explanation] = choice;
  const correct = [...id].reduce((sum, char) => sum + char.charCodeAt(0), 0) % 4;
  const options: string[] = [...alternatives]; options.splice(correct, 0, answer);
  return { id, lessonId, scenario, prompt, options, correct, explanation };
}
export function advancedQuestions(lesson: StudyLesson) {
  const lab = leadershipLabs[lesson.id];
  if (!lab) throw new Error(`Falta o caso de aplicação da aula ${lesson.id}`);
  return lab.choices.map((choice, index) => makeQuestion(`aplicacao-v2:${lesson.id}:${index}`, lesson.id, choice, lab.scenario));
}
export function deepenLeadershipLesson(lesson: StudyLesson): StudyLesson {
  const lab = leadershipLabs[lesson.id];
  if (!lab) throw new Error(`Falta o conteúdo avançado da aula ${lesson.id}`);
  return { ...lesson, minutes: lesson.minutes + 5, sections: [...lesson.sections,
    { heading: "Quando os critérios entram em conflito", text: lab.guidance },
    { heading: "Caso de aplicação: analise antes de escolher", text: lab.scenario },
    { heading: "Raciocínio para conduzir o caso", text: lab.choices.map(([prompt, answer, , rationale]) => `${prompt} ${answer} ${rationale}`).join(" ") },
  ] };
}
