import type { StudyCourse, StudyLesson, StudyQuestion } from "./academy-types";

// Situações didáticas autorais. Não representam dados ou diagnósticos do aluno.
type Choice = [string, string, [string, string, string], string];
type Brief = [title: string, concept: string, scenario: string, diagnosis: string, action: string, mistake: string, evidence: string, review: string];
type CourseBrief = { id: string; title: string; skill: string; description: string; lessons: Brief[] };
const briefs: CourseBrief[] = [
  { id: "estrategia", title: "Da estratégia às escolhas do time", skill: "Direção e foco", description: "Traduza a direção do negócio em escolhas, limites e prioridades que o time consegue executar.", lessons: [
    ["Tradução da estratégia", "Estratégia orienta escolhas de onde atuar e o que deixar de fazer. Uma mensagem ampla precisa virar um resultado e critérios para o trabalho diário.", "A direção pede foco em retenção, mas seu time recebe simultaneamente pedidos de novos recursos e correções. A capacidade não comporta tudo no trimestre.", "Identificar quais entregas influenciam a permanência dos clientes e quais hipóteses sustentam essa relação.", "Priorizar uma entrega ligada à retenção, explicitar a hipótese e negociar o que sai do trimestre.", "Atender todos os pedidos para manter as áreas satisfeitas, sem rever a capacidade.", "Evolução da retenção e uso da entrega, considerando mudanças de perfil dos clientes.", "Reavaliar a hipótese quando houver uso sem melhora no resultado esperado."],
    ["Escolhas e renúncias", "Uma prioridade só existe quando altera a alocação de esforço. Renúncias precisam ser explícitas, com efeitos e responsáveis conhecidos.", "Três iniciativas foram chamadas de prioridade máxima. Todas dependem das mesmas duas pessoas, e os prazos externos ainda não foram negociados.", "Comparar impacto, urgência real, dependências e custo de adiar cada iniciativa.", "Ordenar as iniciativas e negociar prazos com os responsáveis pelas dependências antes de confirmar compromissos.", "Distribuir as pessoas entre as três iniciativas e manter todos os prazos originais.", "Entregas concluídas e tempo de espera nos gargalos, além do impacto das renúncias.", "Reordenar quando surgir uma restrição verificável, comunicando o compromisso afetado."],
    ["Desdobramento em resultados", "Uma entrega é algo produzido; um resultado é a mudança que ela permite observar. A ligação entre ambos precisa ser testável.", "O time promete lançar um guia para reduzir retrabalho. O lançamento está no prazo, mas ninguém definiu o que contará como retrabalho nem como observar seu uso.", "Separar publicação do guia, adoção e redução de falhas nas situações que ele atende.", "Definir uma medida de retrabalho, registrar a referência inicial e acompanhar uso e efeito do guia.", "Considerar a estratégia cumprida assim que o arquivo for publicado.", "Taxa de retrabalho no mesmo tipo de demanda e sinais de adoção do guia.", "Investigar barreiras de uso antes de concluir que o conteúdo não funciona."],
    ["Horizontes de planejamento", "O plano próximo detalha decisões executáveis; horizontes distantes preservam hipóteses e opções. Precisão aparente não elimina incerteza.", "Você recebe pedido de cronograma diário para nove meses, mas a demanda depende de uma aprovação prevista para daqui a seis semanas.", "Identificar decisões próximas que independem da aprovação e hipóteses ainda abertas.", "Detalhar o ciclo próximo e manter cenários para o restante, com revisão após a aprovação.", "Preencher datas definitivas para todo o período para transmitir segurança.", "Mudanças de hipótese e compromissos confirmados em cada revisão do horizonte.", "Atualizar cenários com a decisão externa e renegociar efeitos no plano próximo."],
    ["Revisão estratégica", "Revisar estratégia exige comparar hipóteses e efeitos. Não basta contabilizar tarefas; é preciso decidir onde continuar investindo.", "Uma iniciativa consumiu dois meses e cumpriu todas as entregas. O resultado não mudou, mas outra oportunidade ganhou evidências de impacto com custo menor.", "Comparar o valor futuro das alternativas e a validade da hipótese inicial.", "Revisar o investimento restante e delimitar um teste da nova oportunidade, preservando o aprendizado anterior.", "Continuar a iniciativa apenas porque já consumiu dois meses de esforço.", "Resultado observado, custo adicional e informação produzida pelo novo teste.", "Manter, ajustar ou interromper a iniciativa segundo a evidência da revisão."],
  ] },
  { id: "indicadores", title: "Indicadores sem atalhos", skill: "Leitura crítica de dados", description: "Interprete métricas, incertezas e efeitos colaterais antes de decidir sobre pessoas e resultados.", lessons: [
    ["Indicador e pergunta", "Uma medida deve responder a uma pergunta de decisão. Antes de criar um painel, defina população, cálculo, fonte, frequência e limite de interpretação.", "O time quer medir produtividade contando mensagens. Pessoas de atendimento escrevem mais que especialistas que resolvem casos longos, e os papéis são diferentes.", "Verificar se quantidade de mensagens representa entrega útil em cada papel.", "Escolher medidas ligadas à resolução e qualidade por tipo de trabalho, explicitando limites de comparação.", "Criar um ranking individual pelo volume bruto de mensagens.", "Resolução por tipo de caso e qualidade, sem equiparar papéis diferentes.", "Revisar a medida se ela incentivar volume sem solução útil."],
    ["Médias e distribuição", "A média pode esconder diferenças relevantes. Examine distribuição, tamanho da amostra e grupos comparáveis antes de concluir que todos vivem a mesma situação.", "O tempo médio de resposta caiu, mas casos complexos esperam mais. O volume de solicitações simples cresceu e alterou a composição da amostra.", "Comparar tempos por complexidade e a mudança na proporção de tipos de solicitação.", "Analisar a distribuição e os casos complexos antes de afirmar melhora geral.", "Anunciar melhora para todos com base apenas na nova média.", "Tempos por categoria e proporção de casos acima do prazo acordado.", "Investigar o fluxo dos casos complexos e revisar capacidade dedicada a eles."],
    ["Correlação e causalidade", "Duas medidas podem variar juntas por uma terceira condição. Uma associação orienta uma hipótese; não prova o mecanismo que produziu o resultado.", "A satisfação subiu depois de uma formação. No mesmo período o volume de trabalho caiu e a equipe recebeu uma ferramenta nova.", "Separar as mudanças simultâneas e a evidência específica de aplicação da formação.", "Tratar o efeito da formação como hipótese e comparar situações equivalentes com aplicação observada.", "Atribuir toda a melhora à formação por ter acontecido antes do resultado.", "Aplicação dos comportamentos estudados em contextos comparáveis de carga e ferramenta.", "Revisar a atribuição quando outras mudanças explicarem parte do resultado."],
    ["Sinais e variabilidade", "Oscilações podem ser variação normal ou alteração do processo. Considere sequência temporal, volume e contexto antes de reagir a um único ponto.", "A taxa de falhas dobrou nesta semana, mas houve apenas quatro entregas. Nas oito semanas anteriores, os volumes variaram entre quarenta e sessenta.", "Examinar contagens, denominadores e natureza das falhas, além da porcentagem.", "Investigar as ocorrências relevantes e acompanhar uma série comparável antes de redesenhar todo o processo.", "Mudar a rotina completa porque a porcentagem semanal dobrou.", "Contagem e taxa por volume comparável, com descrição das causas verificadas.", "Intervir no mecanismo confirmado e observar sua evolução em novas entregas."],
    ["Efeitos dos incentivos", "Quando uma medida vira alvo isolado, as pessoas podem otimizar o número sacrificando o resultado. Use contrapesos e investigue o comportamento induzido.", "O prazo médio melhorou após uma meta de velocidade, mas aumentaram reaberturas e reclamações. A primeira resposta encerra casos sem resolver a demanda.", "Examinar a relação entre incentivo de velocidade, encerramento e reabertura.", "Revisar o critério de conclusão e acompanhar resolução, qualidade e prazo em conjunto.", "Elevar ainda mais a meta de velocidade para compensar as reclamações.", "Resolução sem reabertura e satisfação, ao lado do tempo de atendimento.", "Ajustar o incentivo se o número melhorar sem resolver a necessidade."],
  ] },
  { id: "capacidade", title: "Capacidade, foco e fluxo", skill: "Organização do trabalho", description: "Reduza trabalho simultâneo e trate gargalos sem transformar urgência em sobrecarga permanente.", lessons: [
    ["Limites de trabalho em andamento", "Iniciar tudo aumenta filas e custo de troca de contexto. Limitar trabalho em andamento protege conclusão, com regra explícita para novas entradas.", "Cada pessoa tem cinco tarefas abertas. Nenhuma termina porque novas urgências entram diariamente, e o time é cobrado pela quantidade iniciada.", "Mapear tarefas abertas, interrupções e tempo até conclusão.", "Combinar um limite de tarefas simultâneas e uma regra de troca quando entrar urgência.", "Pedir mais tarefas iniciadas para mostrar que todas as demandas estão sendo atendidas.", "Tempo de conclusão e quantidade de itens parados no fluxo.", "Ajustar o limite com evidência de bloqueios, sem abandonar a regra a cada pedido."],
    ["Gargalos e filas", "A capacidade do fluxo depende da restrição que limita saídas. Acelerar etapas anteriores pode apenas aumentar a fila e ocultar o problema.", "Produção entrega vinte itens por dia, mas a revisão aprova oito. O time propõe ampliar produção enquanto a fila de revisão já cresce há duas semanas.", "Identificar a revisão como restrição e separar capacidade disponível de retrabalho.", "Limitar entradas na revisão e trabalhar critérios, apoio e causas de retrabalho no gargalo.", "Aumentar produção para pressionar a revisão a acelerar.", "Fila, idade dos itens e saídas aprovadas na etapa de revisão.", "Redistribuir apoio quando a restrição mudar, acompanhando o fluxo completo."],
    ["Planejar com capacidade real", "Capacidade considera trabalho recorrente, ausências e variabilidade. Planejar ocupação total deixa o time sem margem para demandas previsíveis.", "O plano usa todas as horas disponíveis em projetos. Atendimento recorrente consome um dia por semana e duas pessoas estarão ausentes no mês.", "Calcular disponibilidade após recorrências e ausências conhecidas.", "Reduzir o escopo do ciclo e reservar capacidade compatível com demandas recorrentes.", "Manter o escopo e esperar que o time absorva atendimento sem alterar o plano.", "Demanda planejada e não planejada, entregas e necessidade de renegociação.", "Recalibrar a reserva com o histórico de entradas e não com pressão por ocupação total."],
    ["Dependências visíveis", "Uma dependência precisa de dono, condição de entrega e data negociada. Esperar silenciosamente transforma incerteza externa em atraso interno.", "Uma entrega depende de dados de outra área. O plano chama a etapa de aguardando, sem responsável externo nem definição de formato ou prazo.", "Identificar informação necessária, interlocutor e efeito do atraso na entrega.", "Negociar formato, prazo e escalonamento da dependência com quem pode fornecer os dados.", "Manter a etapa como aguardando e cobrar o time pelo prazo original.", "Cumprimento do acordo externo e tempo bloqueado na dependência.", "Renegociar escopo ou prazo quando a condição externa não puder ser cumprida."],
    ["Urgências e custo de interrupção", "Urgência deve ser definida por consequência e tempo de resposta. Uma entrada excepcional precisa expor qual compromisso será interrompido.", "Um pedido marcado como urgente compete com uma falha que afeta clientes. O primeiro vem de uma pessoa influente, mas pode esperar três dias.", "Comparar consequência de esperar e prazo de contenção de cada demanda.", "Priorizar a falha, explicar os critérios e negociar quando o pedido poderá entrar.", "Priorizar o pedido influente para evitar conflito, mantendo as duas entregas prometidas.", "Impacto contido e compromissos afetados por cada interrupção.", "Revisar critérios de entrada quando pedidos rotineiros repetirem a classificação urgente."],
  ] },
  { id: "individuais", title: "Conversas individuais que desenvolvem", skill: "Acompanhamento de pessoas", description: "Conduza conversas contínuas com escuta, responsabilidade e acordos de desenvolvimento.", lessons: [
    ["Agenda compartilhada", "Uma conversa individual dá espaço a contexto, obstáculos e desenvolvimento. Atualizações podem vir antes; a pauta precisa admitir temas da pessoa.", "Os encontros individuais viraram leitura de tarefas. Uma pessoa tenta falar de dificuldade com outra área, mas a pauta de status ocupa todo o tempo.", "Identificar o tema que precisa de diálogo e o status que pode ser compartilhado antes.", "Construir uma pauta conjunta com tempo para obstáculos e desenvolvimento, enviando atualizações antes.", "Acrescentar mais perguntas de status para aproveitar o encontro.", "Temas discutidos e acordos acompanhados, sem medir qualidade apenas pela duração.", "Rever o formato com a pessoa se a conversa continuar sem espaço para seus temas."],
    ["Perguntas que abrem contexto", "Perguntas abertas investigam a situação sem embutir um julgamento. Confirmar entendimento evita orientar o problema errado.", "Uma entrega atrasou após mudanças de escopo. Você pensa em falta de compromisso, mas ainda não ouviu como as mudanças chegaram à pessoa.", "Distinguir atraso observado da hipótese sobre compromisso e do contexto ainda desconhecido.", "Perguntar como o escopo mudou e confirmar o entendimento antes de combinar correções.", "Abrir perguntando por que a pessoa não se compromete com os prazos.", "Sequência das mudanças e condições que impediram cumprir o acordo inicial.", "Reformular o próximo passo se a conversa revelar dependências não consideradas."],
    ["Acordos de acompanhamento", "Um acordo útil define comportamento, oportunidade, apoio e revisão. A intenção de melhorar precisa virar algo observável no trabalho.", "Após uma conversa sobre apresentações, vocês combinaram melhorar comunicação. Duas semanas depois, cada um interpreta progresso de modo diferente.", "Identificar a ausência de comportamento observável e oportunidade de prática.", "Combinar uma apresentação com síntese de decisão, ensaio e retorno após o encontro.", "Manter o pedido genérico para não limitar o estilo da pessoa.", "Clareza da síntese e compreensão da decisão pelos participantes.", "Ajustar o apoio e o foco da próxima apresentação com base no retorno observado."],
    ["Continuidade sem invasão", "Registros devem apoiar acordos de trabalho com acesso adequado. Informações pessoais sensíveis não precisam ser coletadas para demonstrar escuta.", "Uma pessoa conta uma dificuldade pessoal que afeta um prazo e pede discrição. Você precisa acompanhar a entrega sem expor detalhes à equipe.", "Separar ajuste de trabalho necessário dos detalhes pessoais não necessários.", "Combinar o prazo e o apoio, registrando somente o acordo de trabalho com acesso restrito.", "Registrar toda a história na pauta compartilhada para contextualizar o atraso.", "Execução do acordo e necessidade de apoio, sem circulação dos detalhes pessoais.", "Revisar o ajuste em conversa privada conforme o que a pessoa puder compartilhar."],
    ["Conversas com autonomia", "Acompanhamento combina apoio e responsabilidade. Resolver cada obstáculo pela pessoa reduz oportunidade de elaborar alternativas e decidir.", "Uma pessoa traz um bloqueio e pede que você resolva. Ela tem autonomia para negociar uma parte, mas não para mudar o compromisso com o cliente.", "Distinguir decisões sob autonomia da pessoa e compromisso que exige sua participação.", "Pedir alternativas e apoiar a negociação dentro dos limites, assumindo apenas a decisão que exige sua autoridade.", "Assumir toda a negociação para encerrar o bloqueio rapidamente.", "Alternativas elaboradas e decisões tomadas dentro da autonomia combinada.", "Rever limites e apoio se a mesma dependência de aprovação se repetir."],
  ] },
  { id: "coaching", title: "Perguntas para ampliar autonomia", skill: "Desenvolvimento na conversa", description: "Use perguntas, hipóteses e experimentos para desenvolver o raciocínio de quem você lidera.", lessons: [
    ["Perguntar ou orientar", "Perguntas apoiam elaboração quando há espaço para escolha. Regras obrigatórias e risco imediato exigem orientação clara, sem simular autonomia.", "Uma pessoa nova pede ajuda em uma tarefa com regra de segurança obrigatória. Você quer desenvolver seu raciocínio, mas ela ainda desconhece o procedimento.", "Distinguir orientação obrigatória de alternativas que podem ser exploradas com segurança.", "Explicar a regra e demonstrar sua aplicação antes de explorar opções permitidas.", "Pedir que a pessoa descubra sozinha a regra para desenvolver independência.", "Entendimento do procedimento e decisões corretas dentro dos limites permitidos.", "Ampliar a exploração quando houver domínio do procedimento e risco delimitado."],
    ["Problema antes da solução", "Conselhos prematuros podem resolver uma interpretação errada. Explore o resultado desejado, o contexto e as tentativas antes de propor caminhos.", "Uma pessoa pede uma ferramenta nova porque perde prazos. As demandas chegam por três canais e mudam sem registro, mas vocês ainda não discutiram esse fluxo.", "Investigar como demandas e mudanças são recebidas antes de concluir que falta ferramenta.", "Mapear o fluxo com a pessoa e comparar ajustes de processo e ferramenta pelo problema observado.", "Escolher sua ferramenta preferida como primeira resposta.", "Mudanças registradas, visibilidade dos prazos e redução de perdas no fluxo.", "Rever a solução quando o mecanismo real do atraso diferir da hipótese inicial."],
    ["Alternativas e critérios", "Uma pergunta de desenvolvimento ajuda a comparar opções por critérios. Perguntas que escondem uma resposta desejada limitam o raciocínio.", "Você já prefere uma alternativa e pergunta se a pessoa não acha que seu caminho é melhor. Ela concorda, mas não explica riscos nem critérios.", "Reconhecer que a pergunta direcionou a resposta e não revelou o raciocínio da pessoa.", "Pedir duas alternativas, seus riscos e critérios antes de declarar sua preferência.", "Repetir a pergunta com mais ênfase para confirmar entendimento.", "Critérios explicitados e diferenças relevantes entre alternativas.", "Voltar à pergunta aberta quando a conversa se reduzir a concordar com sua opinião."],
    ["Experimentos de desenvolvimento", "Aprender uma habilidade exige oportunidade delimitada, preparação e retorno. Um experimento ajusta dificuldade e risco ao contexto.", "Uma pessoa quer conduzir negociações, mas o próximo contrato é crítico. Há uma conversa interna de baixo risco na semana anterior.", "Identificar uma oportunidade de prática com risco compatível e critério de aprendizagem.", "Preparar a negociação interna, observar o processo e revisar antes de ampliar responsabilidade.", "Entregar o contrato crítico sem preparação para acelerar o desenvolvimento.", "Uso de critérios, escuta e acordos na negociação observada.", "Ajustar o nível de apoio antes de transferir decisões de maior consequência."],
    ["Devolutiva sobre raciocínio", "Retorno de desenvolvimento descreve escolhas e seus efeitos, não apenas o acerto final. Pergunte como a pessoa chegou à decisão e o que mudaria.", "Uma decisão produziu bom resultado por uma condição externa inesperada. A pessoa afirma que seu processo foi perfeito e quer repetir a escolha sem análise.", "Separar resultado favorável da qualidade do raciocínio com as informações disponíveis.", "Revisar hipóteses e critérios da escolha e discutir o que faria sentido em outro contexto.", "Validar o processo apenas porque o resultado foi bom.", "Coerência entre informação disponível, critérios e riscos considerados.", "Repetir o raciocínio útil e ajustar a hipótese que dependia de condição externa."],
  ] },
  { id: "negociacao", title: "Negociar compromissos e limites", skill: "Negociação para líderes", description: "Construa acordos sustentáveis entre interesses, alternativas e responsabilidades diferentes.", lessons: [
    ["Interesses e posições", "A posição é a solução pedida; o interesse explica o que ela precisa atender. Investigar interesses permite alternativas além de aceitar ou recusar.", "Uma área pede entrega amanhã e seu time precisa de três dias. O pedido visa uma demonstração, que usa apenas parte da funcionalidade.", "Identificar o que a demonstração realmente precisa e o risco de uma entrega parcial.", "Negociar uma parte demonstrável com limites claros e manter o prazo da entrega completa.", "Prometer a entrega completa amanhã para preservar a relação.", "Utilidade da parte entregue para a demonstração e cumprimento do acordo restante.", "Rever o escopo parcial se ele criar expectativa de capacidade ainda inexistente."],
    ["Alternativas ao acordo", "Conhecer alternativas e limites evita aceitar compromisso inviável. Sua alternativa precisa ser concreta, com custo e condições, não uma ameaça.", "Um parceiro exige um prazo incompatível com a qualidade mínima. Há possibilidade de reduzir escopo ou buscar outro parceiro, com custo adicional.", "Comparar custo, risco e viabilidade das alternativas ao acordo proposto.", "Apresentar redução de escopo e um limite de qualidade, avaliando a alternativa se não houver acordo.", "Aceitar o prazo e decidir depois quais verificações abandonar.", "Viabilidade do compromisso negociado e custo da alternativa disponível.", "Atualizar a alternativa se condições mudarem antes de fechar o acordo."],
    ["Critérios de concessão", "Concessões devem atender interesses sem violar limites essenciais. Faça trocas explícitas e avalie o efeito total do compromisso.", "Seu time aceita antecipar uma entrega se outra for adiada. A outra área quer a antecipação, mas se recusa a registrar o adiamento.", "Identificar a capacidade compartilhada e a compensação indispensável para antecipar.", "Confirmar a troca de prazo por escrito antes de aceitar a antecipação.", "Aceitar a antecipação e manter silenciosamente os dois prazos.", "Capacidade liberada e entendimento comum dos novos compromissos.", "Reabrir a negociação se a contrapartida não se concretizar."],
    ["Negociação entre áreas", "Acordos entre áreas exigem responsabilidades nas interfaces. Critérios de aceitação e revisão reduzem disputa sobre quando uma entrega está pronta.", "Uma área envia dados e considera a tarefa concluída; a outra devolve por falta de campos. Nenhuma definiu formato nem validação antes da transferência.", "Mapear o que cada área precisa para aceitar a transferência.", "Combinar formato, validação e responsáveis por correções na interface.", "Exigir que a outra área aceite qualquer arquivo para não atrasar o projeto.", "Transferências aceitas sem devolução e motivos de exceção.", "Atualizar o acordo quando surgirem requisitos novos, sem mudar critérios retroativamente."],
    ["Fechamento verificável", "Um acordo precisa registrar escopo, condição, responsável e revisão. Termos vagos geram expectativas distintas mesmo quando todos dizem concordar.", "Após uma negociação, todos concordam em entregar em breve. Uma pessoa entende sexta, outra fim do mês, e a dependência externa continua sem dono.", "Identificar termos ambíguos e dependências não atribuídas.", "Confirmar data, escopo, responsável e condição externa antes de encerrar.", "Considerar o acordo fechado porque ninguém discordou na reunião.", "Entendimento comum e confirmação das condições necessárias à execução.", "Renegociar explicitamente qualquer mudança de condição antes do vencimento."],
  ] },
  { id: "influencia", title: "Influência sem autoridade formal", skill: "Articulação e colaboração", description: "Mobilize parceiros com contexto, evidências e reciprocidade sem depender do cargo.", lessons: [
    ["Mapear interlocutores", "Influência exige entender quem decide, executa e sofre o efeito da proposta. Cargo não revela sozinho informação ou interesse relevante.", "Uma mudança foi aprovada por um diretor, mas as pessoas que operam o processo não participaram e apontam restrições que inviabilizam a execução.", "Mapear quem conhece a operação e quem precisa decidir sobre as restrições.", "Ouvir executores e pessoas afetadas e levar as restrições verificadas à decisão.", "Usar a aprovação do diretor para encerrar qualquer questionamento operacional.", "Restrições incorporadas e clareza de papéis na execução.", "Rever a proposta quando aparecer uma condição operacional não contemplada."],
    ["Valor para o interlocutor", "Uma proposta ganha força quando explica a necessidade de quem recebe, sem prometer benefício que não pode sustentar. Valor precisa ser específico.", "Você quer que outra área adote um fluxo para reduzir retrabalho do seu time. Para ela, o fluxo aumenta registros e ainda não está claro o benefício.", "Entender o custo adicional e as necessidades da área parceira.", "Desenhar um teste que reduza devoluções nas duas áreas e medir também o esforço de registro.", "Repetir apenas o benefício para seu time e pedir colaboração por espírito de equipe.", "Retrabalho em ambas as áreas e custo de manter o novo fluxo.", "Simplificar o registro se o custo superar o ganho verificado."],
    ["Evidência e narrativa", "Apresentar evidência envolve fonte, contexto e limite. Uma narrativa esclarece a decisão necessária sem esconder informação contrária.", "Sua proposta tem um piloto bem-sucedido com um time pequeno. Você quer convencer três áreas maiores, que têm volumes e restrições diferentes.", "Identificar limites do piloto e diferenças entre os contextos.", "Apresentar resultado e limites e propor uma expansão gradual com verificação local.", "Apresentar o piloto como garantia de sucesso em qualquer área.", "Efeito e viabilidade em cada contexto da expansão.", "Adaptar a proposta se a escala alterar o mecanismo observado no piloto."],
    ["Reciprocidade responsável", "Colaboração pode envolver apoio mútuo, mas não troca de favores que viole critérios. Combine contribuições legítimas e transparentes.", "Um parceiro oferece priorizar sua demanda se você ignorar uma etapa obrigatória de controle na demanda dele. A relação é importante para o projeto.", "Distinguir colaboração legítima de uma troca que viola um limite obrigatório.", "Recusar a dispensa do controle e buscar uma contribuição compatível com os critérios das duas áreas.", "Aceitar a troca para garantir apoio e tratar o controle como detalhe interno.", "Compromissos cumpridos dentro dos critérios e responsabilidades autorizadas.", "Escalar o impasse pelo fluxo adequado se a colaboração depender de violar o controle."],
    ["Compromisso sem coerção", "Discordância pode revelar restrição ou interesse ainda não atendido. Persuadir exige espaço para objeção e uma decisão explícita sobre o próximo passo.", "Uma pessoa aceita sua proposta na reunião, mas depois não consegue executar. Ela diz que o compromisso foi anunciado antes de discutir sua capacidade.", "Examinar se houve acordo real e capacidade para assumir a execução.", "Reabrir o compromisso com limites, recursos e possibilidade de renegociação.", "Cobrar obediência porque a pessoa não discordou publicamente.", "Compromissos confirmados e execução compatível com capacidade.", "Mudar o processo de fechamento para permitir objeções antes do anúncio."],
  ] },
  { id: "inclusao", title: "Participação e decisões inclusivas", skill: "Inclusão no cotidiano", description: "Revise oportunidades, formatos de participação e critérios sem rotular pessoas.", lessons: [
    ["Formatos de participação", "Participação não exige um único estilo de contribuição. Alternar preparação escrita e diálogo permite ouvir argumentos antes de confundir rapidez com qualidade.", "Sempre as mesmas pessoas respondem primeiro. Uma colega envia depois uma análise importante que muda a decisão, mas a reunião já havia encerrado o tema.", "Identificar como o formato favorece respostas rápidas e exclui preparação.", "Enviar a pergunta antes e usar registro individual seguido de discussão antes de decidir.", "Escolher apenas quem responde rápido para acelerar todas as reuniões.", "Variedade de argumentos considerados e tempo adequado para contribuição.", "Ajustar preparação e facilitação se contribuições relevantes continuarem chegando tarde."],
    ["Critérios e vieses de oportunidade", "Oportunidades devem usar critérios ligados à tarefa e desenvolvimento. Afinidade e visibilidade não substituem evidências de preparo e apoio disponível.", "Você costuma convidar para projetos quem almoça com você. Outras pessoas demonstram competência, mas não recebem chance de assumir trabalhos relevantes.", "Examinar critérios usados e concentração de oportunidades por proximidade.", "Explicitar critérios de escolha e considerar preparo e apoio de todo o grupo elegível.", "Manter a escolha por afinidade para garantir uma relação de confiança.", "Distribuição de oportunidades e evidências usadas nas escolhas.", "Revisar critérios quando proximidade continuar decidindo mais que requisitos da tarefa."],
    ["Acessibilidade na rotina", "Acessibilidade considera barreiras de formato, ambiente e informação. Pergunte pela condição necessária ao trabalho sem exigir exposição pessoal desnecessária.", "Uma reunião usa vídeo sem legenda e arquivos enviados minutos antes. Uma pessoa relata dificuldade de acompanhar e pede material com antecedência.", "Identificar barreiras de acesso ao conteúdo e ao ritmo do encontro.", "Disponibilizar material antes, recursos de acesso e um canal para esclarecer dúvidas.", "Exigir que a pessoa explique publicamente sua condição para justificar o ajuste.", "Possibilidade de acompanhar e contribuir no formato ajustado.", "Revisar o recurso com quem o utiliza sem presumir que uma solução serve a todos."],
    ["Interrupções e distribuição de voz", "Facilitar exige observar padrões e intervir no comportamento. Proteja a contribuição sem falar pela pessoa nem transformar o episódio em rótulo.", "Uma participante é interrompida em três tentativas de apresentar dados. Depois um colega repete seu argumento e recebe reconhecimento pela ideia.", "Identificar o padrão de interrupção e a origem da contribuição.", "Devolver a palavra à participante e reconhecer a autoria do argumento na discussão.", "Pedir que ela seja mais firme e deixar a reunião seguir sem intervenção.", "Conclusão das falas e reconhecimento das contribuições de origem.", "Combinar regras de facilitação e acompanhar o padrão nos próximos encontros."],
    ["Divergência com respeito", "Inclusão permite questionar ideias e mantém critérios de decisão. Discordar não autoriza ataque pessoal, e consenso não pode ser exigido pelo medo.", "Uma pessoa questiona uma proposta com dados. O grupo chama sua postura de negativa e sugere retirar sua participação para preservar harmonia.", "Distinguir crítica à proposta de comportamento desrespeitoso.", "Examinar os dados e reforçar regras de respeito, decidindo pelos critérios do trabalho.", "Excluir a pessoa para que a proposta obtenha consenso mais rápido.", "Argumentos avaliados e decisão justificada sem ataque pessoal.", "Intervir sobre comportamentos desrespeitosos sem impedir contrapontos úteis."],
  ] },
  { id: "hibrido", title: "Liderar equipes distribuídas", skill: "Trabalho remoto e híbrido", description: "Crie acordos de colaboração, autonomia e visibilidade para pessoas em locais diferentes.", lessons: [
    ["Acordos de disponibilidade", "Disponibilidade precisa considerar horário, tarefa e urgência. Presença online não prova entrega; defina janelas e critérios para contatos excepcionais.", "Seu time remoto mantém mensagens abertas o dia todo. Pessoas interrompem trabalho profundo para mostrar presença, mas entregas complexas atrasam.", "Distinguir necessidade de resposta da expectativa de presença permanente.", "Combinar janelas de resposta, canal urgente e blocos de concentração com resultados esperados.", "Cobrar resposta imediata em qualquer mensagem para demonstrar comprometimento.", "Entregas e atendimento de urgências dentro dos acordos de contato.", "Ajustar janelas se bloqueios relevantes aguardarem mais que o prazo necessário."],
    ["Documentação que permite agir", "Registro assíncrono deve permitir entender contexto, decisão e próximo passo. Documentar tudo sem estrutura pode dificultar acesso ao que importa.", "Uma decisão ficou em uma chamada. Quem estava em outro fuso recebeu apenas a frase decidido, faça a mudança, sem critérios ou responsável.", "Identificar contexto e limites que faltam para executar a decisão.", "Registrar escolha, razões, responsável e próximo passo em local acessível às pessoas envolvidas.", "Enviar a gravação inteira e considerar que isso substitui o registro da decisão.", "Capacidade de executar sem depender de repetir a chamada.", "Melhorar o registro quando as mesmas dúvidas de contexto se repetirem."],
    ["Equidade entre presença e distância", "Acesso a informação e oportunidades não deve depender de estar fisicamente perto da liderança. Observe como decisões e convites circulam.", "Parte do time trabalha remoto e descobre mudanças depois de conversas no escritório. Projetos relevantes acabam atribuídos a quem estava presente nessas conversas.", "Mapear decisões informais e critérios de distribuição de oportunidades.", "Registrar decisões para todo o grupo e escolher responsáveis por critérios explícitos, incluindo pessoas remotas.", "Presumir que quem está no escritório demonstra mais interesse em crescer.", "Acesso tempestivo à informação e distribuição de oportunidades por critérios.", "Rever canais se pessoas remotas continuarem descobrindo decisões após a execução."],
    ["Coordenação entre fusos", "Coordenação distribuída depende de interfaces, prazos e passagem de contexto. Horários comuns precisam ser viáveis e não sacrificar sempre o mesmo grupo.", "Dois grupos em fusos distintos esperam respostas um do outro. Todas as reuniões comuns são tarde para o mesmo grupo, que acumula extensão de jornada.", "Identificar dependências que exigem sincronia e desigualdade de horários.", "Criar passagem assíncrona de contexto e alternar horários das conversas realmente necessárias.", "Manter o mesmo horário porque já está na agenda e pedir flexibilidade ao grupo afetado.", "Tempo bloqueado entre grupos e distribuição do esforço de sincronia.", "Reduzir dependências simultâneas se a alternância ainda não tornar o fluxo viável."],
    ["Visibilidade sem vigilância", "Acompanhamento remoto usa resultados, riscos e acordos de apoio. Medir cliques ou câmera ligada pode incentivar presença sem trabalho útil.", "Uma proposta de monitoramento registra telas a cada minuto. O time entrega resultados, mas a liderança sente falta de visibilidade dos bloqueios.", "Separar a necessidade de acompanhar bloqueios da coleta invasiva de atividade.", "Combinar atualização de marcos e bloqueios com conversas de apoio e acesso proporcional.", "Implantar capturas contínuas de tela como principal evidência de produtividade.", "Marcos cumpridos, riscos sinalizados e decisões destravadas no acompanhamento.", "Ajustar a frequência de atualização conforme risco, sem transformar presença em resultado."],
  ] },
  { id: "talentos", title: "Desenvolver talentos no trabalho", skill: "Aprendizagem da equipe", description: "Planeje oportunidades de prática, apoios e evidências para desenvolver competências relevantes.", lessons: [
    ["Necessidade de desenvolvimento", "Desenvolvimento começa por uma competência requerida em uma situação real. Separe falta de conhecimento, condição de trabalho e expectativa pouco clara.", "Uma pessoa erra uma análise e você pensa em indicar um curso. O acesso aos dados estava incompleto e os critérios da análise nunca foram explicados.", "Distinguir lacuna de habilidade das condições e critérios ausentes.", "Esclarecer critérios e acesso antes de definir qual habilidade precisa ser desenvolvida.", "Prescrever treinamento para qualquer erro sem examinar contexto.", "Execução com critérios e dados adequados e dificuldades que ainda permanecem.", "Definir uma aprendizagem específica se a dificuldade persistir em condições viáveis."],
    ["Oportunidade e apoio", "Uma habilidade se desenvolve com prática compatível, preparação e retorno. Responsabilidade sem apoio pode transformar aprendizagem em exposição desnecessária.", "Uma pessoa quer melhorar facilitação. A primeira oportunidade disponível é uma reunião tensa com clientes, mas existe um encontro interno antes.", "Comparar risco das oportunidades e nível atual de preparo.", "Preparar e acompanhar o encontro interno antes de ampliar a responsabilidade.", "Entregar a reunião crítica sem apoio para testar a capacidade da pessoa.", "Uso da pauta, participação e clareza dos encaminhamentos na prática observada.", "Ajustar apoio e dificuldade antes da próxima oportunidade."],
    ["Evidência de competência", "Competência exige comportamento e resultado em contexto. Um curso concluído indica estudo, mas não prova transferência para o trabalho.", "Uma pessoa concluiu uma formação de análise. Você quer atribuir decisões complexas, embora ainda não tenha observado como aplica os critérios em uma entrega.", "Separar conclusão do estudo de evidência de aplicação no contexto exigido.", "Propor uma análise delimitada com revisão do raciocínio antes de ampliar decisões.", "Tratar o certificado como prova suficiente para qualquer nível de autonomia.", "Qualidade do raciocínio e da análise em situações reais acompanhadas.", "Ampliar autonomia com evidências consistentes e revisar limites do contexto."],
    ["Diversificar experiências", "Desenvolvimento não se resume a mais tarefas do mesmo tipo. Escolha experiências que ampliem repertório sem dispersar foco e capacidade.", "A pessoa mais experiente recebe sempre a mesma demanda. Quer aprender articulação entre áreas, mas a agenda está completamente ocupada pelas rotinas atuais.", "Identificar competência desejada, oportunidade pertinente e capacidade necessária.", "Renegociar parte da rotina para uma colaboração delimitada entre áreas, com apoio e revisão.", "Adicionar a nova experiência à agenda cheia sem reduzir nenhum compromisso.", "Participação na articulação e manutenção de entregas compatíveis com a capacidade.", "Rever escopo quando a oportunidade virar acúmulo sem aprendizagem observável."],
    ["Revisão do desenvolvimento", "A revisão compara prática, apoio e efeito. Um resultado isolado não deve virar julgamento permanente sobre potencial ou personalidade.", "Uma apresentação não funcionou porque o público mudou de última hora. O plano previa outro perfil e a pessoa teve pouco tempo para adaptar o material.", "Distinguir preparo, adaptação e mudança de contexto na experiência.", "Revisar o que foi aplicado e preparar um ajuste para nova oportunidade comparável.", "Concluir que a pessoa não tem perfil para apresentações a partir desse encontro.", "Adaptação do material e compreensão do público em novas oportunidades.", "Recalibrar prática e apoio segundo o comportamento observado, sem rótulo permanente."],
  ] },
  { id: "sucessao", title: "Continuidade e sucessão responsável", skill: "Continuidade da equipe", description: "Reduza dependências e prepare transições de responsabilidade com critérios e cuidado.", lessons: [
    ["Dependências críticas", "Continuidade começa por tarefas e decisões que param na ausência de alguém. Mapeie conhecimento, acesso e autoridade, não apenas nomes de substitutos.", "Uma pessoa é a única que sabe fechar um processo mensal. Há instruções antigas, mas nenhuma outra pessoa possui acesso ou conhece as exceções.", "Identificar conhecimento, acessos e decisões necessários para o fechamento.", "Planejar transferência acompanhada e acessos autorizados antes da próxima ausência.", "Nomear um substituto e considerar a continuidade resolvida.", "Capacidade de realizar o fechamento com acesso adequado e apoio delimitado.", "Atualizar a cobertura quando exceções revelarem conhecimento ainda concentrado."],
    ["Critérios de prontidão", "Prontidão depende do papel e da evidência disponível. Bom desempenho atual não prova domínio de responsabilidades diferentes.", "A pessoa com maior resultado técnico é indicada para substituir uma liderança. Nunca conduziu conflitos nem distribuiu prioridades de equipe.", "Comparar responsabilidades do novo papel com evidências de experiência e lacunas.", "Planejar experiências acompanhadas nas novas responsabilidades antes de concluir prontidão.", "Considerar resultado técnico suficiente para assumir qualquer responsabilidade de liderança.", "Escolhas de prioridade, conversas e coordenação observadas em oportunidades pertinentes.", "Revisar a prontidão por responsabilidade, sem tratar todas as competências como equivalentes."],
    ["Transferência de conhecimento", "Transferir envolve explicar o raciocínio, observar a execução e registrar exceções. Um manual sem prática não verifica entendimento.", "Você pede a uma pessoa que documente uma rotina. O documento existe, mas quem recebeu ainda não executou e desconhece quando precisa escalar uma exceção.", "Distinguir disponibilidade do documento de capacidade de executar e reconhecer exceções.", "Realizar execução acompanhada, registrar dúvidas e definir escalonamento de exceções.", "Enviar o manual e transferir a responsabilidade sem oportunidade de prática.", "Execução correta e tratamento de exceções dentro dos limites combinados.", "Revisar o material segundo as dúvidas encontradas na prática."],
    ["Transição de autoridade", "Uma transição precisa comunicar quem decide, a partir de quando e com qual apoio. Dois responsáveis com ordens concorrentes deixam o time sem direção.", "A liderança anterior continua aprovando todas as decisões enquanto a nova pessoa assume formalmente. O time recebe orientações contraditórias de ambas.", "Identificar direitos de decisão ainda sobrepostos na transição.", "Combinar e comunicar a autoridade da nova pessoa e o papel de apoio da anterior.", "Manter duas aprovações para garantir segurança durante toda a transição.", "Decisões encaminhadas à pessoa responsável e redução de orientações concorrentes.", "Rever pontos específicos de apoio sem restabelecer uma autoridade paralela."],
    ["Transparência sem promessa", "Preparar sucessão não garante promoção. Explique critérios, oportunidades e limites do processo sem criar expectativa que não controla.", "Você oferece uma experiência de liderança e a pessoa pergunta se isso garante uma promoção. A decisão depende de vaga e aprovação de outra instância.", "Separar oportunidade de desenvolvimento da decisão formal de promoção.", "Explicar os critérios, a dependência e o que a experiência permitirá observar.", "Garantir a promoção para motivar a participação na experiência.", "Competências praticadas e entendimento dos limites do processo.", "Atualizar expectativas quando condições de vaga ou aprovação mudarem."],
  ] },
  { id: "desempenho", title: "Acompanhar desempenho com justiça", skill: "Critérios e desenvolvimento", description: "Converse sobre resultados, contexto e melhoria usando evidências e expectativas claras.", lessons: [
    ["Expectativas verificáveis", "Avaliação justa exige expectativas conhecidas e compatíveis com o papel. Critérios retroativos impedem a pessoa de orientar seu trabalho.", "Na revisão semestral, você cobra uma contribuição que nunca foi combinada. A pessoa cumpriu as entregas formais e não sabia da expectativa adicional.", "Identificar a diferença entre critério conhecido e expectativa introduzida depois.", "Avaliar pelos critérios acordados e negociar a nova contribuição para o próximo ciclo.", "Reduzir a avaliação atual por uma expectativa nunca comunicada.", "Entendimento dos critérios e evidências das contribuições pactuadas.", "Rever expectativas ao mudar o papel, comunicando a mudança antes da cobrança."],
    ["Evidência ao longo do ciclo", "Eventos recentes ou muito visíveis podem dominar a avaliação. Considere evidências do período completo e sua pertinência aos critérios.", "Uma pessoa teve uma falha na última semana, após meses de entregas consistentes. Você percebe que está resumindo todo o semestre a esse episódio.", "Examinar evidências de todo o período e a gravidade específica da falha recente.", "Avaliar o ciclo completo e tratar a falha com sua consequência e um acordo próprio.", "Definir toda a avaliação pelo último evento por ser mais fácil de lembrar.", "Resultados e comportamentos ao longo do ciclo, com contexto das ocorrências.", "Melhorar registros contínuos para reduzir dependência de memória na próxima revisão."],
    ["Contexto e responsabilidade", "Reconhecer contexto não elimina responsabilidade. Diferencie condições fora do controle, decisões possíveis e comunicação esperada diante de bloqueios.", "Uma entrega atrasou por um fornecedor. A pessoa não podia acelerar a entrega externa, mas sabia do risco há uma semana e não o sinalizou.", "Separar atraso externo da responsabilidade de comunicar o risco conhecido.", "Rever o impacto externo e combinar sinalização de bloqueios e alternativas sob controle da pessoa.", "Ignorar a comunicação tardia porque a causa principal foi externa.", "Sinalização tempestiva de riscos e ações possíveis no contexto.", "Ajustar o acordo de escalonamento quando faltarem condições para sinalizar."],
    ["Melhoria com condições viáveis", "Um acordo de melhoria precisa focar comportamentos, recursos e revisão. Metas impossíveis ou genéricas não orientam uma mudança verificável.", "Uma pessoa recebe o pedido de não errar mais. O processo tem orientações contraditórias e nenhuma etapa clara de revisão para tarefas novas.", "Identificar comportamentos a melhorar e obstáculos do processo.", "Esclarecer orientação, combinar uma verificação e revisar uma entrega específica.", "Exigir ausência total de erros sem alterar nenhuma condição do processo.", "Aplicação da verificação e tipos de erro nas entregas acompanhadas.", "Rever apoio e critérios se o mesmo problema persistir mesmo com o acordo aplicado."],
    ["Comparações e calibração", "Comparar exige papéis, escopo e condições equivalentes. Calibração discute evidências e critérios, sem transformar avaliação em competição entre pessoas.", "Duas pessoas têm volumes diferentes de entrega porque uma assume casos críticos mais longos. Um ranking bruto coloca a segunda no fim da lista.", "Examinar complexidade, responsabilidade e condições antes de comparar volumes.", "Avaliar cada papel pelos critérios pertinentes e discutir evidências equivalentes na calibração.", "Usar o mesmo volume bruto para classificar todo o grupo.", "Qualidade e resultados por escopo comparável, sem excluir casos críticos.", "Rever a comparação quando os critérios incentivarem evitar trabalho complexo."],
  ] },
  { id: "reconhecimento", title: "Reconhecer contribuições com intenção", skill: "Feedback positivo e colaboração", description: "Torne contribuições visíveis sem rankings arbitrários, exposição ou incentivos contraditórios.", lessons: [
    ["Especificidade no reconhecimento", "Reconhecimento útil descreve contribuição e efeito. Um adjetivo amplo não mostra o que vale repetir e pode criar expectativa de perfeição.", "Você elogia alguém como a estrela do time. A pessoa ajudou a organizar uma decisão complexa, mas o elogio não explica o comportamento que teve impacto.", "Identificar a ação que esclareceu a decisão e seu efeito no trabalho coletivo.", "Reconhecer a organização dos critérios e como ela permitiu escolher o próximo passo.", "Repetir que a pessoa é melhor que os colegas para reforçar a motivação.", "Compreensão da contribuição reconhecida e possibilidade de repetir o comportamento.", "Reformular o reconhecimento se ele criar comparação pessoal em vez de clareza."],
    ["Preferência e exposição", "A forma de reconhecer deve considerar a preferência da pessoa e o contexto. Visibilidade não justifica expor detalhes que ela não autorizou.", "Uma pessoa fez uma contribuição importante, mas diz que não gosta de homenagem pública. Você já havia pensado em um anúncio com sua história pessoal.", "Distinguir contribuição profissional da exposição pessoal e da preferência de formato.", "Combinar uma forma de reconhecimento que respeite a preferência e preserve informações pessoais.", "Fazer a homenagem mesmo assim porque reconhecimento público é sempre melhor.", "Reconhecimento recebido no formato combinado e limites de informação respeitados.", "Revisar o formato com a pessoa se a situação ou a preferência mudar."],
    ["Trabalho invisível", "Apoio, documentação e prevenção podem produzir valor sem alta visibilidade. Observe contribuições que sustentam resultados de outras pessoas.", "Quem apresenta a entrega recebe todo o crédito. Duas pessoas reduziram falhas e documentaram o processo, mas sua contribuição não aparece na reunião.", "Mapear o trabalho de apoio que tornou a entrega possível.", "Descrever as contribuições de prevenção e documentação junto à apresentação do resultado.", "Reconhecer apenas quem apresentou porque foi a contribuição mais visível.", "Contribuições de apoio identificadas com ação e efeito verificáveis.", "Ajustar o registro de entregas para que crédito acompanhe o trabalho realizado."],
    ["Critérios que orientam cultura", "O comportamento reconhecido comunica o que a organização valoriza. Premiar heroísmo recorrente pode reforçar processos que produzem urgências.", "O time celebra quem trabalhou de madrugada para resolver uma urgência evitável. Quem preveniu falhas e preservou o prazo não recebe destaque.", "Identificar qual comportamento o reconhecimento incentiva a repetir.", "Reconhecer a resposta necessária e também a prevenção, investigando a causa da urgência.", "Premiar sempre jornadas extras como principal sinal de compromisso.", "Prevenção de incidentes e resultados sustentáveis, além da resposta excepcional.", "Mudar critérios se o reconhecimento estimular urgências e sobrecarga repetidas."],
    ["Reconhecimento e feedback corretivo", "Reconhecer uma contribuição não impede tratar um comportamento que precisa mudar. Misturar elogio e cobrança vaga pode tornar os dois confusos.", "Uma pessoa fez uma boa análise, mas interrompeu colegas na apresentação. Você quer reconhecer o trabalho e conversar sobre participação sem anular nenhum tema.", "Separar qualidade da análise do comportamento observado na reunião.", "Reconhecer a análise e tratar as interrupções com exemplos e um acordo específico.", "Omitir as interrupções porque o resultado técnico foi bom.", "Qualidade da análise mantida e espaço de fala preservado nos próximos encontros.", "Revisar cada tema por sua evidência, evitando transformar elogio em cobrança implícita."],
  ] },
  { id: "crises", title: "Coordenação em momentos críticos", skill: "Crises e comunicação", description: "Coordene contenção, decisões e comunicação quando o risco aumenta e faltam informações.", lessons: [
    ["Contenção e investigação", "Conter o efeito e investigar a causa são frentes distintas. Uma resposta inicial reversível pode reduzir dano sem declarar uma explicação ainda não verificada.", "Um processo envia dados incorretos a clientes. A causa não está confirmada e continuar o envio amplia o problema enquanto a equipe investiga.", "Identificar o efeito que pode ser contido e a informação crítica para investigar.", "Suspender o envio afetado com responsável e revisão, investigando a causa em paralelo.", "Continuar o envio até ter certeza completa da causa.", "Interrupção do efeito e evidências verificadas na investigação.", "Revisar a contenção quando novas evidências alterarem o escopo afetado."],
    ["Papéis e decisão", "Sob pressão, autoridade e responsabilidades precisam ser claras. Várias ordens simultâneas podem ampliar risco e retrabalho.", "Três gestores dão instruções diferentes sobre uma falha. O time muda de direção a cada mensagem e ninguém consolida o estado da resposta.", "Identificar conflito de autoridade e ausência de coordenação da ocorrência.", "Definir coordenação, responsáveis por frentes e canal único de atualização da decisão.", "Permitir que cada gestor continue orientando separadamente para ganhar velocidade.", "Decisões coerentes, responsáveis identificados e atualização comum do estado.", "Ajustar papéis quando uma frente nova exigir outra autoridade, comunicando a mudança."],
    ["Comunicação com incerteza", "Uma atualização responsável distingue fato, ação, hipótese e próxima revisão. Silêncio ou certeza fabricada podem deteriorar confiança.", "O cliente exige previsão de retorno. Há contenção em andamento, mas a duração depende de uma verificação que ainda não foi concluída.", "Separar o que é conhecido da previsão que depende da verificação.", "Informar efeito conhecido, ação em curso e horário da próxima atualização, sem garantir prazo não validado.", "Prometer solução em uma hora para reduzir a ansiedade do cliente.", "Atualizações cumpridas e previsões identificadas com suas condições.", "Corrigir a previsão quando a verificação mudar o cenário, explicando a condição nova."],
    ["Capacidade durante a crise", "Uma crise muda prioridades, mas não cria capacidade ilimitada. Coordene turnos, cobertura e compromissos suspensos conforme regras da organização.", "A resposta crítica já dura muitas horas. As mesmas pessoas seguem atendendo projetos normais e começam a repetir verificações com erros.", "Identificar carga acumulada, cobertura disponível e trabalho que pode ser suspenso.", "Renegociar compromissos e organizar cobertura e pausas pelo fluxo da organização.", "Manter todos os projetos e pedir que as mesmas pessoas continuem até resolver tudo.", "Continuidade da resposta, qualidade das verificações e carga distribuída.", "Reorganizar a cobertura se erros e indisponibilidade comprometerem a contenção."],
    ["Revisão após a ocorrência", "Revisão busca mecanismos e melhorias verificáveis. Evite reduzir uma cadeia de condições à culpa de quem estava na última etapa.", "Uma falha foi resolvida e a equipe quer encerrar o assunto. O controle era ambíguo e duas etapas anteriores já continham sinais do problema.", "Reconstruir decisões, sinais e condições do processo sem presumir culpa individual.", "Definir ajustes de controle com responsável, prazo e verificação de eficácia.", "Culpar apenas quem executou a última etapa para demonstrar firmeza.", "Funcionamento dos controles ajustados e prevenção do mecanismo identificado.", "Rever a melhoria se o mesmo mecanismo reaparecer em outra etapa."],
  ] },
  { id: "etica", title: "Responsabilidade e decisões éticas", skill: "Critérios e integridade", description: "Reconheça conflitos de interesse, limites e encaminhamentos responsáveis na liderança.", lessons: [
    ["Conflito de interesse", "Um interesse pessoal pode comprometer a imparcialidade, mesmo sem intenção de favorecer alguém. Sinalize o conflito e siga o processo aplicável.", "Você participa da seleção de um fornecedor e descobre que uma pessoa próxima tem interesse financeiro em uma das propostas. Os critérios ainda serão avaliados.", "Identificar o interesse que pode afetar ou aparentar afetar a imparcialidade.", "Declarar o conflito e seguir o fluxo da organização para participação e decisão.", "Manter a relação em segredo porque você acredita conseguir decidir de forma justa.", "Critérios aplicados e tratamento do conflito conforme o procedimento autorizado.", "Atualizar a declaração se surgir outro vínculo relevante durante o processo."],
    ["Pressão por exceções", "Resultados não autorizam ignorar controles essenciais. Uma exceção deve ter autoridade, justificativa e limites pelo processo da organização.", "Uma entrega comercial importante depende de pular uma aprovação obrigatória. A pessoa solicitante diz que assumirá informalmente qualquer problema.", "Identificar o controle obrigatório e quem tem autoridade para avaliar uma exceção.", "Encaminhar a solicitação pelo fluxo autorizado e explicar o efeito no prazo.", "Ignorar a aprovação porque outra pessoa disse que assume a responsabilidade.", "Decisão autorizada, justificativa e limites registrados no fluxo aplicável.", "Rever o compromisso comercial se a exceção não for autorizada."],
    ["Relatos e encaminhamento", "Receber um relato exige escuta e encaminhamento adequado. Não prometa sigilo absoluto, investigue por conta própria ou exponha pessoas além do necessário.", "Uma pessoa relata conduta inadequada de um colega e pede que você não conte a ninguém. A organização possui um canal específico para tratar relatos.", "Identificar o encaminhamento previsto e os limites que você pode explicar sobre confidencialidade.", "Ouvir sem concluir culpa e orientar o encaminhamento pelo canal adequado, compartilhando apenas o necessário.", "Prometer segredo absoluto e conduzir uma investigação informal sozinho.", "Relato encaminhado com acesso adequado e sem conclusão precipitada.", "Buscar orientação autorizada se houver dúvida sobre proteção e próximo passo."],
    ["Critérios sob ambiguidade", "Uma situação ambígua exige explicitar pessoas afetadas, riscos e obrigações. Conveniência ou hábito não bastam para justificar uma escolha.", "Uma prática comum economiza tempo, mas prejudica um grupo de clientes que não participou da decisão. Não existe orientação clara para essa situação específica.", "Examinar impacto no grupo afetado e critérios e obrigações pertinentes à decisão.", "Consultar a instância adequada e comparar alternativas antes de manter a prática por hábito.", "Continuar porque a prática já era usada e nunca houve cobrança formal.", "Impactos avaliados e decisão fundamentada com os limites conhecidos.", "Reavaliar quando a consulta ou novas evidências mostrarem consequência não considerada."],
    ["Coerência entre fala e ação", "A conduta da liderança comunica critérios reais. Cobrar uma regra que você dispensa para si enfraquece sua aplicação e gera exceções implícitas.", "Você pede que o time registre mudanças de escopo, mas envia alterações diretas sem registro. As pessoas passam a tratar pedidos seus como exceções automáticas.", "Identificar a diferença entre regra declarada e comportamento da liderança.", "Registrar seus próprios pedidos e corrigir as exceções informais, mantendo o fluxo comum.", "Exigir registro apenas do time porque suas demandas são prioritárias.", "Mudanças registradas independentemente da posição de quem solicita.", "Rever o fluxo se a prioridade continuar servindo de justificativa para contornar o critério."],
  ] },
  { id: "privacidade", title: "Cuidado com informações de pessoas", skill: "Confidencialidade no trabalho", description: "Use somente informação necessária e respeite acesso, contexto e canais da organização.", lessons: [
    ["Necessidade e finalidade", "Antes de coletar informação de uma pessoa, defina a finalidade e o mínimo necessário. Curiosidade ou possibilidade técnica não tornam uma coleta pertinente.", "Para organizar cobertura de ausências, uma planilha pede detalhes médicos de todas as pessoas. O planejamento precisa apenas de disponibilidade e ajuste autorizado.", "Separar informação necessária à cobertura de detalhes sensíveis não pertinentes.", "Usar disponibilidade e ajustes autorizados, encaminhando informações sensíveis pelo fluxo próprio.", "Coletar todos os detalhes para que a liderança tenha uma visão completa.", "Cobertura organizada com o mínimo de informação e acesso compatível.", "Rever os campos coletados quando não contribuírem para a finalidade definida."],
    ["Acesso proporcional", "Permissão deve acompanhar a necessidade de trabalho. Compartilhar uma pasta ampla por facilidade pode expor registros de pessoas sem relação com a tarefa.", "Um parceiro precisa de dados de um projeto. A pasta compartilhada também contém registros individuais de feedback e conversas do time.", "Identificar quais arquivos são necessários ao parceiro e quais devem permanecer restritos.", "Compartilhar somente o material do projeto com permissão apropriada.", "Liberar a pasta inteira porque separar arquivos demora mais.", "Acesso ao material necessário sem exposição de registros individuais.", "Revisar permissões quando o trabalho do parceiro terminar ou mudar."],
    ["Contexto no compartilhamento", "Informação recebida em conversa privada não se torna pública por ajudar a explicar um atraso. Combine uso do relato e compartilhe só o necessário.", "Você quer explicar ao grupo por que uma pessoa mudou o prazo. Ela contou uma situação familiar em particular e não autorizou compartilhar os detalhes.", "Separar a justificativa operacional do relato privado que não precisa circular.", "Comunicar o novo acordo de prazo e cobertura sem expor os detalhes pessoais.", "Repetir a situação familiar para que o grupo compreenda e tenha empatia.", "Entendimento do novo acordo e preservação do contexto privado.", "Consultar a pessoa sobre qualquer uso adicional do relato antes de compartilhá-lo."],
    ["Agregação e identificação", "Um resumo agregado pode permitir identificação quando o grupo é pequeno ou os detalhes são únicos. Avalie contexto e regras da organização antes de divulgar.", "Um relatório de clima de três pessoas inclui cargos e falas específicas. Mesmo sem nome, é fácil reconhecer quem fez cada comentário.", "Identificar o risco de reconhecimento pelo tamanho do grupo e pelos detalhes.", "Aplicar os critérios de agregação e retirar detalhes identificáveis antes de divulgar um resumo permitido.", "Publicar todas as falas porque nenhum nome aparece no relatório.", "Resumo útil sem identificação desnecessária, conforme os critérios aplicáveis.", "Rever o recorte ou suspender divulgação se a identificação continuar provável."],
    ["Incidentes de informação", "Uma exposição precisa de contenção e comunicação pelo canal adequado. Apagar um arquivo não comprova que o acesso deixou de ter consequência.", "Um documento restrito foi enviado a um grupo errado. Você consegue remover o link, mas não sabe quem acessou ou baixou o conteúdo.", "Distinguir remoção do acesso de avaliação do que já foi exposto.", "Conter o acesso e informar o canal responsável com fatos conhecidos e incertezas.", "Apagar a mensagem e encerrar o assunto para evitar constrangimento.", "Acesso contido e incidente avaliado pelo procedimento da organização.", "Ajustar permissões e envio conforme o mecanismo identificado na avaliação."],
  ] },
  { id: "melhoria", title: "Melhoria contínua com evidências", skill: "Processos e aprendizagem", description: "Transforme problemas recorrentes em testes delimitados, sem confundir ação com melhoria.", lessons: [
    ["Problema e condição atual", "Um problema descreve a diferença entre esperado e observado. Nomear uma solução cedo demais pode impedir investigar o mecanismo da dificuldade.", "O time diz que precisa de uma reunião diária. O problema é uma sequência de devoluções por critérios de aceitação diferentes entre duas áreas.", "Definir o desvio observado antes de escolher a reunião como solução.", "Mapear motivos de devolução e alinhar critérios antes de testar um novo encontro.", "Criar a reunião diária e considerar o problema tratado.", "Devoluções por motivo e entendimento dos critérios entre as áreas.", "Rever a intervenção se a reunião aumentar sem reduzir o mecanismo das devoluções."],
    ["Causa e hipótese", "Perguntar por causas exige evidência de processo. Uma explicação provável deve ser testada, especialmente quando envolve julgamento sobre pessoas.", "Entregas saem com dados incorretos e o grupo conclui que falta atenção. Os campos mudaram recentemente e a referência de preenchimento está desatualizada.", "Examinar onde o erro surge e se a referência acompanha o campo atual.", "Testar a atualização da orientação e a verificação do campo antes de atribuir causa à atenção.", "Cobrar mais cuidado de todos sem examinar o processo.", "Erro por etapa antes e depois da referência atualizada.", "Buscar outra hipótese se o erro persistir mesmo com orientação correta aplicada."],
    ["Teste pequeno e verificável", "Um teste delimita hipótese, escopo, duração e decisão posterior. Alterar toda a operação antes de aprender amplia o custo de uma escolha equivocada.", "Uma proposta de nova triagem parece promissora, mas pode aumentar espera em casos urgentes. Você pode testá-la em uma fila pequena com cobertura.", "Identificar benefício esperado e risco que precisa ser observado no teste.", "Testar em fila delimitada com prazo, responsável e condição de interrupção para urgências.", "Aplicar a triagem em todas as filas e avaliar quando surgir tempo.", "Qualidade da triagem e espera dos casos urgentes durante o período.", "Interromper ou ajustar se o limite de risco acordado for ultrapassado."],
    ["Padronizar o que funcionou", "Um resultado favorável precisa de condições replicáveis. Padronização explica uso, responsabilidade e exceções, sem transformar o processo em regra cega.", "Um piloto reduziu devoluções porque tinha revisão por uma pessoa dedicada. A expansão proposta remove essa revisão, mas mantém a expectativa de ganho.", "Identificar a condição do piloto que sustentou o resultado.", "Verificar capacidade da revisão na expansão e definir exceções antes de padronizar.", "Copiar somente o formulário e prometer o mesmo efeito em escala.", "Resultado e condições mantidos em contextos da expansão.", "Adaptar o padrão quando a capacidade ou a complexidade do contexto mudar."],
    ["Sustentar e revisar", "Uma melhoria precisa de acompanhamento proporcional e dono do processo. Encerrar o projeto não elimina a necessidade de verificar desvio e mudança de contexto.", "Um fluxo melhorou por um mês, mas os responsáveis mudaram e novas exceções passaram a ser tratadas fora do acordo. Ninguém acompanha o indicador.", "Identificar perda de responsabilidade e exceções que alteraram o fluxo.", "Definir dono, revisão do indicador e tratamento das novas exceções.", "Declarar a melhoria permanente porque o primeiro mês foi positivo.", "Manutenção do efeito e uso do padrão com exceções registradas.", "Reabrir a hipótese quando o efeito deixar de se sustentar no contexto atual."],
  ] },
];

function question(id: string, lessonId: string, choice: Choice, scenario: string): StudyQuestion {
  const [prompt, answer, distractors, explanation] = choice;
  const correct = [...id].reduce((sum, char) => sum + char.charCodeAt(0), 0) % 4;
  const options: string[] = [...distractors]; options.splice(correct, 0, answer);
  return { id, lessonId, scenario, prompt, options, correct, explanation };
}

function buildLesson(courseId: string, brief: Brief, index: number) {
  const [title, concept, scenario, diagnosis, action, mistake, evidence, review] = brief;
  const id = `${courseId}-${index + 1}`;
  const guidance = `${concept} Neste caso, a análise precisa considerar: ${diagnosis} O encaminhamento indicado é: ${action} Não confunda rapidez da resposta com a qualidade da escolha. A alternativa de ${mistake.charAt(0).toLowerCase() + mistake.slice(1)} não trata o mecanismo descrito ou desrespeita uma condição do caso.`;
  const choices: [Choice, Choice, Choice, Choice] = [
    ["Qual análise deve orientar sua decisão neste caso?", diagnosis, ["Usar apenas a impressão inicial da liderança, sem verificar o contexto.", "Comparar as pessoas envolvidas antes de examinar as condições do trabalho.", "Considerar o pedido mais recente suficiente para redefinir todos os critérios."], `A análise pertinente é: ${diagnosis} ${concept}`],
    ["Qual encaminhamento atende ao problema e aos limites apresentados?", action, [mistake, "Adiar qualquer encaminhamento até que não exista nenhuma incerteza.", "Transferir a decisão inteira sem explicar contexto, limites ou responsabilidade."], `${action} Esse encaminhamento aplica o conceito da aula às condições do caso. ${concept}`],
    ["Que evidência permite acompanhar o efeito do encaminhamento?", evidence, ["Quantidade de mensagens trocadas sobre o tema, independentemente do efeito.", "Concordância imediata de todas as pessoas, sem observar execução.", "Ausência de novas perguntas, presumindo que silêncio comprova entendimento."], `A evidência deve mostrar ${evidence.charAt(0).toLowerCase() + evidence.slice(1)} Ela permite revisar o mecanismo do caso; volume de comunicação e impressão de concordância não comprovam o efeito.`],
    ["Qual revisão mantém a responsabilidade pelo resultado neste contexto?", review, [mistake, "Manter o encaminhamento inicial mesmo se novas evidências alterarem as condições.", "Trocar toda a solução pela primeira sugestão recebida, sem comparar critérios."], `${review} A revisão conecta a escolha às condições observadas, preservando critérios e responsabilidade em vez de defender a primeira decisão.`],
  ];
  const lesson: StudyLesson = {
    id, title, minutes: 5,
    sections: [
      { heading: "O conceito que orienta a escolha", text: concept },
      { heading: "Como investigar antes de agir", text: `${diagnosis} Comece separando o que foi observado da interpretação sobre suas causas. Verifique a informação que pode alterar a escolha com as pessoas que conhecem o trabalho. Explique qual decisão precisa ser tomada e quais condições não podem ser ignoradas. Uma investigação proporcional reduz conclusões precipitadas sem transformar toda dúvida em paralisia.` },
      { heading: "Do raciocínio ao encaminhamento", text: `${action} Torne explícitos o próximo passo, a pessoa responsável e o limite de sua autoridade. Confirme o entendimento com quem precisa executar e renegocie compromissos que a escolha afeta. Neste cenário, evite o atalho de ${mistake.charAt(0).toLowerCase() + mistake.slice(1)} O atalho não substitui a análise do problema e pode reforçar a condição que você precisa corrigir.` },
      { heading: "Evidências e revisão", text: `Acompanhe: ${evidence} Compare o observado ao critério acordado, considerando mudanças no contexto. Uma informação isolada pode orientar investigação, mas não representa toda a situação. Para revisar: ${review} Registre o ajuste e o motivo para que as pessoas não precisem adivinhar a nova regra.` },
      { heading: "Preparação para a prática", text: "Leia o caso abaixo e identifique a restrição que torna uma resposta aparentemente rápida inadequada. Compare análise, ação, evidência e revisão. Nos exercícios, escolha uma alternativa por questão; na correção, confira o raciocínio e volte ao conceito quando houver dúvida. A nota indica aprendizagem deste material e não mede a qualidade de uma pessoa como líder." },
    ],
    takeaways: [diagnosis, action, evidence, review], example: scenario,
    application: `Escolha uma situação equivalente no seu trabalho e prepare uma conversa sobre o encaminhamento: ${action} Use apenas informações que você pode acessar e compartilhar.`,
    activity: question(`a-${id}`, id, ["Qual princípio estudado deve orientar a leitura deste caso?", concept, ["A liderança deve escolher primeiro e definir os critérios somente depois de observar o resultado.", "Uma solução usada antes elimina a necessidade de investigar condições do contexto atual.", "O resultado pode ser considerado garantido se o grupo concordar com a intenção da proposta."], `O conceito da aula é: ${concept} Ele precisa ser aplicado ao contexto, não tratado como uma receita universal.`], scenario),
    additionalActivities: [
      question(`a-${id}-2`, id, ["Qual ação deve ser evitada neste caso, mesmo que pareça um atalho?", mistake, [diagnosis, action, review], `O atalho a evitar é: ${mistake} Compare essa ação ao princípio estudado: ${concept}`], scenario),
      question(`a-${id}-3`, id, ["Qual combinação de análise e acompanhamento tem relação com o problema observado?", `${diagnosis} Acompanhar: ${evidence}`, ["Escolher pela primeira impressão e acompanhar somente o número de mensagens enviadas.", "Usar a solução habitual e considerar a ausência de perguntas prova de que o problema foi resolvido.", "Priorizar a solicitação mais recente e avaliar sucesso apenas pela concordância na reunião."], `O diagnóstico e a evidência precisam corresponder ao mecanismo do caso. ${diagnosis} Acompanhe ${evidence.charAt(0).toLowerCase() + evidence.slice(1)}`], scenario),
    ],
    final: question(`f-${id}`, id, choices[3], scenario),
  };
  return { lesson, lab: { scenario, guidance, choices } };
}
const builtCourses = briefs.map((course, n) => ({ ...course, number: String(n + 9).padStart(2, "0"), built: course.lessons.map((brief, i) => buildLesson(course.id, brief, i)) }));
export const expandedLeadershipLabs = Object.fromEntries(builtCourses.flatMap(course => course.built.map(({ lesson, lab }) => [lesson.id, lab])));
const images = ["decision-discussion.webp", "communication-duo.webp", "intro-workshop.webp", "format-team-alt.webp"];
export const expandedStudyCourses: StudyCourse[] = builtCourses.map((course, index) => {
  const lessons = course.built.map(item => item.lesson);
  return { id: course.id, title: course.title, skill: course.skill, description: course.description, number: course.number,
    image: `/images/landing/${images[index % images.length]}`, lessons, transfer: lessons[4].final };
});
