import { additionalLessons, deepenExistingLesson, newStudyCourses } from "./academy-content";
import type { StudyCourse, StudyQuestion } from "./academy-types";
export type { StudyCourse, StudyLesson, StudyQuestion } from "./academy-types";
const q = (id: string, lessonId: string, prompt: string, options: string[], correct: number, explanation: string): StudyQuestion => ({ id, lessonId, prompt, options, correct, explanation });

// Conteúdo autoral de estudo. As notas avaliam conhecimento deste material,
// não a qualidade da liderança ou o desempenho profissional da pessoa.
const originalStudyCourses: StudyCourse[] = [
  { id: "decisoes", number: "01", title: "Decidir com clareza", skill: "Decisão e responsabilidade", description: "Organize critérios, reconheça riscos e revise escolhas sem esperar certeza absoluta.", image: "/images/landing/decision-discussion.webp", lessons: [
    { id: "criterios", title: "Critérios antes da escolha", minutes: 6, sections: [
      { heading: "Defina o que a decisão precisa atender", text: "Quando duas soluções parecem boas, a liderança precisa tornar explícito o que vai orientar a escolha. Comece pelo problema, pelo resultado esperado e pelas restrições reais. Separe critérios indispensáveis, como um prazo acordado ou um requisito de segurança, de preferências negociáveis. Compare as alternativas pelos mesmos critérios. Isso permite explicar a decisão e evita escolher primeiro para justificar depois." },
      { heading: "Diferencie fatos, suposições e preferências", text: "Um fato tem uma fonte verificável; uma suposição ainda precisa ser confirmada; uma preferência expressa o que alguém deseja. Registre essas diferenças ao discutir alternativas. Pergunte qual informação ausente pode mudar a decisão e quem consegue obtê-la. Nem toda dúvida exige uma nova reunião: priorize a informação que afeta um critério indispensável e defina um prazo para decidir." }
    ], takeaways: ["Comece pelo problema e pelo resultado esperado.", "Use os mesmos critérios para comparar alternativas.", "Identifique qual informação pode realmente mudar a escolha."], example: "Seu time precisa escolher entre duas ferramentas. Uma é mais conhecida, mas a outra atende ao requisito obrigatório de integração. A popularidade é uma preferência; a integração necessária é um critério indispensável. Verifique a integração antes de comparar as preferências de uso.", application: "Antes da próxima decisão, apresente o problema e dois critérios indispensáveis à equipe.", activity: q("a-criterios", "criterios", "Duas ferramentas estão em avaliação. O que deve orientar a comparação primeiro?", ["A preferência da pessoa mais experiente.", "O problema a resolver e os critérios indispensáveis.", "A opção com mais funcionalidades, independentemente da necessidade.", "A ferramenta que teve a apresentação mais convincente."], 1, "Os critérios precisam vir do problema e das restrições. Experiência e preferências podem contribuir, mas não substituem uma comparação pelos mesmos critérios."), final: q("f-criterios", "criterios", "Uma alternativa tem o visual preferido pelo time, mas não atende a um requisito obrigatório. Como avaliá-la?", ["A preferência coletiva substitui o requisito.", "O requisito pode ser ignorado para evitar conflito.", "Ela não atende ao critério indispensável; a preferência só entra depois.", "É impossível comparar duas alternativas."], 2, "Critérios indispensáveis delimitam as alternativas viáveis. Preferências ajudam a escolher entre opções que já atendem a esses critérios.") },
    { id: "reversibilidade", title: "Risco, prazo e reversibilidade", minutes: 6, sections: [
      { heading: "Nem toda decisão precisa do mesmo processo", text: "Uma escolha reversível permite testar, aprender e voltar atrás com um custo limitado. Uma escolha difícil de reverter exige mais cuidado com consequências, responsabilidades e pessoas afetadas. Antes de decidir, estime o impacto de um erro e o custo de desfazer a escolha. Ajuste a profundidade da análise ao risco; velocidade não é motivo para ignorar uma consequência grave." },
      { heading: "Desenhe um teste delimitado", text: "Para uma escolha reversível, proponha um piloto: defina o escopo, o tempo, a pessoa responsável e os sinais que permitirão avaliar o resultado. Combine o que faria o teste ser interrompido. Um piloto não é uma implementação definitiva escondida. Explique que a equipe está testando uma hipótese e reserve um momento de revisão antes de ampliar a mudança." }
    ], takeaways: ["Avalie o custo de desfazer uma decisão.", "Ajuste a análise à gravidade das consequências.", "Um piloto precisa de escopo, prazo, responsável e revisão."], example: "Antes de mudar a rotina de toda a empresa, teste uma nova pauta de reunião em um único time por duas semanas. Combine como observar a clareza das decisões, quem acompanhará o teste e quando a equipe decidirá se continua.", application: "Identifique uma mudança reversível e proponha um teste pequeno com revisão marcada.", activity: q("a-reversibilidade", "reversibilidade", "Você quer testar uma nova pauta de reunião. Qual piloto é mais bem definido?", ["Adotar a pauta em todos os times por tempo indeterminado.", "Testar sem explicar que é uma experiência.", "Mudar a pauta e observar quando houver tempo.", "Testar em um time por duas semanas, com responsável e revisão combinados."], 3, "O piloto delimita escopo, duração, acompanhamento e revisão. Assim, o time sabe o que está testando e quando a escolha será reavaliada."), final: q("f-reversibilidade", "reversibilidade", "Uma mudança tem consequências graves e é difícil de reverter. Qual postura segue a aula?", ["Aprofundar a análise e avaliar consequências e responsabilidades.", "Aplicar a mesma pressa de um teste pequeno.", "Delegar sem informar riscos.", "Decidir apenas pela opção mais rápida."], 0, "A análise deve acompanhar o risco e a reversibilidade. Consequências graves exigem mais cuidado antes da implementação.") },
    { id: "revisao", title: "Decidir também é acompanhar", minutes: 5, sections: [
      { heading: "Feche o acordo da decisão", text: "Uma decisão de reunião só vira ação quando as pessoas entendem o que foi escolhido e o que acontece depois. Registre a escolha, os critérios usados, a pessoa responsável, o próximo passo e a data de acompanhamento. Explique o que não está decidido para evitar interpretações diferentes. Dê espaço para que as pessoas apontem dúvidas de execução." },
      { heading: "Revise a escolha com evidências", text: "No acompanhamento, compare o que era esperado com o que foi observado. Separe o resultado do processo de decisão: uma escolha pode ter sido razoável com as informações disponíveis e ainda precisar de ajuste. Pergunte o que mudou e o que foi aprendido. Revisar não significa buscar um culpado nem defender a decisão a qualquer custo; significa decidir se é hora de manter, ajustar ou interromper." }
    ], takeaways: ["Toda decisão precisa de responsável e próximo passo.", "Combine a data de acompanhamento.", "Revise a escolha pelas evidências observadas."], example: "Depois de mudar a distribuição de atendimento, o time percebe um atraso que não era esperado. Na revisão, vocês comparam o prazo observado ao combinado, identificam um gargalo e ajustam a distribuição, em vez de discutir quem deveria ter previsto tudo.", application: "Na próxima reunião, encerre uma decisão dizendo quem fará o quê e quando haverá revisão.", activity: q("a-revisao", "revisao", "O resultado de uma decisão ficou abaixo do esperado. Qual é o melhor próximo passo?", ["Manter a decisão para preservar a autoridade.", "Procurar imediatamente alguém para responsabilizar.", "Comparar esperado e observado e decidir se é preciso ajustar.", "Trocar toda a estratégia sem analisar o que aconteceu."], 2, "A revisão usa evidências para entender o que mudou e orientar um ajuste. Ela não precisa transformar o erro em disputa por autoridade."), final: q("f-revisao", "revisao", "Ao encerrar uma reunião, qual acordo transforma a decisão em acompanhamento?", ["Apenas registrar que todos concordaram.", "Definir responsável, próximo passo e data de revisão.", "Pedir que alguém cuide disso quando puder.", "Listar todas as ideias, sem indicar a escolha."], 1, "Responsável, próximo passo e data de revisão tornam o acompanhamento concreto, além do registro da escolha e de seus critérios.") }
  ], transfer: q("a-decisao-caso", "reversibilidade", "Uma mudança pequena pode ser desfeita, mas falta uma informação que não altera nenhum critério indispensável. O que você pode propor?", ["Adiar indefinidamente até ter certeza total.", "Um teste delimitado, deixando explícita a suposição e a revisão.", "Implementar em toda a empresa sem acompanhamento.", "Ignorar qualquer dúvida e declarar a mudança definitiva."], 1, "Quando a escolha é reversível, um piloto com limites permite aprender. A suposição deve ser explícita, e riscos importantes continuam sendo considerados.") },
  { id: "comunicacao", number: "02", title: "Conversas que fazem avançar", skill: "Comunicação e feedback", description: "Escute com intenção e transforme feedback em acordos claros, sem rótulos pessoais.", image: "/images/landing/communication-duo.webp", lessons: [
    { id: "escuta", title: "Escutar antes de responder", minutes: 5, sections: [
      { heading: "Troque a resposta pronta por uma pergunta", text: "Em uma conversa de liderança, escutar envolve deixar a pessoa terminar e investigar o que você ainda não entendeu. Use perguntas abertas, como ‘o que dificultou a entrega?’ ou ‘como você percebeu essa situação?’. Evite perguntas que já contenham uma acusação. A intenção é conhecer a perspectiva da pessoa antes de definir uma orientação." },
      { heading: "Confirme o entendimento", text: "Depois de ouvir, resuma o que entendeu e pergunte se está correto. Essa confirmação reduz o risco de responder a um problema diferente do relatado. Reconhecer uma perspectiva não exige concordar com tudo. Você pode acolher a informação, explicar as restrições do trabalho e construir um próximo passo. Ao final, confirme o acordo em linguagem concreta." }
    ], takeaways: ["Deixe a pessoa terminar sua explicação.", "Use perguntas abertas, sem acusação embutida.", "Resuma e confirme antes de orientar."], example: "Uma pessoa diz que a entrega atrasou por dependências externas. Em vez de responder ‘você sempre traz desculpas’, pergunte quais dependências faltaram e resuma o que ouviu. Depois, combinem como sinalizar esse bloqueio mais cedo.", application: "Na próxima conversa individual, faça uma pergunta aberta e confirme o que entendeu antes de dar uma orientação.", activity: q("a-escuta", "escuta", "Uma pessoa relata uma dificuldade na entrega. Qual resposta favorece a escuta?", ["‘Por que você sempre se atrasa?’", "‘O que dificultou a entrega? Quero entender antes de combinarmos o próximo passo.’", "‘Já sei o que aconteceu, faça do meu jeito.’", "‘Não precisamos falar disso.’"], 1, "Uma pergunta aberta permite conhecer o contexto. O próximo passo pode ser combinado depois de confirmar o entendimento."), final: q("f-escuta", "escuta", "Você ouviu uma explicação, mas ainda não tem certeza de ter entendido. O que fazer?", ["Concordar para terminar rapidamente.", "Dar uma orientação baseada na primeira impressão.", "Pedir a outra pessoa que resolva sozinha.", "Resumir o que entendeu e perguntar se está correto."], 3, "Confirmar o entendimento evita orientar um problema diferente do relatado. Ouvir não obriga a concordar com todas as conclusões.") },
    { id: "feedback", title: "Feedback sem rótulos", minutes: 7, sections: [
      { heading: "Fale de um comportamento observável", text: "Um feedback útil descreve uma situação específica, o comportamento observado e seu impacto no trabalho. ‘Você é desorganizado’ é um rótulo; ‘na reunião de terça, o relatório não estava disponível e tivemos de adiar a decisão’ descreve o que aconteceu. Não atribua uma intenção que você não verificou. Abra espaço para ouvir a perspectiva da pessoa e entender o contexto." },
      { heading: "Construa um acordo de mudança", text: "Depois de explicar o impacto e ouvir, combine uma ação observável e um acompanhamento. Evite pedidos vagos, como ‘seja mais comprometido’. Pergunte o que pode ajudar e quais dificuldades precisam ser consideradas. Um acordo pode ser ‘enviar o relatório até a véspera e avisar antes se houver bloqueio’. O feedback inclui diálogo e responsabilidade; não termina apenas na exposição do problema." }
    ], takeaways: ["Descreva situação, comportamento e impacto.", "Evite rótulos e suposições sobre intenção.", "Combine uma ação e um momento de acompanhamento."], example: "Uma pessoa interrompeu colegas em uma reunião. Você descreve duas interrupções que observou, explica que ideias ficaram sem discussão e pergunta como ela percebeu o encontro. Combinam esperar a conclusão das falas e revisar isso na próxima reunião.", application: "Prepare um feedback substituindo um adjetivo por uma situação e um comportamento que você observou.", activity: q("a-feedback", "feedback", "Qual abertura de feedback usa um comportamento observável?", ["‘Você não se importa com o time.’", "‘Seu jeito é difícil.’", "‘Na reunião de ontem, duas falas foram interrompidas antes da conclusão.’", "‘Todo mundo acha que você precisa mudar.’"], 2, "A descrição localiza uma situação e um comportamento. Ela permite conversar sobre o impacto sem rotular a pessoa ou atribuir uma intenção."), final: q("f-feedback", "feedback", "Após ouvir um feedback, a pessoa pergunta o que precisa mudar. Qual acordo é mais concreto?", ["Enviar o relatório até a véspera e avisar antes se houver bloqueio, com revisão na semana seguinte.", "Ser mais comprometida com tudo.", "Mudar o jeito de ser imediatamente.", "Evitar qualquer erro no futuro."], 0, "O acordo descreve uma ação verificável, inclui como comunicar bloqueios e define um acompanhamento.") },
    { id: "acordos", title: "Divergências e acordos de trabalho", minutes: 6, sections: [
      { heading: "Separe posições de necessidades", text: "Em uma divergência, as posições são as soluções defendidas: ‘preciso de uma reunião’ ou ‘quero apenas mensagens’. As necessidades explicam o que cada pessoa busca, como clareza, rapidez ou tempo de concentração. Investigue essas necessidades antes de escolher um formato. Assim, vocês podem construir uma solução que não seja apenas a vitória de um lado." },
      { heading: "Torne o acordo verificável", text: "Um acordo de comunicação pode definir canal, prazo de resposta, assunto e regra de escalonamento. Por exemplo, use mensagem para atualizações de rotina e uma conversa curta para bloqueios que impedem a entrega. Combine quando revisar se esse arranjo está funcionando. Não trate silêncio como concordância automática: peça a confirmação das pessoas envolvidas e registre o que foi combinado." }
    ], takeaways: ["Pergunte qual necessidade está por trás da solução defendida.", "Defina canal, prazo e regra de escalonamento.", "Confirme o acordo e combine quando revisá-lo."], example: "Uma pessoa quer respostas imediatas; outra precisa de blocos de concentração. Vocês combinam duas janelas de resposta para a rotina e uma ligação para bloqueios urgentes, com revisão desse acordo após duas semanas.", application: "Revise um acordo do seu time: está claro qual canal usar e quando um bloqueio precisa ser escalado?", activity: q("a-acordos", "acordos", "Duas pessoas discordam sobre o canal de comunicação. Qual pergunta ajuda primeiro?", ["‘Qual necessidade cada formato precisa atender?’", "‘Quem tem mais tempo de empresa?’", "‘Qual de vocês vai abrir mão de tudo?’", "‘Por que vocês não concordam comigo?’"], 0, "Entender as necessidades permite desenhar um acordo que considere clareza, rapidez e concentração, em vez de apenas escolher um vencedor."), final: q("f-acordos", "acordos", "Qual é um acordo de comunicação verificável?", ["‘Precisamos nos comunicar melhor.’", "‘Todos devem estar disponíveis o tempo todo.’", "‘Rotina por mensagem, resposta até o fim da janela combinada e ligação para bloqueios urgentes.’", "‘Cada pessoa interpreta como preferir.’"], 2, "Canal, prazo e escalonamento tornam o acordo concreto. Ele ainda precisa de confirmação e revisão.") }
  ], transfer: q("a-conversa-caso", "feedback", "Um atraso se repete. Você quer conversar sem transformar o feedback em acusação. Qual sequência segue o módulo?", ["Rotular, cobrar silêncio e exigir mudança imediata.", "Evitar a conversa para preservar a relação.", "Ouvir apenas se a pessoa concordar com você.", "Descrever a situação e o impacto, ouvir o contexto e combinar uma ação com revisão."], 3, "A conversa combina evidência observável, escuta e responsabilidade pelo próximo passo, sem dispensar a necessidade de mudança.") },
  { id: "delegacao", number: "03", title: "Delegar para desenvolver", skill: "Autonomia e prioridades", description: "Compartilhe resultados esperados, estabeleça limites e acompanhe sem assumir tudo.", image: "/images/landing/intro-workshop.webp", lessons: [
    { id: "resultado", title: "Delegue um resultado, não só uma tarefa", minutes: 6, sections: [
      { heading: "Explique o resultado e o contexto", text: "Delegar exige mais do que repassar uma lista de tarefas. Explique o resultado esperado, por que ele importa, o prazo, os critérios de qualidade e os recursos disponíveis. Confirme o entendimento com a pessoa e ouça dúvidas sobre o escopo. Isso ajuda a distribuir responsabilidade sem deixar a equipe dependente de adivinhar o que você espera." },
      { heading: "Ajuste o apoio à situação", text: "A autonomia pode variar conforme a experiência da pessoa e o risco da entrega. Combine se ela deve trazer uma recomendação antes de agir, decidir dentro de limites acordados ou conduzir a entrega e informar os resultados. Esses níveis precisam ser explícitos. Pergunte que apoio será necessário, sem tomar de volta a tarefa ao primeiro sinal de dificuldade." }
    ], takeaways: ["Explique resultado, prazo, qualidade e recursos.", "Confirme o entendimento e as dúvidas de escopo.", "Combine a autonomia conforme experiência e risco."], example: "Ao delegar uma apresentação, explique que ela precisa apoiar uma decisão específica, indique os dados obrigatórios e combine uma revisão do rascunho. A pessoa escolhe a organização dos slides dentro desses limites.", application: "Na próxima delegação, peça à pessoa que resuma o resultado esperado e os limites combinados.", activity: q("a-resultado", "resultado", "Qual delegação está mais completa?", ["‘Faça uma apresentação bonita para depois.’", "‘Veja isso quando tiver tempo.’", "‘Prepare uma apresentação para esta decisão, com estes dados, até sexta; revisamos o rascunho na quarta.’", "‘Copie exatamente os meus slides, sem perguntas.’"], 2, "A delegação explicita finalidade, informações necessárias, prazo e acompanhamento, preservando espaço para escolhas na execução."), final: q("f-resultado", "resultado", "Uma pessoa assume uma entrega de alto risco e ainda está aprendendo. O que combinar?", ["Autonomia total sem apoio, em qualquer situação.", "Um nível de autonomia e apoio adequado ao risco e à experiência.", "Que ela não pode fazer nenhuma pergunta.", "Que você decidirá cada detalhe sem explicar o resultado."], 1, "Autonomia não precisa ser tudo ou nada. Combine limites, decisões e apoio de acordo com a experiência e o risco da entrega.") },
    { id: "acompanhamento", title: "Acompanhar sem microgerenciar", minutes: 5, sections: [
      { heading: "Defina pontos de acompanhamento", text: "Acompanhamento combinado dá previsibilidade. Defina quando conversar, o que será observado e em quais situações a pessoa precisa pedir apoio antes desse momento. Prefira observar critérios de resultado a controlar cada detalhe da execução. Quando houver um bloqueio, investigue o que precisa ser decidido e que apoio você pode oferecer." },
      { heading: "Evite devolver a responsabilidade para você", text: "Se a pessoa traz uma dificuldade, pergunte quais alternativas ela considera e qual recomenda. Você pode fornecer contexto, remover uma dependência ou negociar recursos sem fazer a tarefa no lugar dela. Se precisar intervir diretamente por risco relevante, explique a razão e renegocie o acordo. A intervenção não deve tornar os limites da delegação imprevisíveis." }
    ], takeaways: ["Combine checkpoints e situações de escalonamento.", "Observe resultado e bloqueios, não cada detalhe.", "Peça alternativas antes de assumir a tarefa."], example: "A pessoa relata que falta uma informação de outro setor. Você pergunta quais caminhos ela já considerou e ajuda a resolver a dependência. Ela continua responsável pela entrega e pelo próximo checkpoint.", application: "Troque uma cobrança surpresa por um checkpoint combinado com critérios claros.", activity: q("a-acompanhamento", "acompanhamento", "A pessoa encontra um bloqueio em uma tarefa delegada. Como apoiar sem assumir tudo?", ["Perguntar quais alternativas considera e ajudar a remover a dependência.", "Refazer a entrega inteira sem conversar.", "Cobrar atualizações a cada poucos minutos.", "Cancelar todos os checkpoints."], 0, "O apoio pode remover barreiras sem tirar a responsabilidade da pessoa. Alternativas e checkpoints mantêm o acordo de delegação."), final: q("f-acompanhamento", "acompanhamento", "O que distingue acompanhamento combinado de controle de cada detalhe?", ["A ausência de qualquer conversa sobre a entrega.", "Cobrar sem avisar, sempre que surgir uma dúvida.", "Aprovar cada mensagem que a pessoa envia.", "Observar critérios de resultado em checkpoints definidos e combinar quando pedir apoio."], 3, "Checkpoints e regras de escalonamento oferecem previsibilidade, enquanto os critérios de resultado preservam autonomia na execução.") },
    { id: "prioridades", title: "Prioridades que cabem na capacidade", minutes: 6, sections: [
      { heading: "Priorizar envolve uma escolha real", text: "Quando tudo recebe a mesma urgência, a equipe perde a referência do que vem primeiro. Compare as entregas pelo impacto, pelo prazo real, pelas dependências e pela capacidade disponível. Pergunte o que acontece se uma atividade for adiada. Diferencie prazo acordado de preferência por rapidez. Para incluir uma nova prioridade, explicite o que será adiado, reduzido ou renegociado." },
      { heading: "Renegocie antes de prometer", text: "Um limite bem comunicado informa o que é possível fazer, quais são as restrições e quais alternativas existem. Em vez de aceitar mais uma entrega sem discutir a capacidade, apresente opções: reduzir escopo, mudar prazo ou realocar apoio. Confirme a escolha com as pessoas afetadas. Dizer sim sem considerar a capacidade esconde a decisão de priorização até o problema aparecer." }
    ], takeaways: ["Compare impacto, prazo real, dependências e capacidade.", "Uma nova prioridade precisa de uma compensação explícita.", "Ofereça alternativas de escopo, prazo ou apoio."], example: "Chega uma entrega para amanhã, mas a equipe já está comprometida com um prazo crítico. Você apresenta dois caminhos: adiar a demanda existente ou reduzir o escopo da nova. A decisão é confirmada com quem depende das entregas.", application: "Ao receber uma nova urgência, explicite qual compromisso precisará ser renegociado.", activity: q("a-prioridades", "prioridades", "A equipe está no limite e chega uma nova prioridade. Qual ação é coerente com a aula?", ["Aceitar tudo e pedir esforço sem discutir capacidade.", "Apresentar alternativas e explicitar o que será adiado, reduzido ou renegociado.", "Chamar todas as entregas de urgentes.", "Ocultar o conflito até o prazo vencer."], 1, "Uma prioridade exige uma escolha sobre a capacidade. A compensação deve ser discutida e confirmada com as pessoas afetadas."), final: q("f-prioridades", "prioridades", "Qual resposta comunica um limite com alternativas?", ["‘Não faremos, sem discussão.’", "‘Podemos tudo, basta se dedicar.’", "‘Com a capacidade atual, podemos reduzir o escopo ou renegociar o prazo; qual opção atende melhor à necessidade?’", "‘Vou aceitar agora e pensar na capacidade depois.’"], 2, "A resposta informa a restrição e oferece alternativas concretas, tornando a escolha de priorização explícita.") }
  ], transfer: q("a-delegacao-caso", "resultado", "Você delegou uma entrega, mas recebe pedidos de aprovação para cada detalhe. O que revisar primeiro?", ["Se o resultado, os limites de autonomia e os checkpoints foram combinados claramente.", "Se a pessoa pode ser impedida de fazer perguntas.", "Se você consegue executar tudo sozinho.", "Se mais controle de mensagens vai resolver."], 0, "Dependência excessiva pode indicar falta de clareza sobre resultado e autonomia. Revise o acordo antes de aumentar o controle.") },
  { id: "equipe", number: "04", title: "Cultivar o desenvolvimento do time", skill: "Pessoas e aprendizagem", description: "Conduza conversas individuais e crie oportunidades de prática com acompanhamento.", image: "/images/landing/team-followup.webp", lessons: [
    { id: "individuais", title: "Conversas individuais com propósito", minutes: 6, sections: [
      { heading: "Reserve espaço para a perspectiva da pessoa", text: "Uma conversa individual pode tratar de dificuldades, apoio, relações de trabalho e desenvolvimento. Combine uma pauta, abra espaço para os temas da pessoa e evite transformar todo encontro em prestação de contas de tarefas. Pergunte o que está dificultando o trabalho, que apoio está faltando e que oportunidade de aprendizagem ela gostaria de experimentar." },
      { heading: "Encerre com poucos acordos", text: "Retome os pontos importantes e combine um ou dois próximos passos, com responsáveis e acompanhamento. Nem todo assunto precisa de solução imediata. Se você não puder atender a um pedido, explique a restrição e o que consegue encaminhar. Ao registrar a conversa, guarde apenas o necessário para acompanhar os acordos e considere a privacidade das informações compartilhadas." }
    ], takeaways: ["Inclua temas escolhidos pela pessoa.", "Converse sobre apoio e desenvolvimento, além de tarefas.", "Feche poucos acordos com responsabilidade e acompanhamento."], example: "Uma pessoa quer aprender a facilitar reuniões. Na conversa individual, vocês escolhem uma reunião de baixo risco para ela conduzir, combinam como se preparar e marcam um retorno depois da prática.", application: "Inclua na próxima conversa individual uma pergunta sobre uma oportunidade de desenvolvimento desejada pela pessoa.", activity: q("a-individuais", "individuais", "Qual pauta amplia uma conversa individual para além do status de tarefas?", ["Uma lista de cobranças sem espaço para perguntas.", "Somente os temas que a liderança escolheu.", "Repetir todas as informações da reunião de equipe.", "Temas da pessoa, dificuldades, apoio necessário e oportunidades de aprendizagem."], 3, "A conversa individual precisa de espaço para a perspectiva da pessoa e para temas de apoio e desenvolvimento, além das entregas."), final: q("f-individuais", "individuais", "Uma pessoa pede apoio que você não consegue oferecer imediatamente. Qual postura segue a aula?", ["Ignorar o pedido até a próxima conversa.", "Explicar a restrição, combinar o que pode ser encaminhado e acompanhar.", "Prometer mesmo sem possibilidade de cumprir.", "Transformar o pedido em uma falha da pessoa."], 1, "Clareza sobre a restrição e sobre o encaminhamento possível evita promessas vazias e preserva o acompanhamento.") },
    { id: "aprendizagem", title: "Desenvolvimento por uma prática possível", minutes: 6, sections: [
      { heading: "Traduza uma habilidade em ação", text: "Um objetivo como ‘melhorar a comunicação’ é amplo demais para orientar uma prática. Escolha um comportamento que possa ser tentado no trabalho: resumir uma decisão no encerramento da reunião ou fazer uma pergunta aberta antes de responder. Combine uma oportunidade adequada, o apoio necessário e como observar o que aconteceu. Comece por uma ação pequena, sem prometer que uma prática resolve tudo." },
      { heading: "Observe, aprenda e ajuste", text: "Depois da tentativa, conversem sobre a situação, a ação escolhida e o resultado observado. Pergunte o que ajudou e o que precisa mudar. Uma dificuldade não encerra o desenvolvimento: ela pode indicar que a ação precisa ser menor, que o contexto mudou ou que falta apoio. Escolha o próximo passo com base na experiência, em vez de apenas repetir o objetivo amplo." }
    ], takeaways: ["Transforme a habilidade em um comportamento observável.", "Escolha uma oportunidade com apoio e acompanhamento.", "Use o aprendizado para ajustar o próximo passo."], example: "Para praticar feedback, uma pessoa prepara uma situação, um comportamento e um impacto. Ela ensaia com você, conduz uma conversa de baixo risco e depois revisa o que aconteceu antes de escolher uma nova prática.", application: "Com uma pessoa do time, transforme um objetivo amplo em uma ação que possa ser observada nesta semana.", activity: q("a-aprendizagem", "aprendizagem", "Qual objetivo oferece uma prática observável de comunicação?", ["‘Resumir a decisão ao final da próxima reunião e confirmar o entendimento.’", "‘Ser perfeito em todas as conversas.’", "‘Ter mais perfil de liderança.’", "‘Melhorar tudo o mais rápido possível.’"], 0, "A ação é específica, tem uma oportunidade concreta e permite observar o que aconteceu, ao contrário de objetivos amplos ou absolutos."), final: q("f-aprendizagem", "aprendizagem", "Uma prática não teve o resultado esperado. Como continuar o desenvolvimento?", ["Encerrar o objetivo e evitar novas tentativas.", "Repetir a mesma ação sem considerar o contexto.", "Observar o que ajudou, o que faltou e ajustar o próximo passo.", "Concluir que a pessoa não tem potencial."], 2, "O acompanhamento transforma uma tentativa em aprendizagem. Ajustar ação, contexto ou apoio é parte do desenvolvimento.") },
    { id: "reconhecimento", title: "Reconhecer contribuições e ouvir sinais", minutes: 5, sections: [
      { heading: "Reconheça uma contribuição específica", text: "Reconhecimento útil nomeia uma ação e explica sua contribuição para o trabalho. ‘Seu resumo deixou a decisão clara para todos’ mostra o comportamento que ajudou. Evite comparações entre pessoas ou usar reconhecimento como substituto de condições adequadas de trabalho. Pergunte também como a pessoa prefere ser reconhecida; nem todo mundo deseja uma exposição pública." },
      { heading: "Investigue sinais sem adivinhar causas", text: "Um silêncio em uma reunião ou uma queda de participação pode ter diferentes explicações. Observe a situação, abra uma conversa e verifique a perspectiva da pessoa. Não transforme um sinal isolado em diagnóstico sobre motivação ou personalidade. Quando um assunto envolve o grupo, investigue padrões e combine um ajuste que possa ser acompanhado. Diferencie o que foi relatado da sua interpretação." }
    ], takeaways: ["Reconheça a ação e o impacto, sem comparar pessoas.", "Considere a preferência da pessoa sobre reconhecimento.", "Use sinais para abrir uma conversa, não para adivinhar causas."], example: "Uma pessoa que costumava participar ficou em silêncio em duas reuniões. Você descreve o que observou em uma conversa privada e pergunta como ela percebeu os encontros, em vez de anunciar que ela perdeu o interesse pelo trabalho.", application: "Reconheça uma contribuição específica e, ao observar um sinal de atenção, pergunte antes de concluir sua causa.", activity: q("a-reconhecimento", "reconhecimento", "Uma pessoa participou menos de duas reuniões. Qual é a interpretação adequada?", ["Ela certamente perdeu o interesse pelo trabalho.", "O sinal permite concluir uma característica de personalidade.", "A observação é um ponto de partida para conversar e entender o contexto.", "O silêncio deve ser usado para compará-la aos colegas."], 2, "Um sinal isolado não explica a causa. A conversa ajuda a separar observação, relato e interpretação."), final: q("f-reconhecimento", "reconhecimento", "Qual reconhecimento é específico e respeitoso?", ["‘Você é melhor que todos os colegas.’", "‘Você nunca deve errar depois deste elogio.’", "‘Vou expor sua contribuição publicamente mesmo que você não queira.’", "‘Seu resumo esclareceu a decisão; como você prefere que essa contribuição seja reconhecida?’"], 3, "O reconhecimento descreve ação e impacto e considera a preferência da pessoa, sem compará-la com os colegas.") }
  ], transfer: q("a-equipe-caso", "aprendizagem", "Após uma conversa individual, vocês querem desenvolver a facilitação de reuniões. Qual próximo passo é mais coerente?", ["Exigir melhora geral sem oportunidade de prática.", "Escolher uma reunião de baixo risco, preparar a pessoa e revisar depois o que aconteceu.", "Medir a capacidade por uma única impressão.", "Substituir o acompanhamento por um elogio genérico."], 1, "Uma oportunidade concreta, com apoio e revisão, conecta a conversa de desenvolvimento à prática observável.") }
];
export const studyCourses: StudyCourse[] = [
  ...originalStudyCourses.map(course => ({ ...course, lessons: [...course.lessons.map(deepenExistingLesson), ...additionalLessons[course.id]] })),
  ...newStudyCourses,
];
// Conjuntos históricos exatos: ampliar o material não invalida notas ou rascunhos salvos.
export const legacyStudyQuestionIds: Record<string, string[]> = Object.fromEntries([
  ...originalStudyCourses.map(course => [course.id, [...course.lessons.map(lesson => lesson.activity.id), course.transfer.id]]),
  ["avaliacao-final", originalStudyCourses.flatMap(course => course.lessons.map(lesson => lesson.final.id))],
]);
export const allStudyLessons = studyCourses.flatMap(course => course.lessons);
export const studyPractices = studyCourses.flatMap(course => course.lessons.flatMap(lesson => [lesson.activity, ...(lesson.additionalActivities || [])].map((question, index) => ({
  id: `pratica:${course.id}:${question.id}`, courseId: course.id, lessonId: lesson.id, question,
  title: `${lesson.title} · prática ${index + 1}`,
}))));
export const finalStudyQuestions = allStudyLessons.map(lesson => lesson.final);
export const FINAL_QUIZ_ID = "avaliacao-final";
export const PASSING_GRADE = 7;
export function studyQuiz(id: string) {
  if (id === FINAL_QUIZ_ID) return { id, title: "Avaliação final de liderança", questions: finalStudyQuestions, course: null, lessons: allStudyLessons, practice: false };
  const course = studyCourses.find(item => item.id === id);
  if (course) return { id, title: `Avaliação · ${course.title}`, questions: [...course.lessons.flatMap(lesson => [lesson.activity, ...(lesson.additionalActivities || [])]), course.transfer], course, lessons: course.lessons, practice: false };
  const practice = studyPractices.find(item => item.id === id);
  if (!practice) return null;
  const practiceCourse = studyCourses.find(item => item.id === practice.courseId)!;
  return { id, title: practice.title, questions: [practice.question], course: practiceCourse, lessons: practiceCourse.lessons.filter(lesson => lesson.id === practice.lessonId), practice: true };
}
