import type { StudyQuestion } from "./academy-types";
type FinalCase = [lessonId: string, scenario: string, prompt: string, answer: string, distractors: [string, string, string], rationale: string];
// Novos casos de transferência: diferentes dos casos usados nas práticas.
const cases: FinalCase[] = [
  ["criterios", "Uma área quer trocar de fornecedor para reduzir custo. A alternativa mais barata não demonstrou recuperação dos dados, requisito obrigatório. O contrato atual vence em dez dias.", "Qual encaminhamento combina prazo e qualidade da decisão?", "Definir teste de recuperação com prazo curto e uma alternativa viável se o requisito não for atendido.", ["Escolher o menor custo e testar recuperação após a contratação.", "Adiar toda decisão até eliminar qualquer dúvida sobre o fornecedor.", "Ponderar recuperação e desconto na mesma média, permitindo compensação."], "Requisito obrigatório não é compensado por preferência ou desconto. Prazo e alternativa de contingência permitem decidir sem ignorá-lo."],
  ["reversibilidade", "Um piloto com três clientes foi bom, mas ampliar exige integração irreversível e atender casos mais complexos. A liderança pede implantação imediata.", "O que a recomendação precisa distinguir?", "Evidência do piloto, limites de representatividade e risco do compromisso de ampliação.", ["A satisfação dos três clientes como validação de qualquer escala.", "A reversibilidade do piloto como prova de reversibilidade da integração.", "O sucesso do teste como motivo para retirar critérios de interrupção."], "A conclusão precisa respeitar amostra, contexto e reversibilidade. Um teste bom não elimina riscos de outro compromisso."],
  ["vieses", "A liderança prefere uma proposta e anuncia que ela é a mais promissora antes da análise. O grupo concorda, mas uma pessoa relata que uma dependência crítica não foi testada.", "Qual ação melhora a decisão?", "Verificar a dependência e colher contrapontos independentes antes de confirmar a escolha.", ["Confirmar pelo consenso e tratar a dependência depois.", "Pedir que o grupo vote de novo após ouvir uma defesa mais detalhada.", "Desconsiderar a objeção porque é uma opinião isolada."], "Consenso após anúncio da preferência não substitui verificação de risco. Contrapontos independentes podem alterar a decisão."],
  ["feedback", "Uma entrega veio incompleta e a pessoa diz que a prioridade mudou por pedido de outra área. O registro do pedido ainda não foi verificado; houve retrabalho.", "Qual conversa integra clareza e escuta?", "Descrever a entrega e o impacto, ouvir e verificar a mudança de prioridade antes de combinar prevenção.", ["Classificar a pessoa como pouco comprometida e reforçar o prazo.", "Aceitar a explicação e retirar qualquer responsabilidade pelo repasse.", "Aplicar um novo procedimento a toda a equipe antes de verificar o episódio."], "Fato, impacto, contexto e novo acordo precisam ser tratados juntos. Nem julgamento imediato nem aceitação automática investigam o problema."],
  ["acordos", "Duas áreas chamam toda solicitação de urgente. Resposta imediata interrompe trabalho crítico; resposta no fim do dia atrasa ocorrências relevantes.", "Qual acordo resolve a tensão de forma aplicável?", "Classificar urgência por consequência e prazo, definir canais e testar o entendimento com exemplos.", ["Estabelecer resposta imediata a tudo para padronizar.", "Eleger o canal preferido pela maioria sem distinguir demandas.", "Transferir a classificação para cada solicitante sem critério comum."], "O acordo precisa diferenciar tipos de necessidade e ser aplicado a exemplos reais, evitando uma regra única que piora um dos problemas."],
  ["conversa-dificil", "Uma discussão sobre escopo está tensa. Um pedido depende de outro gestor, e versões do acordo inicial divergem. A entrega precisa de um encaminhamento hoje.", "Qual compromisso é responsável?", "Delimitar o que pode ser feito hoje, verificar o acordo e combinar retomada e retorno sobre a aprovação externa.", ["Garantir a aprovação externa para reduzir a tensão.", "Suspender todo encaminhamento até obter consenso sobre o passado.", "Adotar a versão da liderança e exigir aceitação imediata."], "Clareza sobre fatos pendentes e decisões controláveis permite agir sem promessa externa ou certeza fabricada."],
  ["resultado", "Uma pessoa recebeu uma entrega importante com prazo e formato, mas sem saber o resultado esperado. Ela pede aprovação de todas as escolhas e você assume a execução.", "Qual ajuste trata a origem do problema?", "Clarificar resultado, critérios e limites de decisão e devolver a execução com marcos de acompanhamento.", ["Reduzir o prazo para aumentar foco.", "Aprovar cada etapa mais rapidamente até concluir.", "Retirar todo acompanhamento para estimular autonomia."], "Contexto e direitos de decisão precisam acompanhar a delegação. Controle mais rápido ou abandono não corrigem a falta de clareza."],
  ["distribuicao", "Uma entrega com parte crítica será usada para desenvolver uma pessoa. Quem a apoiará já tem a carga completa e continua responsável pelas tarefas antigas.", "Qual condição é necessária para a delegação funcionar?", "Delimitar a parte de aprendizagem, reservar capacidade de apoio e definir critérios da parte crítica.", ["Delegar tudo e pedir que as duas pessoas se organizem.", "Manter o apoio informal para não reduzir produtividade.", "Usar a oportunidade somente se a pessoa já puder executar sem ajuda."], "Desenvolvimento real precisa de oportunidade e apoio planejado, considerando risco e capacidade."],
  ["prioridades", "O time comporta duas entregas e uma nova demanda relevante surgiu. Nenhuma restrição de prazo foi alterada. A nova entrada exigiria interromper uma escolha anterior.", "Qual negociação torna o custo da escolha visível?", "Comparar impactos e explicitar qual entrega e compromisso seriam renegociados para a entrada.", ["Adicionar a demanda e distribuir pequenas partes entre todos.", "Priorizar a solicitação mais recente para reduzir pressão.", "Assumir a entrega adicional pessoalmente sem revisar compromissos."], "A entrada compete pela mesma capacidade. Tornar a troca explícita permite negociar prioridade sem prometer trabalho que não cabe."],
  ["aprendizagem", "Uma pessoa concluiu conteúdos sobre facilitação e conduziu um encontro. Houve participação, mas nenhum responsável pelas ações foi confirmado.", "Qual próximo passo demonstra desenvolvimento orientado por evidência?", "Praticar um fechamento com responsáveis e prazos, com observação e feedback na próxima reunião.", ["Considerar a competência concluída pela aula e participação.", "Indicar outra trilha inteira sem tratar a lacuna observada.", "Retirar a oportunidade porque o primeiro encontro não foi perfeito."], "A evidência identifica uma lacuna específica, que deve orientar a próxima prática apoiada."],
  ["reconhecimento", "O time entregou por esforço extraordinário recorrente. Um elogio público foi proposto como única resposta, e contribuições de bastidores não foram consideradas.", "Qual resposta é mais completa?", "Reconhecer contribuições e preferências de exposição e revisar capacidade e prioridades para evitar a sobrecarga recorrente.", ["Premiar somente quem apresentou ao cliente.", "Usar o elogio para manter o mesmo esforço nos próximos ciclos.", "Evitar reconhecimento porque as condições precisam mudar."], "Reconhecimento específico e ajuste de condições são complementares; elogio não substitui decisão de capacidade."],
  ["resultado-meta", "A iniciativa realizou todos os encontros e emitiu certificados. O objetivo era reduzir falhas no atendimento, mas ninguém definiu falha nem mediu a situação inicial.", "O que pode ser afirmado com os dados disponíveis?", "As atividades previstas ocorreram; ainda falta evidência consistente para afirmar melhora no atendimento.", ["O resultado foi alcançado porque todos foram certificados.", "O atendimento piorou porque não foi medido.", "A conclusão pode ser estimada a partir da presença."], "Execução de atividade não demonstra resultado. A falta de medida também não prova piora; é preciso construir acompanhamento consistente."],
  ["indicadores", "O volume entregue cresceu, mas retrabalho aumentou. A complexidade dos pedidos também mudou. Você precisa rever um incentivo sem atribuir automaticamente toda a piora a ele.", "Qual análise é mais responsável?", "Examinar qualidade, complexidade e comportamento incentivado, explicitando limites da comparação.", ["Concluir que o incentivo causou todo o retrabalho.", "Manter somente volume porque é o indicador comparável.", "Excluir pedidos complexos do relatório sem informar."], "Medidas complementares e contexto evitam causalidade indevida e mostram onde o incentivo pode ter efeito adverso."],
  ["dependencias", "Uma entrega depende de dados que outra área não consegue fornecer integralmente no prazo. O cliente espera sexta e o time ainda não negociou escopo mínimo.", "Qual encaminhamento coordena o resultado?", "Comparar escopo mínimo, capacidade e impacto no prazo com as áreas e comunicar um compromisso viável.", ["Confirmar sexta e cobrar mais frequência da outra área.", "Esperar o vencimento para informar o cliente.", "Transferir a responsabilidade inteira para quem fornece os dados."], "Coordenação trabalha alternativas e compromissos entre interfaces, sem garantir prazo que depende de um acordo ainda inexistente."],
  ["confianca", "Você descumpriu um retorno e a pessoa foi prejudicada. O contexto explica o atraso, mas o compromisso não foi renegociado. Ela precisa de uma resposta que depende de dados externos.", "Como reparar sem criar uma nova promessa frágil?", "Reconhecer impacto, informar o que já sabe, combinar um retorno viável e sinalizar antecipadamente qualquer impedimento.", ["Garantir uma solução completa hoje para compensar.", "Explicar a urgência e aguardar que a pessoa cobre novamente.", "Dizer que nada poderia ter sido feito porque os dados eram externos."], "Reparação une responsabilidade e compromisso controlável. Contexto não elimina o acordo, e compensação não autoriza promessa impossível."],
  ["facilitar-acordo", "Duas propostas viáveis competem por um recurso. Você deve decidir a prioridade estratégica. Depois de ouvir, uma pessoa continua discordando do critério escolhido.", "Qual fechamento é coerente com participação e responsabilidade?", "Explicar a escolha, registrar a objeção e confirmar execução e condição de revisão.", ["Exigir que a pessoa declare concordância para executar.", "Reabrir a decisão até atingir unanimidade.", "Ignorar a objeção por não ser da pessoa que decide."], "Consulta exige consideração e devolutiva, não unanimidade. Decisão clara pode manter discordância registrada e revisão."],
  ["inclusao", "A equipe anuncia oportunidades abertas, mas escolhe sempre quem se oferece primeiro. Quem precisa preparar uma contribuição raramente participa.", "Qual mudança cria acesso mais verificável?", "Explicitar critérios, oferecer preparação e formas de contribuição e acompanhar a distribuição das oportunidades.", ["Manter a seleção por rapidez porque a oferta era aberta.", "Escolher uma pessoa nova uma única vez e considerar resolvido.", "Exigir o mesmo modo de participação para todos."], "Abertura formal não elimina barreiras do processo. Critérios e condições de participação precisam ser observados ao longo do tempo."],
  ["piloto-mudanca", "O piloto reduziu prazo em casos simples, mas qualidade não foi medida. Os casos complexos não participaram. O custo de ampliar será difícil de reverter.", "Qual recomendação respeita a evidência?", "Limitar a conclusão aos casos testados e verificar qualidade e risco antes de ampliar.", ["Ampliar porque o prazo principal melhorou.", "Usar adesão ao treinamento para inferir qualidade.", "Desconsiderar o piloto por não cobrir todas as situações."], "A evidência parcial tem utilidade dentro de seus limites. Qualidade, representatividade e compromisso de escala exigem análise adicional."],
  ["adocao", "O novo processo tem presença alta em treinamento, mas aplicação baixa. O sistema falha em um turno e parte do time não sabe quando usar a nova regra.", "Qual ação combina suporte e avaliação da adoção?", "Corrigir a barreira, esclarecer situações de uso e observar aplicação adequada e erros por turno.", ["Reaplicar o mesmo treinamento a todos e considerar concluído.", "Classificar a aplicação baixa como falta de interesse.", "Usar certificados como único indicador de implantação."], "Adoção depende de compreensão e condições reais. A análise precisa medir uso adequado e qualidade, não exposição ao conteúdo."],
  ["plano-lider", "Você testou delegar uma entrega com novos limites. A pessoa tomou decisões melhores, mas uma dependência externa atrasou o resultado. O próximo ciclo ainda precisa ser escolhido.", "Qual revisão usa as evidências sem julgamento excessivo?", "Examinar autonomia e critérios atendidos, tratar a dependência e decidir o próximo ajuste de prática.", ["Concluir que a delegação falhou porque houve atraso.", "Concluir que a liderança inteira evoluiu a partir de uma entrega.", "Escolher outro tema sem revisar o teste anterior."], "Aprendizagem exige distinguir mecanismo da prática, resultado e contexto. Um episódio não diagnostica a liderança inteira."],
];
export const advancedFinalQuestions: StudyQuestion[] = cases.map(([lessonId, scenario, prompt, answer, distractors, explanation], index) => {
  const correct = (index * 3 + 1) % 4;
  const options: string[] = [...distractors]; options.splice(correct, 0, answer);
  return { id: `final-v2:${index + 1}`, lessonId, scenario, prompt, options, correct, explanation };
});
