"use client";

import { useState } from "react";
import { ArrowRight, Check, CheckCircle2, Clock3, Copy, Link2, MessageCircleMore, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { communicationTopics } from "@/lib/experiences";
import { comparePreferences } from "@/lib/results";

export type CommunicationPair={id:string;partnerEmail:string;creatorName:string;partnerName:string|null;isCreator:boolean;answered:boolean;creatorAnswered:boolean;partnerAnswered:boolean;ready:boolean;preferences?:number[][];agreement?:string;createdAt:string;inviteToken?:string;inviteExpiresAt?:string};
export type CommunicationCandidate={id:string;name:string;email:string};
export type CommunicationInvite={token:string;reference_id:string;created_at?:string};
type Send=(action:string,payload:Record<string,unknown>)=>Promise<{id?:string;link?:string}|null>;
type Props={pairs:CommunicationPair[];candidates:CommunicationCandidate[];invites:CommunicationInvite[];requestToken?:string;companyId:string;busy:boolean;send:Send;onInvitationAnswered:()=>void};
const emptyAnswers=()=>Array(communicationTopics.length).fill(-1) as number[];
const validEmail=(value:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim());
const shortDate=(value:string)=>new Date(value).toLocaleDateString("pt-BR",{day:"2-digit",month:"short",year:"numeric"});

function Questions({answers,onChange}:{answers:number[];onChange:(next:number[])=>void}){
  return <div className="comm-questions">{communicationTopics.map((topic,index)=><fieldset className="comm-question" key={topic.label}><legend><span>{String(index+1).padStart(2,"0")}</span>{topic.label}</legend><p>No trabalho, prefiro...</p><RadioGroup aria-label={topic.label} value={answers[index]<0?"":String(answers[index])} onValueChange={value=>onChange(answers.map((item,i)=>i===index?Number(value):item))} className="comm-options">{topic.options.map((option,i)=><label key={option} className="comm-option"><RadioGroupItem value={String(i)}/><span>{option}</span></label>)}</RadioGroup></fieldset>)}</div>;
}

function ResponseForm({title,partner,busy,onSubmit}:{title:string;partner:string;busy:boolean;onSubmit:(answers:number[])=>Promise<boolean>}){
  const [answers,setAnswers]=useState(emptyAnswers),[consent,setConsent]=useState(false);
  const complete=answers.every(answer=>answer>=0);
  return <div className="comm-response-form"><span className="kicker">SUA RESPOSTA</span><h3>{title}</h3><p>Responda pelo seu jeito de trabalhar. {partner} responde separadamente. Nenhuma escolha aparece para a outra pessoa antes que ambas concluam.</p><Questions answers={answers} onChange={setAnswers}/><label className="comm-consent"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/><span>Concordo em compartilhar minhas preferências com esta pessoa e com o administrador master quando as duas respostas estiverem prontas.</span></label><Button className="app-primary" disabled={busy||!complete||!consent} onClick={async()=>{if(await onSubmit(answers)){setAnswers(emptyAnswers());setConsent(false)}}}>Concluir minha resposta <ArrowRight size={16}/></Button><small>{answers.filter(answer=>answer>=0).length} de {answers.length} respostas preenchidas</small></div>;
}

export default function CommunicationExperience({pairs,candidates,invites,requestToken,companyId,busy,send,onInvitationAnswered}:Props){
  const [selectedPerson,setSelectedPerson]=useState(""),[external,setExternal]=useState(false),[email,setEmail]=useState(""),[activePairId,setActivePairId]=useState(()=>typeof window==="undefined"?"":new URLSearchParams(window.location.search).get("pair")||""),[activeToken,setActiveToken]=useState(requestToken||""),[agreements,setAgreements]=useState<Record<string,string>>({}),[copied,setCopied]=useState("");
  const currentToken=activeToken||requestToken||"";
  const pending=pairs.filter(pair=>!pair.ready),completed=pairs.filter(pair=>pair.ready);
  const inviteByEmail=external||candidates.length===0;
  const activeInvite=invites.find(invite=>invite.token===currentToken);
  const invitedPair=pairs.find(pair=>pair.id===activeInvite?.reference_id);
  async function createPair(){const result=await send("create_communication",inviteByEmail?{email:email.trim()}:{partnerId:selectedPerson});if(result?.id){setActivePairId(result.id);setSelectedPerson("");setEmail("");window.requestAnimationFrame(()=>document.getElementById(`dupla-${result.id}`)?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"center"}))}}
  async function answerPair(pairId:string,answers:number[]){const result=await send("respond_communication",{pairId,preferences:answers,consent:true});if(result){setActivePairId("");return true}return false}
  async function answerInvite(answers:number[]){const result=await send("respond_communication",{token:currentToken,preferences:answers,consent:true});if(result){setActiveToken("");onInvitationAnswered();return true}return false}
  async function copyPairLink(pair:CommunicationPair){const url=pair.inviteToken?`${window.location.origin}/app?invite=${encodeURIComponent(pair.inviteToken)}`:`${window.location.origin}/app?company=${encodeURIComponent(companyId)}&view=communication&pair=${encodeURIComponent(pair.id)}`;try{await navigator.clipboard.writeText(url);setCopied(pair.id);window.setTimeout(()=>setCopied(""),2500)}catch{window.prompt("Copie o link da dupla:",url)}}
  const answerCount=(pair:CommunicationPair)=>Number(pair.creatorAnswered)+Number(pair.partnerAnswered);
  return <div className="comm-experience">
    <header className="comm-intro"><div><span className="kicker">RAIO X DA COMUNICAÇÃO · EM DUPLA</span><h1>Uma conversa começa com duas perspectivas<span>.</span></h1><p>Escolha alguém, respondam separadamente e descubram onde as preferências se encontram. A comparação aparece quando as duas pessoas terminarem.</p></div><div className="comm-intro-mark" aria-hidden="true"><span>EU</span><i/><span>VOCÊ</span></div></header>
    {currentToken&&<section className="comm-panel comm-invite-panel"><div className="comm-panel-heading"><span className="kicker">CONVITE RECEBIDO</span><h2>{invitedPair?`${invitedPair.creatorName} quer conversar com você.`:"Você foi convidado para uma dupla."}</h2><p>Responda no seu tempo. A outra pessoa só verá a comparação quando ambas concluírem.</p></div><ResponseForm title="Como você prefere se comunicar?" partner="A outra pessoa" busy={busy} onSubmit={answerInvite}/></section>}
    {!currentToken&&invites.length>0&&<section className="comm-panel comm-incoming"><div className="comm-panel-heading"><span className="kicker">CONVITES RECEBIDOS</span><h2>{invites.length===1?"Uma pessoa quer comparar com você.":`${invites.length} pessoas querem comparar com você.`}</h2><p>Você pode responder agora ou voltar depois.</p></div><div className="comm-incoming-actions">{invites.map(invite=><Button variant="outline" key={invite.token} onClick={()=>setActiveToken(invite.token)}>Abrir convite <ArrowRight size={16}/></Button>)}</div></section>}
    <section className="comm-panel comm-create"><div className="comm-panel-heading"><span className="kicker">NOVA DUPLA</span><h2>Com quem você quer fazer esta experiência?</h2><p>{candidates.length?"Escolha uma pessoa do seu espaço. A dupla aparecerá para ela quando entrar no Synky Líderes.":"Ainda não há outra pessoa neste espaço. Informe um e-mail para convidar alguém."}</p></div>{candidates.length>0&&!external&&<div className="comm-people" role="group" aria-label="Pessoas do seu espaço">{candidates.map(person=><button type="button" key={person.id} aria-pressed={selectedPerson===person.id} className={selectedPerson===person.id?"selected":""} onClick={()=>setSelectedPerson(person.id)}><span className="comm-avatar">{person.name.trim().charAt(0).toUpperCase()||"?"}</span><span><strong>{person.name}</strong>{!person.email.endsWith("@visitor.synky.local")&&<small>{person.email}</small>}</span><Check size={17}/></button>)}</div>}{inviteByEmail&&<label className="field-label">E-mail da pessoa<Input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="pessoa@empresa.com"/></label>}<div className="comm-create-actions"><Button className="app-primary" disabled={busy||(!inviteByEmail&&!selectedPerson)||(inviteByEmail&&!validEmail(email))} onClick={createPair}>Criar dupla <ArrowRight size={16}/></Button>{candidates.length>0&&<button type="button" className="comm-text-button" onClick={()=>{setExternal(value=>!value);setSelectedPerson("");setEmail("")}}>{external?"Escolher alguém do espaço":"Convidar outra pessoa por e-mail"}</button>}</div>{inviteByEmail&&<p className="comm-help">Após criar a dupla, copie o link para a pessoa entrar no espaço e responder. O link vale por 14 dias.</p>}</section>
    <section className="comm-list" aria-label="Suas duplas"><div className="comm-list-heading"><div><span className="kicker">ACOMPANHAMENTO</span><h2>Suas duplas</h2></div><span>{pending.length} em andamento · {completed.length} concluída{completed.length===1?"":"s"}</span></div>{pending.length===0&&completed.length===0&&<div className="comm-empty"><UsersRound size={24}/><h3>Sua primeira dupla começa aqui.</h3><p>Escolha uma pessoa acima para abrir uma comparação. Cada um responde no seu tempo.</p></div>}
      {[...pending,...completed].map(pair=>{const other=pair.isCreator?pair.partnerName||pair.partnerEmail:pair.creatorName;const count=answerCount(pair);const comparisons=pair.ready&&pair.preferences?.length===2?comparePreferences(pair.preferences[0],pair.preferences[1]):null;return <article className="comm-pair" id={`dupla-${pair.id}`} key={pair.id}><div className="comm-pair-heading"><div className="comm-pair-icon"><MessageCircleMore size={21}/></div><div><span className="kicker">{pair.ready?"COMPARAÇÃO PRONTA":pair.isCreator?"DUPLA CRIADA":"CONVITE PARA VOCÊ"}</span><h3>Você e {other}</h3><small>Iniciada em {shortDate(pair.createdAt)}</small></div><span className={`comm-status ${pair.ready?"ready":count===1?"half":""}`}>{pair.ready?"Pronta":`${count} de 2 respostas`}</span></div><div className="comm-participants"><div><span className={pair.answered?"done":""}>{pair.answered?<CheckCircle2 size={17}/>:<Clock3 size={17}/>}</span><strong>Você</strong><small>{pair.answered?"Respondeu":"Ainda não respondeu"}</small></div><div><span className={pair.isCreator?pair.partnerAnswered?"done":"":pair.creatorAnswered?"done":""}>{pair.isCreator?pair.partnerAnswered?<CheckCircle2 size={17}/>:<Clock3 size={17}/>:pair.creatorAnswered?<CheckCircle2 size={17}/>:<Clock3 size={17}/>}</span><strong>{other}</strong><small>{pair.isCreator?pair.partnerAnswered?"Respondeu":"Ainda não respondeu":pair.creatorAnswered?"Respondeu":"Ainda não respondeu"}</small></div></div>
        {!pair.ready&&<p className="comm-waiting" role="status">{count===0?"Ninguém respondeu ainda. Cada pessoa pode começar quando quiser.":"Somente uma pessoa respondeu por enquanto. A comparação ficará disponível quando a outra terminar."}</p>}
        {!pair.ready&&!pair.answered&&activePairId===pair.id&&<ResponseForm key={pair.id} title="Agora é a sua vez" partner={other} busy={busy} onSubmit={answers=>answerPair(pair.id,answers)}/>}
        {comparisons&&<div className="comm-result"><div className="comm-result-heading"><div><span className="kicker">COMPARAÇÃO DA DUPLA</span><h4>Onde vocês se encontram</h4></div><span>{comparisons.filter(item=>item.match).length} de {comparisons.length} preferências em comum</span></div><div className="comm-results">{communicationTopics.map((topic,index)=>{const item=comparisons[index];return <div key={topic.label}><span className={item.match?"match":"difference"}>{item.match?"Em sintonia":"Vale conversar"}</span><b>{topic.label}</b><p>{pair.creatorName}: {topic.options[item.first??0]}</p><p>{pair.partnerName||pair.partnerEmail}: {topic.options[item.second??0]}</p></div>})}</div><p className="conversation-prompt">Para a próxima conversa: “Como podemos combinar pedidos, prazos e feedback para trabalhar melhor juntos?”</p><label className="field-label">Acordo prático da dupla<Textarea value={agreements[pair.id]??pair.agreement??""} onChange={event=>setAgreements({...agreements,[pair.id]:event.target.value})} placeholder="Ex.: confirmar mudanças de prazo por escrito após a conversa" maxLength={600}/></label><Button variant="outline" disabled={busy||!(agreements[pair.id]??pair.agreement??"").trim()} onClick={async()=>{if(await send("save_agreement",{pairId:pair.id,agreement:agreements[pair.id]??pair.agreement}))setAgreements(current=>{const next={...current};delete next[pair.id];return next})}}>Salvar acordo para a dupla</Button></div>}
        <div className="comm-pair-actions">{!pair.ready&&!pair.answered&&<Button className="app-primary" onClick={()=>setActivePairId(activePairId===pair.id?"":pair.id)}>{activePairId===pair.id?"Fechar perguntas":"Responder agora"} <ArrowRight size={15}/></Button>}{!pair.ready&&pair.isCreator&&<Button variant="outline" onClick={()=>pair.inviteToken||pair.partnerName?copyPairLink(pair):void send("renew_communication_invite",{pairId:pair.id})}><Copy size={15}/>{copied===pair.id?"Link copiado":pair.inviteToken||pair.partnerName?"Copiar link":"Gerar novo link"}</Button>}{!pair.ready&&pair.answered&&<span className="comm-pair-note"><CheckCircle2 size={16}/> Sua parte está concluída.</span>}<Button variant="ghost" disabled={busy} onClick={()=>{if(window.confirm("Remover esta dupla para as duas pessoas? As respostas e o acordo serão apagados definitivamente."))void send("remove_communication",{pairId:pair.id})}}>Remover dupla</Button></div>
      </article>})}
    </section>
    <div className="comm-privacy"><Link2 size={16}/><span>Cada resposta fica reservada até as duas pessoas concluírem e autorizarem a comparação. O acordo salvo aparece para ambas e no relatório do administrador master.</span></div>
  </div>;
}
