"use client";
import { useId, type ReactNode } from "react";
import { ArrowRight, Leaf, LockKeyhole } from "lucide-react";
import { LeaderCover, type LeaderVisual } from "./leader-visuals";
import type { JourneyView, PersonalJourney, Rating } from "./journey-model";

export const journeyLabels: Record<JourneyView, string> = { overview: "Dashboard", starting: "Meu ponto de partida", diagnosis: "Diagnóstico de desenvolvimento", plan: "Plano de prática", exercises: "Exercícios e reflexões", journal: "Diário de prática", review: "Revisão de progresso" };
export const statusLabels = { draft: "Em construção", active: "Em prática", paused: "Em pausa", completed: "Ciclo concluído" };
export type JourneyPageProps = { journey: PersonalJourney; update: (change: (value: PersonalJourney) => PersonalJourney) => void; navigate: (view: JourneyView) => void; announce: (message: string) => void };
export function JTitle({ eyebrow, title, children, visual }: { eyebrow: string; title: string; children?: ReactNode; visual?: LeaderVisual }) { if (visual) return <LeaderCover visual={visual} eyebrow={eyebrow} title={title}>{children}</LeaderCover>; return <header className="j-page-title"><span className="j-eyebrow">{eyebrow}</span><h1>{title}</h1>{children && <p>{children}</p>}</header>; }
export function JButton({ children, onClick, secondary = false, disabled = false, type = "button" }: { children: ReactNode; onClick?: () => void; secondary?: boolean; disabled?: boolean; type?: "button" | "submit" }) { return <button type={type} className={secondary ? "j-button secondary" : "j-button"} disabled={disabled} onClick={onClick}>{children}</button>; }
export function JText({ label, value, onChange, hint, maxLength = 2000, short = false, required = false }: { label: string; value: string; onChange: (value: string) => void; hint?: string; maxLength?: number; short?: boolean; required?: boolean }) { const id = useId(); return <label className="j-field" htmlFor={id}><span>{label}{required && <b aria-hidden="true"> *</b>}</span>{short ? <input id={id} aria-label={label} value={value} onChange={event => onChange(event.target.value)} maxLength={maxLength} required={required} aria-describedby={`${id}-hint`}/> : <textarea id={id} aria-label={label} value={value} onChange={event => onChange(event.target.value)} maxLength={maxLength} rows={3} required={required}/>}<small id={`${id}-hint`}>{hint || `${value.length}/${maxLength} caracteres`}</small></label>; }
export function JRating({ label, value, onChange, low = "Muito baixa", high = "Muito alta", optional = false }: { label: string; value: Rating | null; onChange: (value: Rating | null) => void; low?: string; high?: string; optional?: boolean }) { const id = useId(); return <fieldset className="j-rating"><legend>{label}{optional ? " (opcional)" : " *"}</legend><div className="j-rating-options">{[1,2,3,4,5].map(number => <label key={number}><input type="radio" name={id} value={number} checked={value === number} onChange={() => onChange(number as Rating)}/><span>{number}</span></label>)}</div><div className="j-rating-anchors"><small>1 · {low}</small><small>5 · {high}</small></div>{optional && value !== null && <button type="button" className="j-text-button" onClick={() => onChange(null)}>Limpar resposta</button>}</fieldset>; }
export function JEmpty({ title, children, action, onClick, visual = "starting" }: { title: string; children: ReactNode; action: string; onClick: () => void; visual?: LeaderVisual }) { return <div className="l-empty-page"><LeaderCover visual={visual} eyebrow="SEU DESENVOLVIMENTO, PASSO A PASSO" title={title} actions={<JButton onClick={onClick}>{action}<ArrowRight size={17}/></JButton>}>{children}</LeaderCover><section className="j-card l-empty-guide"><Leaf size={27}/><div><h2>Uma situação real é o começo.</h2><p>Você já lidera. Escolha um comportamento seu para desenvolver e conecte reflexão, plano, ensaio e prática. Os próximos passos ficam disponíveis conforme sua jornada avança.</p></div></section></div>; }
export function PrivateNote() { return <p className="j-private-note"><LockKeyhole size={14}/> Reflexão pessoal · salva neste navegador, sem envio automático ao RH.</p>; }
export function JError({ error }: { error: string }) { return error ? <div className="j-alert error" role="alert">{error}</div> : null; }

