import test from 'node:test';
import assert from 'node:assert/strict';
import { blankJournal, blankReview, confidenceSeries, createJourney, diagnose, emptyChallenge, emptyWorkspace, mergeWorkspaces, nextJourneyView, nextReviewDate, parseWorkspace, personalSummary, practiceSeries, reminderDue, restartPlan, saveWorkspace, storageKey, suggestedPlan, themeDefinitions, todayKey, validateChallenge, validateJournal, validatePlan, validateReview } from './journey-model.ts';

const challenge = () => ({ ...emptyChallenge(), title:'Teste descartável de decisão', context:'Situação de teste em memória, sem dados pessoais.', impact:3, frequency:2, willingness:4 });
const journal = (date, before = 2, after = 4) => ({ ...blankJournal(), id:crypto.randomUUID(), planId:'test-plan', createdAt:'2026-10-01T12:00:00Z', updatedAt:'2026-10-01T12:00:00Z', date, situation:'Situação isolada', action:'Ação concreta', result:'Resultado observado', learning:'Aprendizado registrado', confidenceBefore:before, confidenceAfter:after });
test('Starting point rejects empty answers; creates only explicit user input',()=>{assert.ok(validateChallenge(emptyChallenge()));assert.equal(validateChallenge(challenge()),null);const journey=createJourney(challenge());assert.equal(journey.entries.length,0);assert.equal(journey.plan,null);assert.equal(nextJourneyView(journey),'diagnosis');});
test('All recommended themes explain the recommendation; zero is a valid answer',()=>{for(const theme of themeDefinitions){const answers=theme.questions.map(question=>question.helpful?0:3);const result=diagnose(theme.id,answers);assert.equal(result.focus.behavior,theme.questions[0].behavior);assert.equal(result.attention.length,6);assert.match(result.explanation,/empate/);assert.throws(()=>diagnose(theme.id,[null,0,0,0,0,0]));assert.throws(()=>diagnose(theme.id,[4,0,0,0,0,0]));}});
test('Plan requires days and steps, remains a draft until confirmed',()=>{const plan=suggestedPlan('boundaries');assert.equal(plan.status,'draft');assert.equal(plan.startedAt,null);assert.equal(validatePlan(plan),null);assert.ok(validatePlan({...plan,days:[]}));assert.ok(validatePlan({...plan,steps:['',...plan.steps.slice(1)]}));});
test('Restart preserves old plan and practice history; requires another reflection',()=>{const journey=createJourney(challenge());journey.plan={...suggestedPlan('confidence'),status:'completed',startedAt:'2026-09-01T12:00:00Z',completedAt:'2026-09-08T12:00:00Z'};journey.entries=[journal('2026-09-02')];const restarted=restartPlan(journey);assert.equal(restarted.plan.cycle,2);assert.notEqual(restarted.plan.id,journey.plan.id);assert.equal(restarted.planHistory[0].id,journey.plan.id);assert.equal(restarted.entries[0].id,journey.entries[0].id);assert.equal(nextJourneyView(restarted),'diagnosis');});
test('Review schedule uses only current cycle and supports weekly/fortnightly',()=>{const journey=createJourney(challenge());journey.plan={...suggestedPlan('pressure'),status:'active',startedAt:'2026-09-20T12:00:00Z'};journey.reviews=[{...blankReview(),id:'old',planId:'old-cycle',date:'2026-09-29',createdAt:'2026-09-29T12:00:00Z'}];assert.equal(nextReviewDate(journey),'2026-09-27');assert.equal(nextJourneyView(journey,'2026-10-01'),'diagnosis');journey.diagnostics=[{id:'diagnosis',at:'2026-09-20T12:00:00Z',theme:'confidence',answers:[0,1,2,3,1,2],confidence:3}];journey.diagnosticDraft.open=false;assert.equal(nextJourneyView(journey,'2026-10-01'),'review');journey.plan.reviewEvery=14;assert.equal(nextReviewDate(journey),'2026-10-04');journey.plan.status='paused';assert.equal(nextReviewDate(journey),null);assert.equal(nextJourneyView(journey),'plan');});
test('Diary and review reject future dates and require real evidence',()=>{assert.ok(validateJournal(blankJournal()));assert.equal(validateJournal({...journal(todayKey()),editingId:null}),null);assert.ok(validateJournal({...journal('2099-01-01'),editingId:null}));assert.ok(validateReview(blankReview()));const review={...blankReview(),changed:'Mudança percebida',difficult:'Dificuldade atual',learned:'Aprendizado real',evidence:'Situação observada'};assert.equal(validateReview(review),null);assert.ok(validateReview({...review,decision:'adjust',adjustment:''}));assert.equal(validateReview({...review,decision:'adjust',adjustment:'Reformular o primeiro passo'}),null);});
test('Charts count only period records and complete confidence pairs, without extra data',()=>{const entries=[journal('2026-09-18'),journal('2026-09-24'),journal('2026-10-01'),journal('2026-10-02'),journal('2026-09-29',null,4)];const now=new Date('2026-10-01T12:00:00');assert.equal(practiceSeries(entries,14,now).reduce((sum,row)=>sum+row.count,0),4);const rows=confidenceSeries(entries,14,now);assert.equal(rows.length,3);assert.equal(rows[0].before,2);assert.equal(rows.at(-1).after,4);assert.equal(practiceSeries([],14,now).every(row=>row.count===0),true);});
test('Local reminders require active plan, selected day and configured time',()=>{const now=new Date('2026-10-01T12:00:00');const plan={...suggestedPlan('confidence'),status:'active',days:[now.getDay()],reminderTime:'11:00'};assert.equal(reminderDue(plan,now),true);assert.equal(reminderDue({...plan,status:'paused'},now),false);assert.equal(reminderDue({...plan,reminderTime:''},now),false);assert.equal(reminderDue({...plan,reminderTime:'13:00'},now),false);});
test('Storage is scoped by member AND space; save and reload preserve drafts',()=>{const records=new Map();const storage={setItem:(key,raw)=>records.set(key,raw)};const value=emptyWorkspace();const journey=createJourney(challenge());journey.diagnosticDraft.answers[0]=0;journey.journalDraft={...blankJournal(),situation:'Rascunho em memória'};value.journeys=[journey];value.selectedId=journey.id;const key=storageKey('company-a','member-a');saveWorkspace(storage,key,value);const restored=parseWorkspace(records.get(key));assert.equal(restored.journeys[0].diagnosticDraft.answers[0],0);assert.equal(restored.journeys[0].journalDraft.situation,'Rascunho em memória');assert.notEqual(key,storageKey('company-b','member-a'));assert.notEqual(key,storageKey('company-a','member-b'));assert.equal(records.size,1);});
test('Import checks schema, duplicate IDs and versions; merge never overwrites existing records',()=>{const current=emptyWorkspace(),incoming=emptyWorkspace();current.journeys=[createJourney(challenge())];current.selectedId=current.journeys[0].id;incoming.journeys=[{...current.journeys[0],challenge:{...challenge(),title:'Importado diferente'}},createJourney(challenge())];const result=mergeWorkspaces(current,incoming);assert.equal(result.added,1);assert.equal(result.workspace.journeys[0].challenge.title,current.journeys[0].challenge.title);assert.equal(result.workspace.selectedId,current.selectedId);assert.throws(()=>parseWorkspace('{bad'));assert.throws(()=>parseWorkspace(JSON.stringify({...current,version:2})));assert.throws(()=>parseWorkspace(JSON.stringify({...current,journeys:[...current.journeys,...current.journeys]})));assert.throws(()=>parseWorkspace(JSON.stringify({...current,selectedId:'missing'})));});
test('Quota failure propagates to the UI; no silent successful persistence',()=>{assert.throws(()=>saveWorkspace({setItem(){throw new Error('quota')}},'key',emptyWorkspace()),/quota/);assert.throws(()=>parseWorkspace('a'.repeat(2_000_001)),/limite/);});
test('Completed exercise advances to real practice; summary preserves earlier cycle plans',()=>{const journey=createJourney(challenge());journey.plan={...suggestedPlan('confidence'),status:'active',startedAt:new Date().toISOString()};journey.diagnostics=[{id:'test',at:new Date().toISOString(),theme:'confidence',answers:[0,1,2,3,1,2],confidence:3}];journey.diagnosticDraft.open=false;assert.equal(nextJourneyView(journey),'exercises');journey.exercises=[{id:'test-exercise',planId:journey.plan.id,exerciseId:'criteria',title:'Ensaio de teste',responses:['Resposta descartável'],createdAt:new Date().toISOString()}];assert.equal(nextJourneyView(journey),'journal');journey.plan.status='completed';const restarted=restartPlan(journey);const summary=personalSummary(restarted);assert.match(summary,/Ciclo 1 · concluído/);assert.match(summary,/Ciclo 2 · em construção/);assert.match(summary,/Resposta descartável/);});
