"use client";
import { lazy, Suspense } from "react";
import { ArrowRight, BookOpen, ChartNoAxesCombined, ClipboardList, Flag, Leaf, Plus, RotateCcw, Target } from "lucide-react";
import { nextJourneyView, nextReviewDate, readableDate, themeDefinitions, todayKey, type JourneyView, type JourneyWorkspaceData, type PersonalJourney, type JourneyTheme } from "./journey-model";
import { JButton, statusLabels } from "./journey-ui";
import { LeaderCover, JourneyRail, leaderPhotos } from "./leader-visuals";
import DashboardWidgets from "./journey-dashboard-widgets";
const Progress=lazy(()=>import("./journey-progress"));
const Distribution=lazy(()=>import("./journey-distribution"));
export default function JourneyHome({name,workspace,journey,navigate,select,start,archive,preferenceKey}:{name:string;workspace:JourneyWorkspaceData;journey:PersonalJourney|null;navigate:(view:JourneyView)=>void;select:(id:string)=>void;start:(theme?:JourneyTheme)=>void;archive:(id:string,archived:boolean)=>void;preferenceKey:string}) {
 const visible=workspace.journeys.filter(item=>!item.archivedAt),open=visible.filter(item=>item.plan?.status!=="completed"),active=visible.filter(item=>item.plan?.status==="active");
 const reviews=open.filter(item=>{const due=nextReviewDate(item);return due&&due<=todayKey()});
 const current=journey&&!journey.archivedAt?journey:open[0]||visible[0]||null;
 const entries=visible.flatMap(item=>item.entries.map(entry=>({entry,journey:item}))).sort((a,b)=>b.entry.date.localeCompare(a.entry.date)||b.entry.createdAt.localeCompare(a.entry.createdAt));
 const completedCycles=visible.reduce((sum,item)=>sum+item.planHistory.filter(plan=>plan.status==="completed").length+(item.plan?.status==="completed"?1:0),0);
 function resume(item:PersonalJourney,view?:JourneyView){select(item.id);navigate(view||nextJourneyView(item))}
 function go(view:JourneyView){if(current)resume(current,view);else start()}
 const metrics=[
 {title:"Jornadas abertas",value:open.length,description:"Desafios em desenvolvimento",icon:Flag,tone:"emerald",action:()=>current?resume(current):start()},
 {title:"Planos ativos",value:active.length,description:"Práticas em andamento",icon:Target,tone:"violet",action:()=>active[0]?resume(active[0],"plan"):go("plan")},
 {title:"Práticas registradas",value:entries.length,description:"Registros confirmados no diário",icon:ClipboardList,tone:"blue",action:()=>go("journal")},
 {title:"Ciclos concluídos",value:completedCycles,description:"Ciclos de prática revisados",icon:Leaf,tone:"pink",action:()=>{const item=workspace.journeys.find(item=>!item.archivedAt&&(item.plan?.status==="completed"||item.planHistory.some(plan=>plan.status==="completed")));if(item)resume(item,"review");else go("review")}},
 {title:"Revisões pendentes",value:reviews.length,description:"Planos com revisão prevista",icon:ChartNoAxesCombined,tone:"amber",action:()=>reviews[0]?resume(reviews[0],"review"):go("review")}];
 const widgets=[
 {id:"evolution",label:"Evolução pessoal",content:<Suspense fallback={<section className="j-card" role="status">Preparando sua evolução…</section>}><Progress entries={current?.entries||[]} onStart={()=>current?resume(current):start()}/></Suspense>},
 {id:"summary",label:"Resumo das jornadas",content:<Suspense fallback={<section className="j-card" role="status">Preparando seu resumo…</section>}><Distribution journeys={visible} onStart={()=>start()}/></Suspense>},
 {id:"focus",label:"Meu próximo passo",content:<section className="j-card p-focus"><div className="j-row"><h2>Meu próximo passo</h2><Target size={20}/></div><span className="p-status">{current?statusLabels[current.plan?.status||"draft"]:"Vamos começar?"}</span><h3>{current?.challenge.title||"Qual desafio você quer trabalhar?"}</h3><p>{current?.plan?.goal||current?.challenge.context||"Escolha uma situação real da sua liderança. A reflexão se transforma em um plano curto, com espaço para praticar e revisar."}</p><JButton onClick={()=>current?resume(current):start()}>{current?"Continuar minha jornada":"Escolher meu desafio"}<ArrowRight size={16}/></JButton>{current&&<small>Atualizada em {readableDate(current.updatedAt)} · ciclo {current.plan?.cycle||1}</small>}</section>},
 {id:"practices",label:"Práticas recentes",content:<section className="j-card p-recent"><div className="j-row"><h2>Práticas recentes</h2><BookOpen size={20}/></div>{entries.length?<div className="p-practice-list">{entries.slice(0,4).map(({entry,journey:item})=><button key={entry.id} onClick={()=>resume(item,"journal")}><span className="p-practice-icon"><BookOpen size={17}/></span><span><b>{entry.situation}</b><small>{readableDate(entry.date)} · {item.challenge.title}</small></span><ArrowRight size={16}/></button>)}</div>:<div className="p-empty"><BookOpen size={26}/><b>Seus aprendizados ganham espaço aqui.</b><p>Registre uma situação, a ação que tentou e o que aprendeu no seu diário de prática.</p><button className="j-text-button" onClick={()=>go("journal")}>Começar meu registro<ArrowRight size={15}/></button></div>}</section>}];
 const decisions=[{title:"Meu ponto de partida",text:"Escolha um desafio do seu dia a dia como líder.",action:"Definir desafio",icon:Flag,view:"starting" as JourneyView,tone:"amber"},{title:"Meu plano de prática",text:current?.plan?.goal||"Transforme a reflexão em pequenas ações observáveis.",action:"Ver meu plano",icon:Target,view:"plan" as JourneyView,tone:"violet"},{title:"Exercícios e reflexões",text:"Ensaie escolhas antes de praticar no trabalho.",action:"Abrir exercícios",icon:BookOpen,view:"exercises" as JourneyView,tone:"blue"},{title:"Revisão de progresso",text:reviews.length?reviews.length+" jornada(s) com revisão prevista para retomar.":"Observe o que mudou e escolha seu próximo passo.",action:"Revisar minha prática",icon:ChartNoAxesCombined,view:"review" as JourneyView,tone:"emerald"}];
 return <div className="j-home p-dashboard"><LeaderCover visual="overview" eyebrow={`SEU ESPAÇO DE EVOLUÇÃO · OLÁ, ${name.split(" ")[0]}`} title="Sua liderança também merece cuidado." actions={<><JButton onClick={()=>current?resume(current):start()}>{current?"Continuar meu desenvolvimento":"Escolher meu primeiro desafio"}<ArrowRight size={17}/></JButton><JButton secondary onClick={()=>current?resume(current,"journal"):start("custom")}>{current?"Registrar uma prática":"Começar por outra situação"}</JButton></>}>Você já cuida de pessoas, conversas e decisões. Aqui, reserve espaço para desenvolver sua forma de liderar — com reflexão, prática e aprendizados da sua realidade.</LeaderCover><JourneyRail journey={current} navigate={view=>current?resume(current,view):start()}/><div className="l-section-heading l-overview-heading"><div><span className="j-eyebrow">SEU PERCURSO EM NÚMEROS</span><h2>O que você colocou em movimento.</h2></div><p>Seus registros reais · jornadas não arquivadas.</p></div>
 <div className="p-stats">{metrics.map(metric=><button key={metric.title} className={"p-stat "+metric.tone} onClick={metric.action}><div><span>{metric.title}</span><i><metric.icon size={18}/></i></div><strong>{metric.value}</strong><small>{metric.description}</small></button>)}</div>
 <div className="l-section-heading l-overview-heading"><div><span className="j-eyebrow">OBSERVAR PARA EVOLUIR</span><h2>Aprendizados que orientam o próximo passo.</h2></div><p>{current?`Jornada em foco: ${current.challenge.title}`:"Crie uma jornada para começar seu acompanhamento."}</p></div><DashboardWidgets widgets={widgets} preferenceKey={preferenceKey}/>
 <section className="j-card p-decisions"><div className="j-row"><div><span className="j-eyebrow">DO PENSAMENTO À PRÁTICA</span><h2>Seu desenvolvimento, no seu ritmo.</h2></div><p>Um passo possível para a sua liderança.</p></div><div className="p-decision-grid">{decisions.map(item=><article key={item.view}><span className={"p-tone-icon "+item.tone}><item.icon size={20}/></span><h3>{item.title}</h3><p>{item.text}</p><button className="j-text-button" onClick={()=>item.view==="starting"?start():item.view==="review"&&reviews[0]?resume(reviews[0],"review"):go(item.view)}>{item.action}<ArrowRight size={15}/></button></article>)}</div></section>
 <section className="j-card p-paths"><div className="j-row"><div><span className="j-eyebrow">SITUAÇÕES DE QUEM JÁ LIDERA</span><h2>Por onde você quer evoluir?</h2></div><JButton secondary onClick={()=>start("custom")}><Plus size={16}/>Outro desafio</JButton></div><div className="p-theme-grid">{themeDefinitions.map((theme,index)=><button key={theme.id} onClick={()=>start(theme.id)}><img className="l-theme-photo" src={[leaderPhotos.starting,"/images/landing/format-duo-alt.webp",leaderPhotos.exercises][index]} alt="" loading="lazy" decoding="async"/><span className={"p-tone-icon "+["emerald","amber","violet"][index]}><Leaf size={20}/></span><span><b>{theme.title}</b><small>{theme.description}</small></span><ArrowRight size={17}/></button>)}</div></section>
 {workspace.journeys.length>0&&<section className="j-card"><div className="j-row"><h2>Minhas jornadas</h2><JButton secondary onClick={()=>start()}><Plus size={16}/>Nova jornada</JButton></div><div className="j-journey-list">{visible.map(item=><article key={item.id}><span className="j-mini-leaf"><Leaf size={20}/></span><div><h3>{item.challenge.title}</h3><small>{statusLabels[item.plan?.status||"draft"]} · {item.entries.length} prática(s) · {item.reviews.length} revisão(ões)</small></div><div className="j-actions"><JButton secondary onClick={()=>resume(item)}>Retomar<ArrowRight size={15}/></JButton><button className="j-text-button" onClick={()=>archive(item.id,true)}>Arquivar</button></div></article>)}</div>{workspace.journeys.some(item=>item.archivedAt)&&<details><summary>Jornadas arquivadas ({workspace.journeys.filter(item=>item.archivedAt).length})</summary>{workspace.journeys.filter(item=>item.archivedAt).map(item=><div className="j-row j-history-item" key={item.id}><span>{item.challenge.title}</span><JButton secondary onClick={()=>archive(item.id,false)}><RotateCcw size={14}/>Restaurar</JButton></div>)}</details>}</section>}</div>;
}

