"use client";
import { ArrowRight, ArrowUpRight, BarChart3, CalendarDays, ChevronDown, Clock3, Sparkles, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";

type Cycle={id:string;status:string;createdAt:string;responseCount:number;action:string|null};
type Run={id:string;created_at:string};
type Pair={id:string;createdAt:string};
type Request={type:string;token:string}|null;
type OverviewData={name:string;role:string;company:string;mirrors:Cycle[];runs:Run[];pairs:Pair[];request:Request};
type View="mirror"|"decisions"|"communication"|"evolution"|"team"|"experiences";
const experiences=[
  {key:"mirror" as const,title:"Espelho do Líder",description:"Receba percepções do seu time e amplie sua visão como líder.",className:"mirror"},
  {key:"decisions" as const,title:"Decisões Sob Pressão",description:"Pratique decisões reais, explore caminhos e veja os impactos.",className:"decisions"},
  {key:"communication" as const,title:"Raio X da Comunicação",description:"Descubra como você se comunica, como é percebida e onde pode evoluir.",className:"communication"},
];
function activitySeries(data:OverviewData){
  const today=new Date(),months=Array.from({length:6},(_,i)=>{const d=new Date(today.getFullYear(),today.getMonth()-5+i,1);return {year:d.getFullYear(),month:d.getMonth(),label:d.toLocaleDateString("pt-BR",{month:"short"}).replace(".","").toUpperCase()}});
  const items=[...data.mirrors.map(x=>x.createdAt),...data.runs.map(x=>x.created_at),...data.pairs.map(x=>x.createdAt)];
  const values=months.map(m=>items.filter(x=>{const d=new Date(x);return d.getFullYear()<m.year||(d.getFullYear()===m.year&&d.getMonth()<=m.month)}).length);
  return {months,values,total:items.length};
}
export function ExperienceCards({data,onNavigate,query=""}:{data:OverviewData;onNavigate:(v:View)=>void;query?:string}){
  const filtered=experiences.filter(x=>(x.title+" "+x.description).toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")));
  return <div className="reference-experience-grid">{filtered.map(x=>{
    const mirror=data.mirrors[0],count=x.key==="mirror"?mirror?.responseCount:undefined;
    const details=x.key==="mirror"?(mirror?`${count} de 5 respostas mínimas`:"8 min · para líderes"):x.key==="decisions"?(data.runs.length?`${data.runs.length} cenário(s) concluído(s)`:"Simulação interativa · 7 min"):(data.pairs.length?`${data.pairs.length} comparação(ões)`:"Em dupla · 10 min");
    return <article className="reference-experience-card" key={x.key}><button className={`reference-art ${x.className}`} onClick={()=>onNavigate(x.key)} aria-label={`Abrir ${x.title}`}/><div className="reference-experience-body"><h3>{x.title}</h3><p>{x.description}</p><div className="reference-card-meta"><span>{details}</span>{x.key!=="mirror"&&<Clock3 size={14}/>}</div>{x.key==="mirror"&&mirror&&<div className="reference-progress"><span style={{width:`${Math.min(100,mirror.responseCount/5*100)}%`}}/></div>}<Button variant={x.key==="decisions"?"default":"outline"} className="reference-card-button" onClick={()=>onNavigate(x.key)}>{x.key==="mirror"&&mirror?"Acompanhar":x.key==="decisions"?"Continuar":"Começar"} <ArrowRight size={16}/></Button></div></article>
  })}{!filtered.length&&<div className="reference-empty">Nenhuma experiência corresponde à busca.</div>}</div>;
}
export default function OverviewDashboard({data,onNavigate,query=""}:{data:OverviewData;onNavigate:(v:View)=>void;query?:string}){
  const hour=new Date().getHours(),greeting=hour<12?"Bom dia":hour<18?"Boa tarde":"Boa noite";
  const canLead=["admin","rh","leader"].includes(data.role),mirror=data.mirrors[0];
  const next=data.request?{eyebrow:"UM CONVITE PARA VOCÊ",title:data.request.type==="mirror"?"Sua percepção pode ajudar o time.":"Uma conversa melhor começa aqui.",body:data.request.type==="mirror"?"Responda sobre comportamentos que você observa. Suas respostas individuais ficam protegidas.":"Compare preferências de comunicação depois que as duas pessoas consentirem.",button:"Responder convite",view:data.request.type==="mirror"?"mirror" as const:"communication" as const}:canLead?mirror?.status==="open"?{eyebrow:"SEU PRÓXIMO PASSO",title:"Convidar o time para o Espelho do Líder",body:"Receba a percepção do seu time e descubra novos pontos de vista para o seu desenvolvimento.",button:"Enviar convites",view:"mirror" as const}:mirror?.status==="closed"?{eyebrow:"SEU PRÓXIMO PASSO",title:"Olhar para o que seu time percebeu",body:"Revise o ciclo, encontre pontos de convergência e escolha uma ação para praticar.",button:"Ver meu ciclo",view:"mirror" as const}:{eyebrow:"SEU PRÓXIMO PASSO",title:"Comece pelo Espelho do Líder",body:"Observe seus comportamentos de liderança e prepare uma conversa com seu time.",button:"Começar agora",view:"mirror" as const}:{eyebrow:"SEU PRÓXIMO PASSO",title:"Explore uma decisão de cada vez",body:"Pratique escolhas em situações de trabalho e descubra novas formas de agir.",button:"Explorar cenários",view:"decisions" as const};
  const series=activitySeries(data),max=Math.max(1,...series.values),points=series.values.map((v,i)=>`${24+i*48},${124-v/max*84}`).join(" ");
  return <div className="reference-overview"><div className="reference-overview-main"><div className="reference-greeting"><h1>{greeting}, {data.name.split(" ")[0]}<span>.</span></h1><p>Sua jornada de desenvolvimento continua aqui.</p></div><section className="reference-next"><div className="reference-next-copy"><span className="eyebrow">{next.eyebrow}</span><h2>{next.title}</h2><p>{next.body}</p><Button onClick={()=>onNavigate(next.view)}>{next.button}<ArrowRight size={17}/></Button></div><div className="reference-next-art" role="img" aria-label="Formulários de percepção ilustrados"/></section><div className="reference-experience-heading"><h2>Suas experiências</h2><button onClick={()=>onNavigate("experiences")}>Ver todas <ArrowRight size={16}/></button></div><ExperienceCards data={data} onNavigate={onNavigate} query={query}/></div><aside className="reference-rail"><section className="reference-evolution"><div className="reference-rail-heading"><h2>Sua evolução</h2><span>Últimos 6 meses <ChevronDown size={14}/></span></div>{series.total?<div className="reference-stat"><b>{series.total}</b><span>experiências iniciadas</span></div>:<div className="reference-stat empty-stat"><BarChart3 size={28}/><span>Suas experiências aparecerão aqui</span></div>}<div className="reference-chart"><svg viewBox="0 0 300 155" role="img" aria-label={series.total?`Gráfico de atividades nos últimos seis meses: ${series.values.join(", ")}`:"Gráfico vazio de atividades nos últimos seis meses"}>{[40,68,96,124].map(y=><line key={y} x1="24" x2="264" y1={y} y2={y} stroke="#e6ece7"/>)}{series.total>0&&<><polygon points={`24,124 ${points} 264,124`} fill="#def1e5" opacity=".8"/><polyline points={points} fill="none" stroke="#16855d" strokeWidth="2.5"/>{series.values.map((v,i)=><circle key={i} cx={24+i*48} cy={124-v/max*84} r="3.5" fill="#16855d" stroke="#fff" strokeWidth="2"/>)}</>}{series.months.map((m,i)=><text key={i} x={24+i*48} y="148" textAnchor="middle" fontSize="9" fill="#687f75">{m.label}</text>)}</svg></div><div className="reference-evolution-note"><span><BarChart3 size={18}/></span><p>{series.total?`Você começou ${series.total} experiência(s). Continue no seu ritmo.`:"Comece uma experiência para acompanhar seu caminho."}</p></div></section><section className="reference-week"><div className="reference-rail-heading"><h2><Sparkles size={20}/> Ação da semana</h2><span>•••</span></div><div className="reference-week-body"><span className="reference-week-icon"><UsersRound size={24}/></span><div><strong>{mirror?.action||"Escolha um próximo passo para sua liderança."}</strong><p>{mirror?.action?"Volte ao seu ciclo para revisar essa prática.":"Pequenas ações criam espaço para conversas melhores."}</p></div></div><Button onClick={()=>onNavigate(mirror?"evolution":"mirror")}>{mirror?"Ver minha evolução":"Explorar o Espelho"} <ArrowRight size={16}/></Button></section></aside></div>;
}
