"use client";

import { useEffect, useId, useState } from "react";
import { Activity, ArrowRight, BarChart3, ShieldCheck } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { mirrorLabels } from "@/lib/experiences";
import type { View } from "./overview-dashboard";
import { activityBuckets, activityEvents, eligibleMirrors, energyDays, shortDate, thermometerRows, type PanelData } from "./panel-data";

type Tab = "activity" | "mirror" | "energy" | "thermometer";
const colors = ["#194b3e", "#8da600", "#b76e42", "#478eb0", "#826a9c", "#607a52"];
const tooltipStyle = { borderRadius: 12, border: "1px solid #dce3dc", boxShadow: "0 10px 25px #153b2c12", fontSize: 13 };
const axis = { fill: "#64766d", fontSize: 11 };

function EmptyChart({ title, body, action, onClick }: { title: string; body: string; action: string; onClick: () => void }) {
  return <div className="panel-chart-empty"><span><BarChart3 size={29}/></span><h3>{title}</h3><p>{body}</p><button className="panel-text-link" onClick={onClick}>{action}<ArrowRight size={16}/></button></div>;
}

export default function PanelInsights({ data, onNavigate, onOpenMirror }: { data: PanelData; onNavigate: (view: View) => void; onOpenMirror: (id: string) => void }) {
  const [tab, setTab] = useState<Tab>("activity");
  const [activityPeriod, setActivityPeriod] = useState(90);
  const [energyPeriod, setEnergyPeriod] = useState(14);
  const [cycleId, setCycleId] = useState("");
  const [trackId, setTrackId] = useState("");
  const [reduceMotion, setReduceMotion] = useState(true);
  const id = useId();
  useEffect(() => { const media = window.matchMedia("(prefers-reduced-motion: reduce)"); const update = () => setReduceMotion(media.matches); update(); media.addEventListener("change", update); return () => media.removeEventListener("change", update); }, []);
  const canLead = ["admin", "rh", "leader"].includes(data.role);
  const tabs: { key: Tab; label: string }[] = [
    { key: "activity", label: "Sua atividade" },
    ...(canLead && data.modules.mirror ? [{ key: "mirror" as const, label: "Escuta do time" }] : []),
    ...(data.modules.energy ? [{ key: "energy" as const, label: "Sua energia" }] : []),
    ...(canLead && data.modules.thermometer ? [{ key: "thermometer" as const, label: "Comportamentos" }] : []),
  ];
  const selectedTab = tabs.some(item => item.key === tab) ? tab : "activity";
  const activity = activityBuckets(activityEvents(data), activityPeriod);
  const activityCount = activity.reduce((sum, item) => sum + item.experiences + item.practices, 0);
  const energy = energyDays(data.energyEntries, energyPeriod);
  const energyCount = energy.reduce((sum, item) => sum + item.count, 0);
  const cycles = eligibleMirrors(data.mirrors);
  const cycle = cycles.find(item => item.id === cycleId) || cycles[0];
  const mirror = cycle ? mirrorLabels.map((label, index) => ({ label, self: cycle.selfScores[index] ?? null, team: cycle.teamScores?.[index] ?? null })) : [];
  const track = data.thermometerTracks.find(item => item.id === trackId) || data.thermometerTracks[0];
  const rounds = track ? thermometerRows(track) : [];
  const title = selectedTab === "activity" ? "Seu percurso, ao longo do tempo." : selectedTab === "mirror" ? "Duas perspectivas. Uma conversa." : selectedTab === "energy" ? "O que dá energia à sua rotina?" : "O que o time observa na prática.";
  const subtitle = selectedTab === "activity" ? "Experiências e práticas disponíveis no seu histórico pessoal." : selectedTab === "mirror" ? "Sua autoavaliação e a percepção agregada do time. Escala de 1 a 5." : selectedTab === "energy" ? "Efeito médio que você registrou em cada dia. Escala de −2 a +2." : "Percepções agregadas por comportamento e rodada. Escala de 1 a 5.";
  return <section className="panel-insights" aria-labelledby={id + "-title"}>
    <div className="panel-section-label"><span className="panel-eyebrow"><Activity size={14}/> INDICADORES COM CONTEXTO</span><span>Seus registros reais</span></div>
    <div className="panel-chart-tabs" role="tablist" aria-label="Indicadores da liderança">{tabs.map((item, index) => <button key={item.key} id={id + "-tab-" + item.key} role="tab" aria-selected={selectedTab === item.key} aria-controls={id + "-content"} tabIndex={selectedTab === item.key ? 0 : -1} onClick={() => setTab(item.key)} onKeyDown={event => { if (["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) { event.preventDefault(); const next = event.key === "Home" ? 0 : event.key === "End" ? tabs.length - 1 : (index + (event.key === "ArrowRight" ? 1 : -1) + tabs.length) % tabs.length; setTab(tabs[next].key); document.getElementById(id + "-tab-" + tabs[next].key)?.focus(); } }}>{item.label}</button>)}</div>
    <div role="tabpanel" id={id + "-content"} aria-labelledby={id + "-tab-" + selectedTab} tabIndex={0}>
      <div className="panel-chart-heading"><div><h2 id={id + "-title"}>{title}</h2><p>{subtitle}</p></div>
        {selectedTab === "activity" && <label className="panel-period">Período<select aria-label="Período de atividade" value={activityPeriod} onChange={event => setActivityPeriod(Number(event.target.value))}><option value={30}>Últimos 30 dias</option><option value={90}>Últimos 90 dias</option><option value={180}>Últimos 180 dias</option></select></label>}
        {selectedTab === "energy" && <label className="panel-period">Período<select aria-label="Período de energia" value={energyPeriod} onChange={event => setEnergyPeriod(Number(event.target.value))}><option value={7}>Últimos 7 dias</option><option value={14}>Últimos 14 dias</option><option value={30}>Últimos 30 dias</option></select></label>}
        {selectedTab === "mirror" && cycles.length > 0 && <label className="panel-period">Ciclo<select aria-label="Ciclo de escuta" value={cycle?.id} onChange={event => setCycleId(event.target.value)}>{cycles.map((item, index) => <option key={item.id} value={item.id}>Ciclo {cycles.length - index} · {shortDate(item.createdAt)}</option>)}</select></label>}
        {selectedTab === "thermometer" && data.thermometerTracks.length > 0 && <label className="panel-period">Acompanhamento<select aria-label="Acompanhamento de comportamentos" value={track?.id} onChange={event => setTrackId(event.target.value)}>{data.thermometerTracks.map((item, index) => <option key={item.id} value={item.id}>Acompanhamento {data.thermometerTracks.length - index} · {shortDate(item.createdAt)}</option>)}</select></label>}
      </div>
      {selectedTab === "activity" && (activityCount ? <><div className="panel-chart-summary"><strong>{activityCount}</strong><span>registro{activityCount === 1 ? "" : "s"} disponível{activityCount === 1 ? "" : "s"} no período</span></div><div className="panel-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={activity} accessibilityLayer margin={{ top: 16, right: 15, left: -20, bottom: 8 }}><CartesianGrid stroke="#e8ede8" vertical={false}/><XAxis dataKey="label" tick={axis} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={axis} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle} labelFormatter={label => activity.find(item => item.label === label)?.range || label} cursor={{ fill: "#f3f6ef" }}/><Legend iconType="circle" wrapperStyle={{ fontSize: 12, paddingTop: 14 }}/><Bar dataKey="experiences" name="Experiências" fill="#194b3e" radius={[5, 5, 0, 0]} maxBarSize={38} isAnimationActive={!reduceMotion}/><Bar dataKey="practices" name="Práticas registradas" fill="#b9d94b" radius={[5, 5, 0, 0]} maxBarSize={38} isAnimationActive={!reduceMotion}/></BarChart></ResponsiveContainer></div><details className="panel-data-table"><summary>Consultar valores e origem dos dados</summary><p>Conta ciclos, cenários, duplas, reflexões e acompanhamentos. Práticas incluem o diário de energia e ações registradas após o Espelho. Não mede desempenho ou engajamento. O histórico carregado inclui até 20 cenários e 20 reflexões de carreira, até 20 práticas por ciclo e até 100 registros de energia dos últimos 30 dias.</p><table><caption>Atividade pessoal disponível por intervalo</caption><thead><tr><th>Intervalo</th><th>Experiências</th><th>Práticas</th></tr></thead><tbody>{activity.map(row => <tr key={row.label}><th>{row.range}</th><td>{row.experiences}</td><td>{row.practices}</td></tr>)}</tbody></table></details></> : <EmptyChart title="Seu percurso começa com um registro." body="Conclua uma atividade ou registre uma prática. O gráfico aparecerá quando houver dados no período escolhido." action="Escolher uma experiência" onClick={() => onNavigate("experiences")}/>)}
      {selectedTab === "mirror" && (cycle ? <><div className="panel-chart-summary"><strong>{cycle.responseCount}</strong><span>respostas no ciclo encerrado · percepção coletiva</span></div><div className="panel-chart panel-chart-mirror"><ResponsiveContainer width="100%" height="100%"><BarChart data={mirror} layout="vertical" accessibilityLayer margin={{ top: 8, right: 20, left: 0, bottom: 5 }}><CartesianGrid stroke="#e8ede8" horizontal={false}/><XAxis type="number" domain={[0, 5]} tick={axis} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="label" width={113} tick={axis} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle}/><Legend iconType="circle" wrapperStyle={{ fontSize: 12 }}/><Bar dataKey="self" name="Sua autoavaliação" fill="#b9d94b" radius={[0, 4, 4, 0]} isAnimationActive={!reduceMotion}/><Bar dataKey="team" name="Percepção do time" fill="#194b3e" radius={[0, 4, 4, 0]} isAnimationActive={!reduceMotion}/></BarChart></ResponsiveContainer></div><details className="panel-data-table"><summary>Consultar valores da comparação</summary><table><caption>Escala de 1 a 5. Sem elementos suficientes aparece como indisponível.</caption><thead><tr><th>Comportamento</th><th>Você</th><th>Time</th></tr></thead><tbody>{mirror.map(row => <tr key={row.label}><th>{row.label}</th><td>{row.self ?? "Indisponível"}</td><td>{row.team ?? "Indisponível"}</td></tr>)}</tbody></table></details></> : <EmptyChart title="A escuta precisa de tempo e confiança." body="A comparação aparece após encerrar um ciclo com pelo menos cinco respostas válidas. Respostas individuais permanecem protegidas." action={data.mirrors.length ? "Acompanhar meu ciclo" : "Iniciar ciclo de escuta"} onClick={() => onNavigate("mirror")}/>)}
      {selectedTab === "energy" && (energyCount ? <><div className="panel-chart-summary"><strong>{energyCount}</strong><span>atividade{energyCount === 1 ? "" : "s"} registrada{energyCount === 1 ? "" : "s"} · diário pessoal</span></div><div className="panel-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={energy} accessibilityLayer margin={{ top: 16, right: 20, left: -20, bottom: 8 }}><CartesianGrid stroke="#e8ede8" vertical={false}/><XAxis dataKey="label" tick={axis} axisLine={false} tickLine={false} minTickGap={28}/><YAxis domain={[-2, 2]} ticks={[-2, -1, 0, 1, 2]} tick={axis} axisLine={false} tickLine={false}/><ReferenceLine y={0} stroke="#c7d1c8" strokeDasharray="4 4"/><Tooltip contentStyle={tooltipStyle} formatter={value => [value, "Efeito médio"]}/><Line type="linear" dataKey="average" name="Energia registrada" stroke="#194b3e" strokeWidth={2.5} dot={{ r: 4, fill: "#b9e900", stroke: "#194b3e" }} activeDot={{ r: 6 }} connectNulls={false} isAnimationActive={!reduceMotion}/></LineChart></ResponsiveContainer></div><p className="panel-chart-note">−2 desgastou muito · 0 neutro · +2 deu muita energia. Dias sem registro ficam sem ponto. Esses dados não representam o clima do time.</p><details className="panel-data-table"><summary>Consultar médias diárias</summary><table><caption>Efeito médio das atividades do seu diário</caption><thead><tr><th>Dia</th><th>Registros</th><th>Efeito médio</th></tr></thead><tbody>{energy.filter(row => row.count).map(row => <tr key={row.date}><th>{row.label}</th><td>{row.count}</td><td>{row.average}</td></tr>)}</tbody></table></details></> : <EmptyChart title="Entenda o ritmo dos seus dias." body="Registre como uma atividade afetou sua energia. As médias diárias aparecerão aqui, sem conclusões sobre saúde ou desempenho." action="Registrar minha energia" onClick={() => onNavigate("energy")}/>)}
      {selectedTab === "thermometer" && (track && rounds.length ? <><div className="panel-chart-summary"><strong>{rounds.length}</strong><span>rodada{rounds.length === 1 ? "" : "s"} encerrada{rounds.length === 1 ? "" : "s"} com resultados disponíveis</span></div><div className="panel-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={rounds} accessibilityLayer margin={{ top: 16, right: 20, left: -20, bottom: 8 }}><CartesianGrid stroke="#e8ede8" vertical={false}/><XAxis dataKey="label" tick={axis} axisLine={false} tickLine={false}/><YAxis domain={[1, 5]} ticks={[1, 2, 3, 4, 5]} tick={axis} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle}/><Legend iconType="circle" wrapperStyle={{ fontSize: 12 }}/>{track.dimensions.map((dimension, index) => <Line key={dimension} type="linear" dataKey={"dimension" + index} name={mirrorLabels[dimension]} stroke={colors[index % colors.length]} strokeWidth={2.5} dot={{ r: 4 }} connectNulls={false} isAnimationActive={!reduceMotion}/>)}</LineChart></ResponsiveContainer></div><details className="panel-data-table"><summary>Consultar resultados por rodada</summary><table><caption>Somente rodadas encerradas com pelo menos cinco respostas válidas</caption><thead><tr><th>Rodada</th>{track.dimensions.map(dimension => <th key={dimension}>{mirrorLabels[dimension]}</th>)}</tr></thead><tbody>{rounds.map((row, i) => <tr key={i}><th>{row.label}</th>{track.dimensions.map((dimension, index) => <td key={dimension}>{row["dimension" + index] ?? "Indisponível"}</td>)}</tr>)}</tbody></table></details></> : <EmptyChart title="Desenvolvimento que você pode acompanhar." body="Após um ciclo do Espelho, acompanhe comportamentos no Termômetro. O gráfico usa apenas rodadas encerradas com pelo menos cinco respostas válidas." action="Abrir acompanhamento" onClick={() => onNavigate("thermometer")}/>)}
      <div className="panel-insight-footer"><span><ShieldCheck size={15}/> Dados do seu acesso e espaço atual.</span><button className="panel-text-link" onClick={() => selectedTab === "mirror" && cycle ? onOpenMirror(cycle.id) : onNavigate(selectedTab === "energy" ? "energy" : selectedTab === "mirror" ? "mirror" : selectedTab === "thermometer" ? "thermometer" : "evolution")}>Abrir {selectedTab === "activity" ? "meu histórico" : "registros"}<ArrowRight size={15}/></button></div>
    </div>
  </section>;
}
