import Link from "next/link";
import { ArrowRight, ArrowUpRight, UsersRound, Zap, MessageCircleMore, Sparkles } from "lucide-react";

const experiences = [
  { n: "01", title: "Espelho do Líder", desc: "Compare sua percepção com a visão coletiva do time e escolha um próximo passo concreto.", icon: UsersRound, tone: "coral" },
  { n: "02", title: "Decisões Sob Pressão", desc: "Explore situações reais, faça escolhas e veja como cada decisão muda o caminho.", icon: Zap, tone: "blue" },
  { n: "03", title: "Raio X da Comunicação", desc: "Entenda onde duas pessoas se encontram e onde vale combinar um jeito melhor de conversar.", icon: MessageCircleMore, tone: "violet" },
];
function Radar() {
  const labels = ["Clareza","Escuta","Abertura","Delegação","Reconhecimento","Acompanhamento"];
  return <div className="radar-card"><div className="radar-top"><b>SEU PERFIL DE LIDERANÇA</b><span>VISÃO GERAL</span></div><svg viewBox="0 0 410 340" role="img" aria-label="Ilustração de um gráfico de liderança">
    {[1,2,3,4].map(n=><polygon key={n} points={Array.from({length:6},(_,i)=>{const a=-Math.PI/2+i*Math.PI/3;return `${205+Math.cos(a)*30*n},${174+Math.sin(a)*30*n}`}).join(" ")} fill="none" stroke="#dfe6f4"/>)}
    {Array.from({length:6},(_,i)=>{const a=-Math.PI/2+i*Math.PI/3;return <line key={i} x1="205" y1="174" x2={205+Math.cos(a)*120} y2={174+Math.sin(a)*120} stroke="#e4e9f3"/>})}
    <polygon points="205,80 288,126 280,219 205,269 129,218 128,130" fill="#1254d3" fillOpacity=".14" stroke="#1254d3" strokeWidth="2"/>
    <polygon points="205,98 274,134 270,213 205,247 140,211 148,141" fill="#a4b2c8" fillOpacity=".12" stroke="#a4b2c8" strokeWidth="2" strokeDasharray="4 4"/>
    {labels.map((label,i)=>{const a=-Math.PI/2+i*Math.PI/3;return <text key={label} x={205+Math.cos(a)*151} y={178+Math.sin(a)*143} textAnchor="middle" fontSize="10" fill="#35435c">{label}</text>})}
  </svg><div className="radar-legend"><span><i/>Você</span><span><i/>Seu time</span></div></div>
}
export default function Home() {
  return <div className="site"><header className="topbar"><Link className="brand" href="/"><span className="mark">S<i/></span><span>synky<small>EVOLUÇÃO</small></span></Link><nav aria-label="Navegação principal"><a href="#experiencias">Experiências</a><a href="#como-funciona">Como funciona</a><Link href="/app" className="nav-enter">Entrar <ArrowUpRight size={16}/></Link></nav></header>
    <main><section className="hero"><div className="hero-copy"><div className="eyebrow">AUTOCONHECIMENTO <b>•</b> CONEXÕES <b>•</b> EVOLUÇÃO</div><h1>Descubra novas formas de <em>liderar.</em></h1><p>Transforme percepções em conversas melhores, escolhas mais conscientes e desenvolvimento que acontece no trabalho.</p><div className="hero-actions"><Link href="/app" className="button primary">Começar agora <ArrowRight size={18}/></Link><a href="#experiencias" className="button outline">Explorar experiências</a></div><div className="hero-details"><span><Sparkles size={16}/> Insights para colocar em prática</span><span><UsersRound size={16}/> Feito para pessoas e equipes</span></div></div><div className="hero-art"><div className="orb"/><Radar/><div className="floating one"><UsersRound size={19}/><span><b>Espelho do Líder</b><small>Uma visão construída junto.</small></span><ArrowUpRight size={15}/></div><div className="floating two"><Zap size={19}/><span><b>Decisões Sob Pressão</b><small>Escolhas com contexto.</small></span><ArrowUpRight size={15}/></div></div></section>
    <section className="experiences" id="experiencias"><div className="section-head"><div><span className="kicker">EXPERIÊNCIAS SY N K Y</span><h2>Aprender sobre si.<br/><em>Agir com os outros.</em></h2></div><p>Cada experiência parte de situações do cotidiano e termina com uma ideia que você pode levar para a próxima conversa.</p></div><div className="experience-grid">{experiences.map(x=><Link href="/app" className={`experience-card ${x.tone}`} key={x.n}><div className="exp-top"><span>{x.n} / EXPERIÊNCIA</span><x.icon size={25}/></div><div className="exp-number">{x.n}</div><div className="exp-content"><h3>{x.title}</h3><p>{x.desc}</p><span className="exp-arrow"><ArrowRight size={18}/></span></div></Link>)}</div></section>
    <section className="how" id="como-funciona"><div><span className="kicker">DO INSIGHT À AÇÃO</span><h2>Seu desenvolvimento acontece em movimento.</h2></div><div className="steps"><div><b>01</b><h3>Explore</h3><p>Responda experiências curtas e relevantes, no seu ritmo.</p></div><div><b>02</b><h3>Entenda</h3><p>Veja padrões e perguntas que abrem novas perspectivas.</p></div><div><b>03</b><h3>Experimente</h3><p>Escolha uma ação pequena e acompanhe sua prática.</p></div></div></section></main><footer className="footer"><span className="brand"><span className="mark">S<i/></span><span>synky<small>EVOLUÇÃO</small></span></span><span>Desenvolvimento humano com espaço para cada pessoa.</span><Link href="/app">Acessar plataforma <ArrowRight size={16}/></Link></footer></div>;
}
