export const publicExperiences=[
  {slug:"mirror",number:"01",title:"Espelho do Líder",audience:"Para líderes e equipes",duration:"8 min para começar",summary:"Compare sua percepção com a visão coletiva da equipe e escolha uma ação prática para acompanhar.",steps:["Faça sua autoavaliação sobre comportamentos observáveis.","Convide integrantes da equipe pelo e-mail de cada pessoa.","Encerre o ciclo e veja concordâncias e diferenças quando houver respostas suficientes."],privacy:"O líder vê somente médias agregadas depois do encerramento e de pelo menos cinco respostas válidas. Respostas individuais não são exibidas.",color:"mirror",image:"/images/experiences/mirror-v2.webp",imageAlt:"Líder ouvindo percepções de integrantes do time"},
  {slug:"decisions",number:"02",title:"Decisões Sob Pressão",audience:"Para líderes e profissionais",duration:"7 min por cenário",summary:"Pratique escolhas em situações de trabalho, veja as consequências e reflita sobre os comportamentos presentes nas suas decisões.",steps:["Escolha um dos cenários disponíveis.","Decida como agir em cada uma das três etapas.","Leia uma devolutiva baseada nas escolhas que você fez e acompanhe seu histórico."],privacy:"Você e o administrador master podem consultar suas escolhas e devolutivas na área de Resultados. Uma decisão isolada não define seu perfil.",color:"decisions",image:"/images/experiences/decisions-v2.webp",imageAlt:"Líder avaliando uma decisão de equipe sob prazo"},
  {slug:"communication",number:"03",title:"Raio X da Comunicação",audience:"Para duplas de trabalho",duration:"10 min por pessoa",summary:"Descubra onde suas preferências de comunicação combinam e transforme possíveis ruídos em acordos práticos.",steps:["Convide uma pessoa para participar da comparação.","Cada pessoa responde separadamente e consente com o compartilhamento.","Conversem sobre pontos em comum, diferenças e registrem um acordo."],privacy:"A comparação aparece após as duas pessoas responderem e consentirem. Os participantes e o administrador master podem consultá-la. Cada participante pode encerrar a dupla.",color:"communication",image:"/images/experiences/communication-v2.webp",imageAlt:"Duas pessoas conversando para alinhar formas de trabalhar"},
  {slug:"energy",number:"04",title:"Mapa de Energia",audience:"Para qualquer profissional",duration:"2 min por registro",summary:"Registre atividades que dão energia ou desgastam e perceba padrões ao longo dos dias.",steps:["Escolha o tipo de atividade e registre como ela afetou sua energia.","Observe o resumo por categoria e por dia.","Se quiser, compartilhe somente o resumo com uma liderança ou o RH."],privacy:"Líderes e RH recebem apenas o resumo que você compartilhar. Você e o administrador master podem consultar o diário completo na área de Resultados.",color:"energy",image:"/images/experiences/energy-v2.webp",imageAlt:"Profissional revendo atividades e energia da rotina"},
  {slug:"career",number:"05",title:"Bússola de Carreira",audience:"Para qualquer profissional",duration:"6 min",summary:"Explore prioridades e tensões nas suas escolhas profissionais sem receber um rótulo ou um cargo ideal.",steps:["Responda oito dilemas concretos do trabalho.","Veja as prioridades que apareceram nas suas escolhas.","Refaça a experiência quando desejar e compare com tentativas anteriores."],privacy:"Você e o administrador master podem consultar suas respostas e resultados. Eles servem para reflexão, não para previsão de desempenho.",color:"career",image:"/images/experiences/career-v2.webp",imageAlt:"Profissional comparando caminhos de carreira"},
  {slug:"thermometer",number:"06",title:"Termômetro de Liderança",audience:"Para líderes e equipes",duration:"2 min por rodada",summary:"Acompanhe poucos comportamentos ao longo do tempo após concluir um ciclo do Espelho do Líder.",steps:["Escolha até três comportamentos do seu ciclo concluído.","A mesma equipe responde a rodadas curtas de acompanhamento.","Compare a evolução das percepções agregadas em gráficos simples."],privacy:"Cada média exige encerramento da rodada e pelo menos cinco respostas válidas por comportamento. Nenhuma resposta individual é exibida.",color:"thermometer",image:"/images/experiences/thermometer-v2.webp",imageAlt:"Equipe acompanhando mudanças em comportamentos de liderança"},
] as const;

export type PublicExperience=(typeof publicExperiences)[number];
